### ISSUE TITLE
Update command

### ISSUE THREAD

**Issue by c4pt0r** [pingcap/docs#1019]
File: [tispark/tispark-quick-start-guide.md](https://pingcap.com/docs/tispark/tispark-quick-start-guide/)

mysql -h 192.168.0.2 -P 4000 -u root < dss.ddl
shoule be
mysql --local-infile=1 -h 192.168.0.2 -P 4000 -u root < dss.ddl

**Comment by CaitinChen** [comment]
Fixed at: https://github.com/pingcap/docs/pull/1020

**Comment by ilovesoup** [comment]
Confirmed from Dev and this change should applied to all version of tidb.

**Comment by c4pt0r** [comment]
https://github.com/pingcap/tidb-docker-compose

README

**Comment by CaitinChen** [comment]
I will fix this issue of README soon.

**Comment by CaitinChen** [comment]
@c4pt0r What part should be changed in README.md?

**Comment by CaitinChen** [comment]
Fixed at: https://github.com/pingcap/tidb-docker-compose/pull/61
