### ISSUE TITLE
Docker compose 

### ISSUE THREAD

**Issue by thebennos** [pingcap/docs#103]
Related to 
https://github.com/pingcap/docs/blob/master/op-guide/docker-compose.md

Do not see that opening so much port is needed, like 
    ports:
      - "2379"
      - "2380"

I think internal ports (expose) is enough for pd and tikv.

**Comment by tennix** [comment]
@thebennos Yes, you're right. Thank you for pointing out that. We'll fix it in #104

**Comment by tennix** [comment]
This is already fixed in [tidb-docker-compose](https://github.com/pingcap/tidb-docker-compose). By default we only expose PD 2379 and TiDB 4000/10080 ports. And users can expose other ports using helm to generate customized docker-compose.yml if needed.
