### ISSUE TITLE
The link to create an issue should be of type bug

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#1044]
File: [trouble-shooting.md](https://pingcap.com/docs/trouble-shooting/)

Change: https://github.com/pingcap/tidb/issues/new
To: https://pingcap.com/docs/report-issue/

Or alternatively: https://github.com/pingcap/tidb/issues/new?template=bug-report.md (the current link skips the template and chooser.)

**Comment by CaitinChen** [comment]
Thanks. Fixed at: https://github.com/pingcap/docs/pull/1091
