### ISSUE TITLE
Document dumpling interaction with tikv_gc_life_time

### ISSUE THREAD

**Issue by kolbe** [pingcap/docs#10526]
The documentation for dumpling at https://docs.pingcap.com/tidb/stable/dumpling-overview notes "Support automatic adjustment of TiDB GC time for TiDB v4.0.0 and above". But there is some important nuance here that is not explained.

When dumpling connects to TiDB, it will get the address of a PD server in the cluster. Dumpling will then try to connect to the PD server (in part to determine if the PD server is actually part of the same cluster as the TiDB server). If the connection to the PD server fails, a message will be written to the log:

> meet error while check whether fetched pd addr and TiDB belong to one cluster. This won't affect dump process

The reason dumpling tries to connect to PD is so that it can use the UpdateServiceGCSafePoint PD API call (see https://github.com/pingcap/dumpling/issues/95). That API call permits a TTL to be used, so that the value of `tikv_gc_life_time` will be reverted to its original value after some period of time. This is important because a change to the `tikv_gc_life_time` system variable using a `SET VARIABLE` SQL statement cannot be reverted to the original value if dumpling exits prematurely.

In many deployments, it is not possible for dumpling to connect directly to PD. This is especially true when using a Kubernetes deployment, or when using TiDB Cloud. In those cases, dumpling will write this message to its log:

> If the amount of data to dump is large, criteria: (data more than 60GB or dumped time more than 10 minutes)\nyou'd better adjust the tikv_gc_life_time to avoid export failure due to TiDB GC during the dump process.\nBefore dumping: run sql `update mysql.tidb set VARIABLE_VALUE = '720h' where VARIABLE_NAME = 'tikv_gc_life_time';` in tidb.\nAfter dumping: run sql `update mysql.tidb set VARIABLE_VALUE = '10m' where VARIABLE_NAME = 'tikv_gc_life_time';` in tidb.

This behavior of dumpling is not documented. The documentation should make these things clear:
* that dumpling can only "Support automatic adjustment of TiDB GC time for TiDB" if it is possible for dumpling to connect directly to PD
* that dumpling cannot connect directly to PD if connected to a TiDB cluster running in Kubernetes (unless dumpling itself is run inside the Kubernetes environment)
* that dumpling cannot connect directly to PD if connecting to a TiDB Cloud cluster
* that it is critical to manually change tikv_gc_life_time if dumpling cannot do this automatically
* that the user should manually change tikv_gc_life_time back to its original value after dumpling exits (successfully or unsuccessfully)

**Comment by lichunzhu** [comment]
Good point! I have no problem about documentation that should be made clear.
`UpdateServiceGCSafePoint` won't affect `tikv_gc_life_time`. They are two different kind of systems. It's used to make sure specified won't be garbage collected with ttl.
In the future we may use sql to do this `UpdateServiceGCSafePoint` job to avoid connecting to PD.

**Comment by kolbe** [comment]
I don't understand your point about these being "two different kind of systems".

See https://github.com/pingcap/tidb/blob/master/dumpling/export/dump.go?plain=1#L1437

In tidbStartGCSavepointUpdateService, if dumpling has a PD client connection, it will execute pdClient.UpdateServiceGCSafePoint. Otherwise, it will output the message telling the user to manually change tikv_gc_life_time.

**Comment by lichunzhu** [comment]
If`UpdateServiceGCSafePoint` can't work, users need to set tikv_gc_life_time.
I mean they are doing the same thing(avoid data being gced). But `UpdateServiceGCSafePoint` can't affect tikv_gc_life_time.
