### ISSUE TITLE
帮忙说明清楚，这部分的值该填什么

### ISSUE THREAD

**Issue by glkappe** [pingcap/docs#10679]
File: [/release-6.1/tidb-cloud/set-up-private-endpoint-connections.md](https://docs.pingcap.com/tidbcloud/set-up-private-endpoint-connections)
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/21033020/194743721-13502cfc-a034-4de9-b18f-eb97a89fbf02.png">

**Comment by glkappe** [comment]
这个 service name 的值从哪里获取到呢？

**Comment by benmaoer** [comment]
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/24819510/194746593-3da9a862-ddf5-43bf-a491-5e13a003894c.png">

When the endpoint service is created, take a note of your endpoint service name from the command in the lower area of the console.
