### ISSUE TITLE
Documentation live backup to tikv

### ISSUE THREAD

**Issue by cicerocomp** [pingcap/docs#110]

**Comment by siddontang** [comment]
Hi @cicerocomp 

Do you mean sending SIGUSR2 to TiKV and backup the data?  If yes, we will remove this mechanism and use an HTTP API after we introduce gRPC.

**Comment by cicerocomp** [comment]
I actually wanted documentation to know how to `tikv` backup. 
Is it possible to do incremental backup?

**Comment by siddontang** [comment]
we don't support live backup now, it is not in the RoadMap currently.

Reopen if we support it later.
