### ISSUE TITLE
Non-Transactional DML page issues

### ISSUE THREAD

**Issue by mjonss** [pingcap/docs#11217]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/tidb/stable/non-transactional-dml

2. How would you like to improve it?

Please clarify how `KILL TIDB` command can be used with an example:
![Screenshot 2022-11-06 at 23 40 55](https://user-images.githubusercontent.com/5520054/200253228-04da4cce-3d28-4056-b044-61c00f8b6b28.png)

**Comment by TomShawn** [comment]
@ekexium Could you please take a look and provide the information? Thanks

**Comment by ekexium** [comment]
Simply `show processlist` to get the connection id and then `kill tidb`.
I'll try to complement it later.

**Comment by TomShawn** [comment]
@mjonss @ekexium Maybe we only need to add a link to https://docs.pingcap.com/tidb/dev/sql-statement-kill.
![image](https://user-images.githubusercontent.com/41534398/200514247-fa799e69-9c47-472f-a9ec-fec92e8d1250.png)

**Comment by mjonss** [comment]
> @mjonss @ekexium Maybe we only need to add a link to https://docs.pingcap.com/tidb/dev/sql-statement-kill.

Link is ok.

**Comment by TomShawn** [comment]
@mjonss @ekexium PTAL https://github.com/pingcap/docs/pull/11252

**Comment by TomShawn** [comment]
@mjonss The link is added. Can we close this issue?
