### ISSUE TITLE
max-merge-region-keys vs max-merge-region-rows

### ISSUE THREAD

**Issue by dotmanila** [pingcap/docs#1151]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
https://www.pingcap.com/docs/dev/reference/tools/pd-control/

2. How would you like to improve it?
max-merge-region-rows seems outdated, actual code refers to max-merge-region-keys
https://github.com/pingcap/pd/blob/master/server/config.go#L462

**Comment by disksing** [comment]
Hi @dotmanila , thanks for your report. The `pd-control` document is located in `docs/dev/reference/tools/pd-control.md`. And yes the document is outdated, thanks again. We will start to fix it.
