### ISSUE TITLE
Better explanation for not mixing Lightning backends statements

### ISSUE THREAD

**Issue by db-will** [pingcap/docs#11636]
## Change Request

https://github.com/pingcap/docs/blob/master/tidb-lightning/tidb-lightning-physical-import-mode.md
```
When you use multiple TiDB Lightning to import data to the same target, do not mix the backends. That is, do not use the physical import mode and the logical import mode at the same time.
```

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
`Same target` is a bit confusing here, as it may refer to same table or same database, or same cluster.
Further explanation for why not mixing backends provided could help readers to have better understand about this statement here

2. Describe your suggestion or addition.
As described above

3. Provide some reference materials (such as documents and websites) if you could.

**Comment by ran-huang** [comment]
Thanks for the feedback. It should be "the same target table". I'll fix the doc asap.
