### ISSUE TITLE
Request to update for Recommended Action

### ISSUE THREAD

**Issue by qiaoxinke** [pingcap/docs#12236]
File: [/release-6.5/tidb-cloud/monitor-built-in-alerting.md](https://docs.pingcap.com/tidbcloud/monitor-built-in-alerting)

In the "Recommended Action" of [TiDB Cloud built-in alert conditions], most of our recommended solutions are adding additional nodes such as for tidb, tikv, tiflash.
I knows we have supported scale up feature now. In some cases, a scale up or expanding storage size is also a good way to solve the alert like memory,cpu,storage utilization.
Can we try to provide more specified workaround for each alert considering their characteristic.
Thank you.

**Comment by qiancai** [comment]
@qiaoxinke Thanks for your suggestion. 

@lilyjazz Would you please look at the suggestion in this issue? If it is valid, please help update the recommended actions for users. Thanks.

**Comment by lilyjazz** [comment]
@qiaoxinke thank you for your advice.

I will optimize the context on the mail and doc.

**Comment by qiancai** [comment]
This issue had been fixed in https://github.com/pingcap/docs/pull/12463 and the https://docs.pingcap.com/tidbcloud/monitor-built-in-alerting#tidb-cloud-built-in-alert-conditions doc now provides the recommended actions.
