### ISSUE TITLE
TiDB Cloud doesn't support Audit Log now

### ISSUE THREAD

**Issue by shenli** [pingcap/docs#12230]
File: [/release-6.5/tidb-cloud/tidb-cloud-auditing.md](https://docs.pingcap.com/tidbcloud/tidb-cloud-auditing)
Users can not setup audit log themself. The `Audit Admin` role is hidden now.

**Comment by qiancai** [comment]
Hi @shenli Thanks for your feedback. 

Hi @ljun0712  Would you please confirm how can users get the `Adudit Admin` role for TiDB Cloud? Thanks.

**Comment by ljun0712** [comment]
The database audit log is controlled by a whitelist, and the customer needs to provide the Org ID, which can only be viewed after being modified by the developer.
please check:
https://github.com/tidbcloud/app-delivery/blob/main/core-svc/envs/prod/oneconfig-central-configmap.yaml
(After upgrading the database audit log capability, TiDB Cloud will cancel the whitelist control)

**Comment by qiancai** [comment]
@ljun0712 I've added a note in https://github.com/pingcap/docs/pull/12253/files to guide users to apply for the database audit logging feature. PTAL. Thanks.

**Comment by qiancai** [comment]
The note has been added to [Database Audit Logging | PingCAP Docs](https://docs.pingcap.com/tidbcloud/tidb-cloud-auditing) as follows. 

![image](https://user-images.githubusercontent.com/79440533/215643139-eade7cd8-f35c-46d7-978e-9b181efacf3b.png)

@shenli Please let us know if this note addresses this issue. If no other concerns, we will close this issue.

**Comment by shenli** [comment]
looks good to me, thanks!
