### ISSUE TITLE
Add `check <cluster-name> <scale-out.yml> --cluster	` option

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs#12234]
File: [/release-6.5/tiup/tiup-component-cluster-check.md](https://docs.pingcap.com/tidb/stable/tiup-component-cluster-check)

[TiUP v1.9.0](https://github.com/pingcap/tiup/releases/tag/v1.9.0) supports checking the yaml file before scale out via https://github.com/pingcap/tiup/pull/1659

```
'	check <cluster-name> <scale-out.yml> --cluster	'
```

Please consider to add this usage to the document because this command is very useful to validate the yaml file before scaling out.

**Comment by shichun-0415** [comment]
@yahonda Thanks for your suggestion.
@qqqdan Could you please help take a look?
