### ISSUE TITLE
tidb-configuration-file: missing labels

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#12987]
## Error Report

Page: https://docs.pingcap.com/tidb/dev/tidb-configuration-file

This should document this part of the config:
```
[labels]
zone = "<zone>"
dc = "<dc>"
rack = "<rack>"
host = "<host>"
```

This is described on other pages like https://docs.pingcap.com/tidb/dev/schedule-replicas-by-topology-labels#optional-configure-labels-for-tidb

**Comment by qiancai** [comment]
Hi @glorv, as the label configuration was added by you in https://github.com/pingcap/docs-cn/pull/11242, would you please also create a PR to add the config info to https://github.com/pingcap/docs-cn/pull/11242? Thanks.

**Comment by glorv** [comment]
Yeah, I thinks we should also add this missing config in the tidb-config-file. https://github.com/pingcap/docs-cn/pull/13522 Here is the PR for Chinese doc.
