### ISSUE TITLE
Improve naming-conventions-for-data-import.md

### ISSUE THREAD

**Issue by okJiang** [pingcap/docs#13030]
https://github.com/pingcap/docs/blob/bddaae6f483c0ecd8e8f8ca330134753716c902a/tidb-cloud/naming-conventions-for-data-import.md?plain=1#L51

the rules of xxxxx, such as what it consists of, need to be explained.

**Comment by Oreoxmt** [comment]
@frank945946 Would you please create a PR to add the naming rule (such as only numbers are allowed, the max length is ...) of `[.XXXXXX]` here?

**Comment by Frank945946** [comment]
@dsdashun PTAL

**Comment by okJiang** [comment]
I can do this. Let me check it in code.

**Comment by okJiang** [comment]
There are several file formats available now.

1. `${db_name}.${table_name}[.xxxxx].csv`, where `xxxxx` is composed of numbers and there is no limit to the quantity.
2. `${db_name}.${table_name}[._xxx_xxx_xxx].csv`, where `xxx` is composed of numbers and there is no limit to the quantity.
3. `${db_name}.${table_name}[_xxx_xxx_xxx].csv`, where `xxx` is composed of numbers and there is no limit to the quantity.
