### ISSUE TITLE
"ROWS" missing from reserved keywords list

### ISSUE THREAD

**Issue by kaeverens** [pingcap/docs#1328]
1. Describe what you find is inappropriate or missing in the existing docs.

I diagnosed an issue with a query that was working in MySQL but is not working in TiDB, and think that TiDB has reserved the keyword "ROWS"

2. Describe your suggestion or addition.

The [Reserved Keywords](https://pingcap.com/docs/v3.0/reference/sql/language-structure/keywords-and-reserved-words/#keywords-and-reserved-words) doc page does not mention ROWS. It should probably be added, or removed from the engine's reserved list.

3. Provide some reference materials (documents, websites, etc) if you could.

example query that's causing me trouble:

`insert into user32_invoices set rows="";
`

adding backticks around "rows" makes it work

**Comment by lilin90** [comment]
@CaitinChen Please help add `ROWS` to the [Reserved Keywords](https://pingcap.com/docs/v3.0/reference/sql/language-structure/keywords-and-reserved-words/#keywords-and-reserved-words) table for `v3.0` and `dev`. Thanks!

**Comment by CaitinChen** [comment]
@lilin90 OK

**Comment by CaitinChen** [comment]
Fixed at https://github.com/pingcap/docs/pull/1428, https://github.com/pingcap/docs-cn/pull/1720

**Comment by CaitinChen** [comment]
"ROWS (R)" is not a reserved word in v2.1. I remove it in https://github.com/pingcap/docs/pull/1431
