### ISSUE TITLE
refine description

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/docs#1419]
https://pingcap.com/docs/v3.0/how-to/maintain/backup-and-restore/
there is one note "You can use mydumper to export data from MySQL and loader to import the data into TiDB."
which we just use tidb not mysql, maybe it should be "mydumper & loader are used for mysql protocol and can be used for tidb"

**Comment by ericsyh** [comment]
"You can use mydumper to export data from TiDB and loader to import the data into TiDB." will be more accurate since it's backup and restore not migrate.
