### ISSUE TITLE
Update Docker Compose link

### ISSUE THREAD

**Issue by lilin90** [pingcap/docs#1427]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.

    Update the Docker Compose deployment file link.

2. Describe your suggestion or addition.

    Only keep Docker Compose deployment in `dev`.

3. Provide some reference materials (documents, websites, etc) if you could.

    N/A

**Comment by ran-huang** [comment]
@lilin90 Can we close this issue now? It looks outdated to me. 

btw, I find this doc [TiDB Docuker Compose Deployment](https://docs.pingcap.com/tidb/dev/deploy-test-cluster-using-docker-compose) but it's not in the TOC.
