### ISSUE TITLE
metricstool link doesn't work

### ISSUE THREAD

**Issue by choudharypankaj** [pingcap/docs#14928]
File: [/release-5.1/exporting-grafana-snapshots.md](https://docs.pingcap.com/tidb/v5.1/exporting-grafana-snapshots)

The metricstool link is broken:
MetricsTool can be accessed from https://metricstool.pingcap.com/.

**Comment by Oreoxmt** [comment]
@choudharypankaj Thanks for your feedback! I have created a PR to update the link of MetricsTool to <https://metricstool.pingcap.net>.

> **Note**:
>
> - Starting from TiDB v6.0.0, PingCAP no longer maintains MetricsTool. Starting from v6.1.0, PingCAP no longer maintains the MetricsTool document.
> - To export monitoring metrics data, use the [PingCAP Clinic diagnostic service](https://docs.pingcap.com/tidb/dev/clinic-introduction) to get the information required for diagnosing a TiDB cluster, including the monitoring metrics, logs, cluster topology, configuration, and parameters.
