### ISSUE TITLE
TiCDC Overview does not provide details about the Storage Sink capabilities

### ISSUE THREAD

**Issue by benmeadowcroft** [pingcap/docs#14957]
File: [/release-7.1/ticdc/ticdc-overview.md](https://docs.pingcap.com/tidb/stable/ticdc-overview)

This document includes mentions of the TiCDC support for multiple sinks including other TiDB Clusters, MySQL, and Kafka but it does not mentioned TiCDC's support for storage services like AWS S3.

There is some information in other pages of the documentation, such as https://docs.pingcap.com/tidb/stable/ticdc-sink-to-cloud-storage, but this info should also be reflected in the overview page.

**Comment by Oreoxmt** [comment]
@benmeadowcroft I have created a PR to update the overview page https://github.com/pingcap/docs/pull/14958 PTAL
