### ISSUE TITLE
对于 Read 来说，也是一样的操作，唯一不同在于 Leader 可以直接提供 Read，不需要走 Raft。

### ISSUE THREAD

**Issue by jingyugao** [pingcap/docs#1518]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
https://pingcap.com/blog-cn/how-tikv-store-get-data/

2. How would you like to improve it?

据我所知，读leader的时候，为了保证leader没有离线，导致读到stale值，需要走一个noop log。
可以用read index 和 lease 进行优化。但是这里“直接read”，这个表述是不是有些问题。或者说，允许读到stale的值？

**Comment by zhangjinpeng1987** [comment]
@jingyugao in leader we use lease read.

**Comment by CaitinChen** [comment]
@jingyugao Do you have any comment?

**Comment by jingyugao** [comment]
> @jingyugao Do you have any comment?

Thanks.
