### ISSUE TITLE
Provide dictionary for Japanese

### ISSUE THREAD

**Issue by likidu** [pingcap/docs#15248]

**Comment by shhdgit** [comment]
In CI testing.

Limitation of OpenAI
- Output max token: 4k
  - https://platform.openai.com/docs/models
  - Whether it's GPT-3.5 (16k context) or GPT-4 (128k context), the maximum token limit for their output is 4k. This limitation hinders the ability to translate in scenarios where the input-to-output ratio is 1:1. Segmented translation is necessary, but it results in the loss of context, leading to a decrease in translation effectiveness compared to translating the entire text. However, the max token limit for the input is not fully restricted, and what is limited by the output is the original content of the input. We can enhance output effectiveness in such scenarios through few-shot techniques in subsequent iterations. Further research is needed to explore more universally effective ways to provide translation context.

**Comment by likidu** [comment]
Target on comparing the service cost end of December.
