### ISSUE TITLE
Add more guidance for "perform bit-reverse on the generated IDs" 

### ISSUE THREAD

**Issue by Tetsuya3850** [pingcap/docs#15263]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.
I was reading this page's this section.
https://docs.pingcap.com/tidb/stable/dev-guide-unique-serial-number-generation
"Finally, note that the IDs generated by the above two solutions are not random enough to be directly used as primary keys for TiDB tables. In practice, you can perform bit-reverse on the generated IDs to get more random new IDs."
While I do get that probably this means that since snowflake style uuids are basically increasing, it can cause hotspots so we need to modify the value by bit-reverse. However, what does it specifically mean by bit-reverse? If we can clarify here, ideally with an example snippet code, it could be a little more approachable.

2. Describe your suggestion or addition.
Provide more clear guidance for "perform bit-reverse on the generated IDs", ideally with examples.

3. Provide some reference materials (such as documents and websites) if you could.
https://docs.pingcap.com/tidb/stable/dev-guide-unique-serial-number-generation

**Comment by Oreoxmt** [comment]
@Icemap PTAL. Thanks!

**Comment by Tetsuya3850** [comment]
@Icemap Hi, if you can please take a look at your convenience?

**Comment by Icemap** [comment]
Got it, let me see. For the `bit-reverse`, it means to reverse this number by bit, for example:

- `00000010100101000001111010011100` after bit-reverse, it will be `00111001011110000010100101000000`.
- `11111111111111111111111111111101` after bit-reverse, it will be `10111111111111111111111111111111`.

**Comment by Tetsuya3850** [comment]
@Icemap Thank you! I opened a PR to add the same. https://github.com/pingcap/docs/pull/15748
If you can please review 🙇
