### ISSUE TITLE
Add a tip about using double quotes to the docs search result page

### ISSUE THREAD

**Issue by lilin90** [pingcap/docs#15368]
When users search a system variable or config parameter, sometimes they fail to find the exact result. For example, searching _tidb_store_batch_size_ without double quotes ([Algolia advanced syntax](https://www.algolia.com/doc/api-reference/api-parameters/advancedSyntax/)) can't get the exactly matched pages:
![image](https://github.com/pingcap/docs/assets/30922556/68b090ff-5283-4b33-bc08-8824b2957e65)

But if you surround it with double quotes, you can get two exactly matched pages:
![image](https://github.com/pingcap/docs/assets/30922556/0e4fe18b-032c-47f4-8287-e5f574e8b9f2)

It can help users to find what they want if we provide a search **Tip**, like the **[Tip in the general TiDB docs page](https://docs.pingcap.com/tidb/stable/extended-statistics)**.

![image](https://github.com/pingcap/docs/assets/30922556/8e8c2a11-d0d2-4652-aa3c-1141efae9b0c)

**Comment by ran-huang** [comment]
Tip text:

- English: Use double quotes for exact match. For example, "deploy TiDB".
- Chinese: 使用双引号进行精确搜索。例如，"部署 TiDB"。
- Japanese: フレーズを正確に検索したい場合に「"」で囲って利用します。例えば、"TiDBデプロイ"。
