### ISSUE TITLE
Enrich Documentation: TiDB String Functions 

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#15417]
**Overview**

The current [document for TiDB's string functions](https://docs.pingcap.com/tidb/dev/string-functions) provides basic information for each [supported function](https://docs.pingcap.com/tidb/dev/string-functions#supported-functions) without detailed descriptions and examples. To make this document more comprehensive and user-friendly, we welcome external contributors to enrich the instructions for each string function.

**Objectives**

- Enhance the document for TiDB's string functions by providing detailed instructions and examples for each function.
- Ensure consistency and clarity in this document.

**Required skills**

- Proficiency in SQL and TiDB string functions.

**Contribution guidelines**

1. Choose two string functions from the list of sub-issues.
2. Go to the sub-issue link of these two string functions.
3. Assign the issue to yourself by commenting `/assign`.
4. Submit a pull request (PR) to the TiDB docs repositories (**either [pingcap/docs](https://github.com/pingcap/docs/pulls) in English or [pingcap/docs-cn](https://github.com/pingcap/docs-cn/pulls) in Chinese, or both**). 
5. In the PR description, indicate which sub-issue this PR resolves, such as "Fix #xxx".

**List of sub-issues**

> Note: Except for the first 11 lines, the other lines in the following list are not issues yet. We'll convert them to sub-issues after the 11 issues are assigned. If you want to enrich instructions for certain string functions that are not sub-issues yet, please add a comment on this issue.

- [x] #15418
- [x] #15482
- [x] #15483
- [x] #15484
- [x] #15485
- [x] #15486
- [x] #15487
- [x] #15488
- [x] #15489
- [x] #15491
- [x] #15490
- [x] #16937
- [x] #16938
- [x] #16939
- [x] #16940
- [x] #16941
- [x] #16942
- [x] #16943
- [x] #16944
- [x] #16945

**Additional information**

- To learn how to create a pull request, see [TiDB Documentation Contributing Guide](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md).
- Make sure to test your provided instructions in TiDB. To quickly get started with TiDB Cloud or TiDB, check out the following guides:
     - [TiDB Cloud Quick Start | PingCAP Docs](https://docs.pingcap.com/tidbcloud/tidb-cloud-quickstart)
    - [Quick Start Guide for the TiDB Database Platform | PingCAP Docs](https://docs.pingcap.com/tidb/stable/quick-start-with-tidb)
- **DO NOT** copy instructions from documentation of other databases.

Thank you for contributing to the improvement of TiDB's documentation! If you have any questions, feel free to comment on this issue.

**Comment by kjhuang-db** [comment]
who can participate in this 文档挑战赛？

**Comment by qiancai** [comment]
> who can participate in this 文档挑战赛？

Anyone interested is welcome to participate in this event. For enriching documentation, you can either create a PR in English at [pingcap/docs](https://github.com/pingcap/docs/pulls), or create a PR  in Chinese at [pingcap/docs](https://github.com/pingcap/docs/pulls), or both**

**Comment by kjhuang-db** [comment]
@qiancai sorry I miss, when does it end?

**Comment by dveeden** [comment]
Looks like multi argument `CHAR()` isn't documented yet
