### ISSUE TITLE
Enrich Documentation: ADMIN CHECKSUM TABLE

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#15468]
**Overview**

According to [My Top 10 Feature Requests for TiDB](https://tidb-blog.vercel.app/posts/my-top-10-feature-requests), the current [ADMIN CHECKSUM TABLE](https://docs.pingcap.com/tidb/dev/sql-statement-admin-checksum-table) document for TiDB is "poorly documented as to what it actually checks".  To make this document more comprehensive and user-friendly, we welcome external contributors to add more information about its purpose, usage scenarios, examples in these scenarios, and output explanations. 

**Required skills**

Proficiency in TiDB statements.

**Contribution guidelines**

1. Assign the issue to yourself by commenting `/assign`.
2. Submit a pull request (PR) to the TiDB docs repositories (either [pingcap/docs](https://github.com/pingcap/docs/pulls) in English or [pingcap/docs-cn](https://github.com/pingcap/docs-cn/pulls) in Chinese, or both).
3. In the PR description, indicate which issue this PR resolves, such as  "Fix [#15468](https://github.com/pingcap/docs/issues/15468)".

**Comment by takaidohigasi** [comment]
correct link for ADMIN CHECKSUM TABLE would be 
https://github.com/pingcap/docs/blob/611cddeb452ec2a652b1a644e36079fa6e1253a4/sql-statements/sql-statement-admin-checksum-table.md

**Comment by qiancai** [comment]
Hi @takaidohigasi, thanks a lot for catching that. I've fixed the link in the issue description.
