### ISSUE TITLE
Enrich instructions for string functions  BIT_LENGTH() and CHAR()

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#15482]
This is a sub-issue of https://github.com/pingcap/docs/issues/15417. 

This sub-issue aims to enrich instructions for string functions [BIT_LENGTH()](https://docs.pingcap.com/tidb/dev/string-functions#bit_length) and [CHAR()](https://docs.pingcap.com/tidb/dev/string-functions#char).

**Contribution guidelines**
You can either enrich the instructions in English or Chinese. 

1. Assign the issue to yourself by commenting `/assign`.
2. Submit a pull request (PR) to the TiDB docs repositories (either [pingcap/docs](https://github.com/pingcap/docs/pulls) in English or [pingcap/docs-cn](https://github.com/pingcap/docs-cn/pulls) in Chinese, or both). 
3. In the PR description, indicate which sub-issue this PR resolves, such as "Fix #15482".

**Comment by rpaik** [comment]
👋 @PitifulPete, just a friendly reminder to submit your PR for TiDB Docs Dash by January 12 at 07:59 UTC. 🙏 

Please reach out if you have any questions or need any help.

**Comment by qiancai** [comment]
@PitifulPete thank you so much for dedicating time to enrich instructions for string functions [BIT_LENGTH()](https://docs.pingcap.com/tidb/dev/string-functions#bit_length) and [CHAR()](https://docs.pingcap.com/tidb/dev/string-functions#char). ❤️. Since the PR https://github.com/pingcap/docs/pull/16087 for this issue has been merged, we will proceed to close this issue. If you come across any documentation issues in the future, please don't hesitate to create an issue or pull request in this repository 🚀.

**Comment by PitifulPete** [comment]
> @PitifulPete thank you so much for dedicating time to enrich instructions for string functions [BIT_LENGTH()](https://docs.pingcap.com/tidb/dev/string-functions#bit_length) and [CHAR()](https://docs.pingcap.com/tidb/dev/string-functions#char) ❤️. Since the PR #16087 for this issue has been merged, we will proceed to close this issue. If you come across any documentation issues in the future, please don't hesitate to create an issue or pull request in this repository 🚀.

my pleasure 🙏
