### ISSUE TITLE
Enrich instructions for string functions  CHAR_LENGTH() and CHARACTER_LENGTH()

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#15483]
This is a sub-issue of https://github.com/pingcap/docs/issues/15417. 

This sub-issue aims to enrich instructions for string functions [CHAR_LENGTH()](https://docs.pingcap.com/tidb/dev/string-functions#char_length) and [CHARACTER_LENGTH()](https://docs.pingcap.com/tidb/dev/string-functions#character_length).

**Contribution guidelines**
You can either enrich the instructions in English or Chinese. 

1. Assign the issue to yourself by commenting `/assign`.
2. Submit a pull request (PR) to the TiDB docs repositories (either [pingcap/docs](https://github.com/pingcap/docs/pulls) in English or [pingcap/docs-cn](https://github.com/pingcap/docs-cn/pulls) in Chinese, or both). 
3. In the PR description, indicate which sub-issue this PR resolves, such as "Fix #15483".

**Comment by rpaik** [comment]
👋 @PitifulPete thanks for taking on this issue during TiDB Docs Dash! Just a friendly reminder to submit your PR by January 12 at 07:59 UTC. 

Please reach out if you have any questions or need any help.

**Comment by qiancai** [comment]
@PitifulPete thank you so much for dedicating time to enrich instructions for string functions [CHAR_LENGTH()](https://docs.pingcap.com/tidb/dev/string-functions#char_length) and [CHARACTER_LENGTH()](https://docs.pingcap.com/tidb/dev/string-functions#character_length) ❤️. Since the PR https://github.com/pingcap/docs/pull/16057 for this issue has been merged, we will proceed to close this issue. If you come across any documentation issues in the future, please don't hesitate to create an issue or pull request in this repository 🚀.
