### ISSUE TITLE
Enrich instructions for string functions  LIKE and LOCATE()

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#15490]
This is a sub-issue of https://github.com/pingcap/docs/issues/15417. 

This sub-issue aims to enrich instructions for string functions [LIKE](https://docs.pingcap.com/tidb/dev/string-functions#like) and [LOCATE()](https://docs.pingcap.com/tidb/dev/string-functions#locate).

**Contribution guidelines**
You can either enrich the instructions in English or Chinese. 

1. Assign the issue to yourself by commenting `/assign`.
2. Submit a pull request (PR) to the TiDB docs repositories (either [pingcap/docs](https://github.com/pingcap/docs/pulls) in English or [pingcap/docs-cn](https://github.com/pingcap/docs-cn/pulls) in Chinese, or both). 
3. In the PR description, indicate which sub-issue this PR resolves, such as "Fix #15491".

**Comment by rpaik** [comment]
Thanks @Takashi-kun for your contribution to the TiDB Docs Dash 🎉 Just a quick reminder to submit your PR by January 12 at 07:59 UTC ([your local time](https://www.timeanddate.com/worldclock/fixedtime.html?msg=TiDB+Docs+Dash+2024%3A+End&iso=20240112T0759&p1=1440)) 😄

Please let us know if you have any questions.
