### ISSUE TITLE
Debug TiDB Cloud Documentation: Import Local Files to TiDB Cloud

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#15739]
This issue is a sub-issue of [Debug TiDB Cloud Documentation: Summary Issue · Issue #15480 · pingcap/docs](https://github.com/pingcap/docs/issues/15480). The purpose of this sub-issue is to verify and debug the [Import Local Files to TiDB Cloud](https://docs.pingcap.com/tidbcloud/tidb-cloud-import-local-files) document. 

You can follow the instructions provided in [#15480](https://github.com/pingcap/docs/issues/15480) to verify and debug the instructions in this document.

1. After finishing your verification, please add your verification result to this sub-issue as a comment. The result can be the issues you encounter, the mistakes you find, or any other findings. If everything looks fine, you can also add it as a comment.
2. For any issues you found during the verification, welcome to create a pull request (PR) to fix them directly. In the pull request, please indicate which issue this PR resolves in the PR description (for example, fix [#15739](https://github.com/pingcap/docs/issues/15739)). To learn how to create a pull request, see [TiDB Documentation Contributing Guide](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md).

> Note: Currently, the [TiDB Cloud documentation](https://docs.pingcap.com/tidbcloud/) is in English only and it is stored in the `release-7.5` branch of [pingcap/docs](https://github.com/pingcap/docs) for reusing the SQL documentation of TiDB.  Hence, to create a pull request for TiDB Cloud documentation, make sure that your PR is based on the [release-7.5](https://github.com/pingcap/docs/tree/release-7.5) branch.

Your contribution to testing and verifying the documentation is highly appreciated!

**Comment by rpaik** [comment]
👋  @RakerZh,  just a quick reminder to make your TiDB Docs Dash contributions by January 12 at 07:59 UTC.

Let us know if you have any questions!

**Comment by RakerZh** [comment]
## Test Result
Good. Almost all passed.

## Suggestion
Hope there would be more options to import csv file. For example, when import file, there is only primary key option to click. It will be great if there were key selection for `PRI MUI UNI NONE` and `NULL` or not.


## Issue
A small issue for split files larger than 50MB, when total number of lines in file is not exactly divisible by `$n`. 
Shell script in document:
```bash
#!/bin/bash
n=$1
file_path=$2
file_extension="${file_path##*.}"
file_name="${file_path%.*}"
lines_per_file=$(( $(wc -l < $file_path) / $n ))
split -d -a 1 -l $lines_per_file $file_path $file_name.
for (( i=0; i<$n; i++ ))
do
    mv $file_name.$i $file_name.$i.$file_extension
done
```
```bash
sh ./split.sh 4 3.csv
```
Result: `ls -l`
```
.rw-r--r--  467M  12 Jan 00:49  3.0.csv
.rw-r--r--  469M  12 Jan 00:49  3.1.csv
.rw-r--r--  468M  12 Jan 00:49  3.2.csv
.rw-r--r--  469M  12 Jan 00:49  3.3.csv
.rw-r--r--   879  12 Jan 00:49  3.4
.rw-r--r--@ 1.9G   1 Jan 22:12  3.csv
.rw-r--r--   281  12 Jan 00:44  split.sh
```
There will be a 3.4 file with extra lines but without `.csv`.

Fixed:
```bash
#!/bin/bash
n=$1
file_path=$2
file_extension="${file_path##*.}"
file_name="${file_path%.*}"
total_lines=$(wc -l < $file_path)
lines_per_file=$(( (total_lines + n - 1) / n )) 
split -d -a 1 -l $lines_per_file $file_path $file_name.
for (( i=0; i<$n; i++ ))
do
    mv $file_name.$i $file_name.$i.$file_extension
done
```
This will round up the division.
Result after running the same code above: `ls -l`
```
.rw-r--r--  467M  12 Jan 00:56  3.0.csv
.rw-r--r--  469M  12 Jan 00:56  3.1.csv
.rw-r--r--  468M  12 Jan 00:56  3.2.csv
.rw-r--r--  469M  12 Jan 00:56  3.3.csv
.rw-r--r--@ 1.9G   1 Jan 22:12  3.csv
```

**Comment by hfxsd** [comment]
Hi @RakerZh, Thank you sincerely for your valuable contribution to our Docs Dash compaign. Your dedicated effort has significantly enhanced the quality of TiDB documentation. We deeply appreciate your hard work and commitment!
