### ISSUE TITLE
Debug TiDB Cloud Documentation: TiDB Cloud Quick Start

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#15738]
This issue is a sub-issue of [Debug TiDB Cloud Documentation: Summary Issue · Issue #15480 · pingcap/docs](https://github.com/pingcap/docs/issues/15480). The purpose of this sub-issue is to verify and debug the [TiDB Cloud Quick Start](https://docs.pingcap.com/tidbcloud/tidb-cloud-quickstart) document. 

You can follow the instructions provided in [#15480](https://github.com/pingcap/docs/issues/15480) to verify and debug the instructions in this document.

1. After finishing your verification, please add your verification result to this sub-issue as a comment. The result can be the issues you encounter, the mistakes you find, or any other findings. If everything looks fine, you can also add it as a comment.
2. For any issues you found during the verification, welcome to create a pull request (PR) to fix them directly. In the pull request, please indicate which issue this PR resolves in the PR description (for example, fix [#15738](https://github.com/pingcap/docs/issues/15738)). To learn how to create a pull request, see [TiDB Documentation Contributing Guide](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md).

> Note: Currently, the [TiDB Cloud documentation](https://docs.pingcap.com/tidbcloud/) is in English only and it is stored in the `release-7.5` branch of [pingcap/docs](https://github.com/pingcap/docs) for reusing the SQL documentation of TiDB.  Hence, to create a pull request for TiDB Cloud documentation, make sure that your PR is based on the [release-7.5](https://github.com/pingcap/docs/tree/release-7.5) branch.

Your contribution to testing and verifying the documentation is highly appreciated!

**Comment by rpaik** [comment]
👋 @Jellybeanvino, just a quick reminder to make your TiDB Docs Dash contributions by January 12 at 07:59 UTC. 

Let us know if you have any questions!

**Comment by dveeden** [comment]
@Jellybeanvino For Chat2Query AI queries you need to start the line with `-- ` any thing else is either a comment (starts with `#`) or a SQL query. Hope this helps.

**Comment by dveeden** [comment]
An example:
![image](https://github.com/pingcap/docs/assets/1272980/3a5e6269-c049-4849-ba85-294c33ff9ab3)

Here I have a table with names and then I entered:
`-- Give me one name` 
and the system created:
```sql
SELECT
  `name`
FROM
  `names`
LIMIT
  1;
```

When I accept the query (and optionally change bits of it) and then execute it I get:
![image](https://github.com/pingcap/docs/assets/1272980/09badc19-c24f-4edd-bcff-b9ca4aed18e0)

**Comment by dveeden** [comment]
And it can do `INSERT` statements:
![image](https://github.com/pingcap/docs/assets/1272980/d0615b80-e906-4b82-ab71-95c8f7a0adf1)

**Comment by Jellybeanvino** [comment]
> And it can do `INSERT` statements: ![image](https://private-user-images.githubusercontent.com/1272980/295928201-d0615b80-e906-4b82-ab71-95c8f7a0adf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODQ1MjYsIm5iZiI6MTcwNDk4NDIyNiwicGF0aCI6Ii8xMjcyOTgwLzI5NTkyODIwMS1kMDYxNWI4MC1lOTA2LTRiODItYWI3MS05NWM4ZjdhMGFkZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMTQ0MzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTE2YjEwODRjN2M0NDQzMjRjNDYxYTlhM2FlZjMyZDQzMzM0MmMyYzY4ZWViYzdmYWU2ZjI5NDEzMjVjMjY1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OaealyqQmMjjGnmD_LfWtOYvZPXA07VgdBP0EoZKDtc)

@dveeden Thanks for your patient reply. Your example helps me  and now I figure out how to run it. To help other guys like me new to TiDB Cloud or Chat2Query,  adding some simple examples after the tutorial would be better.

**Comment by qiancai** [comment]
Hi @Jellybeanvino, thanks so much for all your valuable comments and the doc update PR ❤️.  As the PR has been merged, I'll close this issue. If you notice any doc issues in the future, feel free to create an issue or PR in the documentation repository.
