### ISSUE TITLE
Debug TiDB Cloud Documentation: Integrate TiDB Cloud with Vercel

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#15746]
This issue is a sub-issue of [Debug TiDB Cloud Documentation: Summary Issue · Issue #15480 · pingcap/docs](https://github.com/pingcap/docs/issues/15480). The purpose of this sub-issue is to verify and debug the [Integrate TiDB Cloud with Vercel](https://docs.pingcap.com/tidbcloud/integrate-tidbcloud-with-vercel) document. 

You can follow the instructions provided in [#15480](https://github.com/pingcap/docs/issues/15480) to verify and debug the instructions in this document.

1. After finishing your verification, please add your verification result to this sub-issue as a comment. The result can be the issues you encounter, the mistakes you find, or any other findings. If everything looks fine, you can also add it as a comment.
2. For any issues you found during the verification, welcome to create a pull request (PR) to fix them directly. In the pull request, please indicate which issue this PR resolves in the PR description (for example, fix [#15746](https://github.com/pingcap/docs/issues/15746)). To learn how to create a pull request, see [TiDB Documentation Contributing Guide](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md).

> Note: Currently, the [TiDB Cloud documentation](https://docs.pingcap.com/tidbcloud/) is in English only and it is stored in the `release-7.1` branch of [pingcap/docs](https://github.com/pingcap/docs) for reusing the SQL documentation of TiDB.  Hence, to create a pull request for TiDB Cloud documentation, make sure that your PR is based on the [release-7.1](https://github.com/pingcap/docs/tree/release-7.1) branch.

Your contribution to testing and verifying the documentation is highly appreciated!

**Comment by Weaxs** [comment]
![Image](https://github.com/pingcap/docs/assets/20680212/6df84377-c182-41b7-9455-8dd897d99e0f)



![Image](https://github.com/pingcap/docs/assets/20680212/e9e84503-1856-4dcc-bd35-b42615650de1)

**Comment by Weaxs** [comment]
![Image](https://github.com/pingcap/docs/assets/20680212/7d3321f3-282d-4619-a55b-497c48835f42)

**Comment by Weaxs** [comment]
I alse tried umami Project with TiDB Cloud Integration.



![Image](https://github.com/pingcap/docs/assets/20680212/b0d083a9-a55d-40ca-82b6-e1cf243f2767)



![Image](https://github.com/pingcap/docs/assets/20680212/0ef3cd62-1d7b-4ab9-9b00-5aa1cbb30471)



![Image](https://github.com/pingcap/docs/assets/20680212/6afcd9b4-08a5-4487-bea4-6d57b002fd0a)

**Comment by qiancai** [comment]
Hi @Weaxs, thank you for dedicating time to review the [Integrate TiDB Cloud with Vercel](https://docs.pingcap.com/tidbcloud/integrate-tidbcloud-with-vercel) document. Your feedback is highly valued ❤️. Since the test results appear satisfactory, we will proceed to close this issue. If you come across any documentation issues in the future, please don't hesitate to create an issue or pull request in this repository.🚀.
