### ISSUE TITLE
Debug TiDB Cloud Documentation: Get Started with Data Service

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#15743]
This issue is a sub-issue of [Debug TiDB Cloud Documentation: Summary Issue · Issue #15480 · pingcap/docs](https://github.com/pingcap/docs/issues/15480). The purpose of this sub-issue is to verify and debug the [Get Started with Data Service](https://docs.pingcap.com/tidbcloud/data-service-get-started) document. 

You can follow the instructions provided in [#15480](https://github.com/pingcap/docs/issues/15480) to verify and debug the instructions in this document.

1. After finishing your verification, please add your verification result to this sub-issue as a comment. The result can be the issues you encounter, the mistakes you find, or any other findings. If everything looks fine, you can also add it as a comment.
2. For any issues you found during the verification, welcome to create a pull request (PR) to fix them directly. In the pull request, please indicate which issue this PR resolves in the PR description (for example, fix [#15743](https://github.com/pingcap/docs/issues/15743)). To learn how to create a pull request, see [TiDB Documentation Contributing Guide](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md).

> Note: Currently, the [TiDB Cloud documentation](https://docs.pingcap.com/tidbcloud/) is in English only and it is stored in the `release-7.5` branch of [pingcap/docs](https://github.com/pingcap/docs) for reusing the SQL documentation of TiDB.  Hence, to create a pull request for TiDB Cloud documentation, make sure that your PR is based on the [release-7.5](https://github.com/pingcap/docs/tree/release-7.5) branch.

Your contribution to testing and verifying the documentation is highly appreciated!

**Comment by rpaik** [comment]
👋 @sgykfjsm,  just a quick reminder to make your TiDB Docs Dash contributions by January 12 at 07:59 UTC.

Let us know if you have any questions!

**Comment by sgykfjsm** [comment]
In item 4 of Step 1. Create a Data App, 
> Click Authorize to authorize access to the application on GitHub.
It would be more clear to clarify this is to be done in the TiDB Cloud console.

**Comment by sgykfjsm** [comment]
In Step 2. Develop an endpoint

> After creating a Data App, a default untitled endpoint is created for you automatically. You can use the default endpoint to access your TiDB Cloud cluster.

The default `untitled endpoint` isn't created.

**Comment by qiancai** [comment]
> In item 4 of Step 1. Create a Data App,
> 
> > Click Authorize to authorize access to the application on GitHub.
> 
> It would be more clear to clarify this is to be done in the TiDB Cloud console.

Yes, agree with you. Thanks for the suggestion.  If you're interested, feel free to create a pull request (PR) to update the documentation directly.

> Note: Currently, the [TiDB Cloud documentation](https://docs.pingcap.com/tidbcloud/) is in English only and it is stored in the `release-7.5` branch of [pingcap/docs](https://github.com/pingcap/docs) for reusing the SQL documentation of TiDB.  Hence, to create a pull request for TiDB Cloud documentation, make sure that your PR is based on the [release-7.5](https://github.com/pingcap/docs/tree/release-7.5) branch.

**Comment by sgykfjsm** [comment]
@qiancai Okay, I will. Let me add some comments more to record what I noticed.

**Comment by sgykfjsm** [comment]
In Step 2. Develop an endpoint, Write SQL statements, "2. Write SQL statements."

> You can also simply type -- followed by your instructions to let AI generate SQL statements automatically.

Maybe we might want to add the notice to inform you that you need to agree with the following dialog.
![image](https://github.com/pingcap/docs/assets/1759349/7d4d6c87-1d33-456d-9054-41c114336703)

**Comment by sgykfjsm** [comment]
In Step 2. Develop an endpoint, Write SQL statements, "3. Run SQL statements."

This part should be aligned with this page https://docs.pingcap.com/tidbcloud/tidb-cloud-quickstart#step-2-try-ai-powered-chat2query-beta:~:text=Run%20the%20SQL%20queries.

**Comment by sgykfjsm** [comment]
In Step 4. Deploy the endpoint, item 2,

> On the right pane of the endpoint details page, you can click the Deployments tab to view the deployed history.

I cannot see the Deployments tab on the right pane.

**Comment by qiancai** [comment]
Hi @sgykfjsm, thanks so much for all your valuable comments and PR ❤️. I've reviewed the PR and merged the changes. If you notice any documentation issues in the future, feel free to create an issue or PR in this doc repository.
