### ISSUE TITLE
Get helm version failed on Mac

### ISSUE THREAD

**Issue by siddontang** [pingcap/docs#1580]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://github.com/pingcap/docs/blob/master/v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube.md#install-helm

```
helm version --client --short | grep -P -o 'v\d+\.\d+\.\d'
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]

```

2. How would you like to improve it?

may should fix on MacOSX

**Comment by tennix** [comment]
Yes, the mac `grep` is from BSD while the Linux `grep` is from GNU, there are some differences between the two version. @Yisaer Could you help to fix this?

**Comment by Yisaer** [comment]
> Yes, the mac `grep` is from BSD while the Linux `grep` is from GNU, there are some differences between the two version. @Yisaer Could you help to fix this?

sure

**Comment by Yisaer** [comment]
fix in https://github.com/pingcap/docs/pull/1582
