### ISSUE TITLE
Does TiKV servers need NTP service on?

### ISSUE THREAD

**Issue by george24601** [pingcap/docs#159]
My understanding is that PD uses etcd to act as timestamp oracle. Therefore, you need NTP on all pd servers to ensure they are not too far off. But I don't see any reference to NTP in TiKV, does that mean we can actually do without it on TiKV servers?

**Comment by siddontang** [comment]
Hi @george24601 

TiKV doesn't need NTP, but I still suggest ensuring the time is accurate because we will record time in the log.
