### ISSUE TITLE
Debug TiDB Cloud Documentation: Connect to TiDB Serverless with WordPress

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#16036]
This issue is a sub-issue of [Debug TiDB Cloud Documentation: Summary Issue · Issue #15480 · pingcap/docs](https://github.com/pingcap/docs/issues/15480). The purpose of this sub-issue is to verify and debug the [Connect to TiDB Serverless with WordPress](https://docs.pingcap.com/tidbcloud/dev-guide-wordpress) document. 

You can follow the instructions provided in [#15480](https://github.com/pingcap/docs/issues/15480) to verify and debug the instructions in this document.

1. After finishing your verification, please add your verification result to this sub-issue as a comment. The result can be the issues you encounter, the mistakes you find, or any other findings. If everything looks fine, you can also add it as a comment.
2. For any issues you found during the verification, welcome to create a pull request (PR) to fix them directly. In the pull request, please indicate which issue this PR resolves in the PR description (for example, fix [#16036](https://github.com/pingcap/docs/issues/16036)). To learn how to create a pull request, see [TiDB Documentation Contributing Guide](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md).

Your contribution to testing and verifying the documentation is highly appreciated!

**Comment by minaelee** [comment]
Step 3 Part 3, should mention what database to select - either the user's own, or the `test` database if only testing.

**Comment by minaelee** [comment]
The tutorial steps worked to connect a test Wordpress installation in Docker to my TiDB cluster.

The way that it ends is abrupt. There should be a note of how to check that the connection worked. E.g. a final step to go to the Chat2Query terminal for the cluster and confirm that wp_ tables now show up under the database indicated.

**Comment by qiancai** [comment]
Hi @minaelee Many thanks for the test and suggestion.

Hi @shizn Would you please take a look at these comments? Thanks.

**Comment by minaelee** [comment]
One more:

>It is highly recommended to run your WordPress in a Linux environment (such as Ubuntu). Run the following command to install them.

Need to be careful about pronoun antecedents. In this case, the final "them" refers back to Docker and Docker Compose, but it is not clear. Reword to:

>It is highly recommended to run your WordPress in a Linux environment (such as Ubuntu). Run the following command to install Docker and Docker Compose.

**Comment by qiancai** [comment]
Hi @minaelee, thank you for dedicating time to verify the [Connect to TiDB Serverless with WordPress](https://docs.pingcap.com/tidbcloud/dev-guide-wordpress) document. Your feedback is highly valued ❤️. Since the PR https://github.com/pingcap/docs/pull/16094 that resolved these issues has been merged, we will proceed to close this GitHub issue. If you come across any documentation issues in the future, please don't hesitate to create an issue or pull request in this repository.
