### ISSUE TITLE
Debug TiDB Cloud Documentation: Connect to TiDB with JetBrains DataGrip

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#16031]
This issue is a sub-issue of [Debug TiDB Cloud Documentation: Summary Issue · Issue #15480 · pingcap/docs](https://github.com/pingcap/docs/issues/15480). The purpose of this sub-issue is to verify and debug the [Connect to TiDB with JetBrains DataGrip](https://docs.pingcap.com/tidbcloud/dev-guide-gui-datagrip) document. 

You can follow the instructions provided in [#15480](https://github.com/pingcap/docs/issues/15480) to verify and debug the instructions in this document.

1. After finishing your verification, please add your verification result to this sub-issue as a comment. The result can be the issues you encounter, the mistakes you find, or any other findings. If everything looks fine, you can also add it as a comment.
2. For any issues you found during the verification, welcome to create a pull request (PR) to fix them directly. In the pull request, please indicate which issue this PR resolves in the PR description (for example, fix [#16031](https://github.com/pingcap/docs/issues/16031)). To learn how to create a pull request, see [TiDB Documentation Contributing Guide](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md).

Your contribution to testing and verifying the documentation is highly appreciated!

**Comment by Weaxs** [comment]
![Image](https://github.com/pingcap/docs/assets/20680212/a02f2d6b-e584-4337-9bae-af86410f0664)

**Comment by qiancai** [comment]
Hi @Weaxs Thank you for dedicating time to verify the [Connect to TiDB with JetBrains DataGrip](https://docs.pingcap.com/tidbcloud/dev-guide-gui-datagrip) document. Your feedback is highly valued ❤️. Since the test results appear satisfactory, we will proceed to close this issue. If you come across any documentation issues in the future, please don't hesitate to create an issue or pull request in this repository.
