### ISSUE TITLE
Always need to scroll to see the system variables because of the header

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs#16325]
File: [/release-7.6/releases/release-7.6.0.md](https://docs.pingcap.com/tidb/v7.6/release-7.6.0)

Every time, I click the link to system variables name, I need to scroll back to see the actual sysvar name because of the header.

### Steps to reproduce
1. Open [TiDB 7.6.0 Release Notes]( https://docs.pingcap.com/tidb/v7.6/release-7.6.0) via Google Chrome or any web browser
2. Click [Cross-database SQL binding](https://docs.pingcap.com/tidb/v7.6/sql-plan-management#cross-database-binding) then click [`tidb_opt_enable_fuzzy_binding`](https://docs.pingcap.com/tidb/v7.6/system-variables#tidb_opt_enable_fuzzy_binding-new-in-v760) to see the detail.

### Expected behavior
Users can see the system variable name and its meanings without additional scroll.

![Screenshot 2024-01-26 at 10 44 53](https://github.com/pingcap/docs/assets/73684/d1535a75-edc6-460e-8827-68258805be13)

### Actual behavior
Users see the header (I do not know if header is the correct term, I mean to say the bar to show "PingCAP logo, Home, TiDB Cloud, TiDB, Playground, Forum, Contact Us") that overlays the sysvar name.

![Screenshot 2024-01-26 at 10 51 05](https://github.com/pingcap/docs/assets/73684/db23f6b1-5ac0-4eb6-8a0e-29b6f4f89d6a)

**Comment by Oreoxmt** [comment]
@Yuiham Could you please take a look at this issue? Thanks

**Comment by Oreoxmt** [comment]
This issue was fixed in https://github.com/pingcap/website-docs/pull/470
