### ISSUE TITLE
GCP Region CIDR should be /16 and /20

### ISSUE THREAD

**Issue by qiaoxinke** [pingcap/docs#16397]
File: [/release-7.5/tidb-cloud/set-up-vpc-peering-connections.md](https://docs.pingcap.com/tidbcloud/set-up-vpc-peering-connections)

> For Google Cloud Region, it is recommended to configure an IP range size between /16 and /21. Supported network addresses 
 include:

 For Google Cloud Region, it is recommended to configure an IP range size between /16 and **/20** corresponding to UI.

**Comment by qqqdan** [comment]
Fixed
