### ISSUE TITLE
What is the tool used to generate your online docs?

### ISSUE THREAD

**Issue by jievince** [pingcap/docs#1664]
I see yours online docs website: http://pingcap.com/docs/
It's beautiful and has version control feature, so what' the tool to make it?

**Comment by YiniXu9506** [comment]
Hi @jievince! We are glad to hear this.

We are using Hugo to build our website. Hugo can render the markdown file to html file. Since every version has its own TOC.md, we have Hugo template to handle these versions according to users' choice.

Appreciate again!

**Comment by jievince** [comment]
Wow, thanks very much. It helps me a lot.

**Comment by yyt030** [comment]
The website is realy perfect. Do you share your config.toml and Hugo theme ?

**Comment by YiniXu9506** [comment]
@yyt030 We are happy you like it. You can refer the[ config.toml](https://github.com/pingcap/pingcap.github.io/blob/src/config.toml) here. Actually we build the theme by ourself. Thanks!
