### ISSUE TITLE
Add field explanations for TiDB `mysql` schema tables

### ISSUE THREAD

**Issue by qiancai** [pingcap/docs#16684]
**Issue**

The [TiDB's `mysql` Schema](https://docs.pingcap.com/tidb/dev/mysql-schema) document lists TiDB system tables but lacks detailed explanations of the fields within these tables.  These explanations are crucial for users to comprehend these tables, particularly tables that are not compatible with MySQL, such as `stats_histograms`.

**Request**

Add field explanations for `mysql` schema tables.

**Comment by dveeden** [comment]
When we do this we need to make clear that the best practice is to use statement instead of directly inspecting system tables where possible. So `SHOW CREATE USER ...` instead of `SELECT ... FROM mysql.user...` etc. This is true for both MySQL, TiDB and other databases.

**Comment by dveeden** [comment]
It would be good to use the same page-per-table approach as is used for `information_schema` tables.
