### ISSUE TITLE
MySQL 5.7 is still referred to instead of MySQL 8.0

### ISSUE THREAD

**Issue by mjonss** [pingcap/docs#16809]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
https://docs.pingcap.com/tidb/stable/cast-functions-and-operators

2. How would you like to improve it?

Change the text and the links to MySQL 8.0.
Notice that there are other links on the same page that is linked to MySQL 8.0.

Also a quick check showed even more 5.7 links in the documentation (possibly more mentioning of MySQL 5.7, where it should be 8.0)

Functions:
- [x] #16823
- [x] #16822
- [x] #16821
- [x] #16820
- [x] #16819
- [x] #16818
- [x] #16817
- [x] #16816
- [x] #16815
- [x] #16814
- [x] #16858

Cloud:
- [x] #16813

**Comment by dveeden** [comment]
This indeed needs to be updated. However this is not something that was omitted by accident. I'll go over this and other pages covering functions and change MySQL 5.7 in links and text to MySQL 8.0 but I also need to check if we need to update anything about MySQL compatibility.

This might also be a good time to add some examples to these pages as well (see also #15417 )

**Comment by dveeden** [comment]
@bb7133 This is the tracking issue for this work.
