### ISSUE TITLE
LOAD DATA is unsupported

### ISSUE THREAD

**Issue by yangwenmai** [pingcap/docs#1682]
## Error Report

LOAD DATA LOCAL INFILE

```
ERROR 1148 (42000) at line 1: the used command is not allowed with this TiDB version
```

tidb version:

```
["Release Version"=v4.0.0-alpha-1034-g3d66e9b2e] ["Git Commit Hash"=3d66e9b2e21ff1cb40f6c6267eb86d5748dbb989] ["Git Branch"=master] ["UTC Build Time"="2019-11-29 01:54:02"] [GoVersion=go1.13.4] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]
```

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://github.com/pingcap/docs/blob/master/dev/how-to/get-started/import-example-database.md

2. How would you like to improve it?

**Comment by imtbkcat** [comment]
@yangwenmai For the mysql client, local data loading is disabled by default. To enable it explicitly, please use the --local-infile=1.

**Comment by CaitinChen** [comment]
> @yangwenmai For the mysql client, local data loading is disabled by default. To enable it explicitly, please use the `--local-infile=1`.

@yangwenmai Does this work for you？

**Comment by jackysp** [comment]
Hi @yangwenmai ,
Please refer to the official FAQ https://pingcap.com/docs/stable/faq/tidb/#error-1148-42000-the-used-command-is-not-allowed-with-this-tidb-version

**Comment by yangwenmai** [comment]
> > @yangwenmai For the mysql client, local data loading is disabled by default. To enable it explicitly, please use the `--local-infile=1`.
> 
> @yangwenmai Does this work for you？

It's worked.
Thanks

**Comment by CaitinChen** [comment]
Docs updated. https://github.com/pingcap/docs/pull/1686
