### ISSUE TITLE
Does "Checkpoint Restore" needs `s3:DeleteObject` or equivalent permissions?

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs#16961]
File: [/master/br/backup-and-restore-storages.md](https://docs.pingcap.com/tidb/dev/backup-and-restore-storages)

Here are the documented minimum privileges for TiKV and BR.

> Minimum privileges for TiKV and Backup & Restore (BR) to access the backup directories during backup: s3:ListBucket, s3:PutObject, and s3:AbortMultipartUpload
> Minimum privileges for TiKV and BR to access the backup directories during restore: s3:ListBucket, s3:GetObject, and s3:PutObject. BR writes checkpoint information to the ./checkpoints subdirectory under the backup directory. When restoring log backup data, BR writes the table ID mapping relationship of the restored cluster to the ./pitr_id_maps subdirectory under the backup directory.

Since TiDB 7.1 supports the "Checkpoint Restore", https://docs.pingcap.com/tidb/stable/br-checkpoint-restore this feature looks executes `DeleteFile` to delete files in S3 or other object storage added via https://github.com/pingcap/tidb/pull/43384

https://github.com/pingcap/tidb/blob/555ce0235229dc370cc8e63574437cf9ee60bdd0/br/pkg/checkpoint/checkpoint.go#L277
https://github.com/pingcap/tidb/blob/555ce0235229dc370cc8e63574437cf9ee60bdd0/br/pkg/checkpoint/checkpoint.go#L858
https://github.com/pingcap/tidb/blob/555ce0235229dc370cc8e63574437cf9ee60bdd0/br/pkg/checkpoint/log_restore.go#L246

Does "Checkpoint Restore" needs `s3:DeleteObject` or equivalent permissions?

**Comment by BornChanger** [comment]
Good catch. Please open a doc pr for it. @yahonda

**Comment by yahonda** [comment]
Will do. Thanks.

**Comment by yahonda** [comment]
Opened https://github.com/pingcap/docs/pull/17111
