### ISSUE TITLE
Update Security Compatibility

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#1724]
## Error Report

1. What is the URL/path of the document related to this issue?

https://pingcap.com/docs/dev/reference/security/compatibility/

2. How would you like to improve it?

Since https://github.com/pingcap/tidb/pull/13955 has merged (and will soon be backported to 3.0), the security compatibility page is out of date.

**Comment by lilin90** [comment]
@lysu Could we remove this line `Using certificates for authentication is not supported #9708` in the [Security Compatibility with MySQL](https://pingcap.com/docs/dev/reference/security/compatibility/) file now?
