### ISSUE TITLE
region vs Region in the page title

### ISSUE THREAD

**Issue by KavyaShivashankar** [pingcap/docs#17408]
File: [/release-7.5/two-data-centers-in-one-city-deployment.md](https://docs.pingcap.com/tidb/stable/two-data-centers-in-one-city-deployment)

Per the doc page, `region` is used to refer to geographical area, and `Region` is used to represent a shard. The title uses capitalized `Region` and can be misleading. Can you please change the title to `Two Availability Zones in one region deployment`

**Comment by hfxsd** [comment]
Thank you for your feedback!
You are right that region and Region have different meanings in our docs. But we use title style for doc tittles, so we have to use Region instead of region in the tittle.
