### ISSUE TITLE
region vs Region

### ISSUE THREAD

**Issue by KavyaShivashankar** [pingcap/docs#17406]
File: [/release-7.5/multi-data-centers-in-one-city-deployment.md](https://docs.pingcap.com/tidb/stable/multi-data-centers-in-one-city-deployment)

Per the doc page, `region` is used to refer to geographical area, and `Region` is used to represent a shard.   The title uses capitalized `Region` and can be misleading.  Can you please change the title to `Multiple Availability Zones in one region Deployment`

**Comment by KavyaShivashankar** [comment]
Same issue in pages

**Comment by hfxsd** [comment]
See this one: https://github.com/pingcap/docs/issues/17408
