### ISSUE TITLE
region vs Region in the page title

### ISSUE THREAD

**Issue by KavyaShivashankar** [pingcap/docs#17407]
File: [/release-7.5/three-data-centers-in-two-cities-deployment.md](https://docs.pingcap.com/tidb/stable/three-data-centers-in-two-cities-deployment)

Per the doc page, region is used to refer to geographical area, and Region is used to represent a shard. The title uses capitalized Region and can be misleading. Can you please change the title to `Multiple Availability Zones in two region deployment`

**Comment by hfxsd** [comment]
See this one https://github.com/pingcap/docs/issues/17408
