### ISSUE TITLE
Documentation on tidb_ddl_reorg_{worker_cnt,batch_size} defaults is wrong

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#1764]
## Error Report

1. What is the URL/path of the document related to this issue?

https://pingcap.com/docs/dev/reference/configuration/tidb-server/tidb-specific-variables/#tidb_ddl_reorg_worker_cnt
https://pingcap.com/docs/dev/reference/configuration/tidb-server/tidb-specific-variables/#tidb_ddl_reorg_batch_size

2. How would you like to improve it?

On a fresh install of TiDB, these are not the defaults:

```
mysql> show global variables like 'tidb_ddl%';
+----------------------------+--------------+
| Variable_name              | Value        |
+----------------------------+--------------+
| tidb_ddl_reorg_worker_cnt  | 4            |
| tidb_ddl_reorg_batch_size  | 256          |
| tidb_ddl_error_count_limit | 512          |
| tidb_ddl_reorg_priority    | PRIORITY_LOW |
+----------------------------+--------------+
4 rows in set (0.01 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-alpha-1334-g07e642c92
Git Commit Hash: 07e642c9230ccb7c1537b27442f1fe8433e65f8a
Git Branch: master
UTC Build Time: 2020-01-08 08:32:04
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

This can either be fixed in code or in the documentation. I think it actually should be fixed in code, these defaults are too low.

**Comment by ran-huang** [comment]
Thanks for reporting this issue!
Please check out this PR https://github.com/pingcap/docs/pull/1974, where we have changed the default value for the two variables in our docs. 
Feel free to ask me if you have any other question.😀

**Comment by ran-huang** [comment]
Closing this issue. If you have any other question, please open a new issue.
