### ISSUE TITLE
Please check with Joey Zhang regarding the updates to replica count for serverless in the code example

### ISSUE THREAD

**Issue by markdonsky** [pingcap/docs#17645]
File: [/release-8.1/tiflash/tiflash-results-materialization.md](https://docs.pingcap.com/tidb/stable/tiflash-results-materialization)

Right now the code example shows REPLICA 1, but if you use this in serverless, you get a warning and the value gets set to 2.

**Comment by qiancai** [comment]
Hi @markdonsky, thanks for the feedback. @joey-yez Has created https://github.com/pingcap/docs/pull/17878 to fix this issue and another issue in the TiDB Cloud HTAP quick start guide.
