### ISSUE TITLE
[Doc] Duplicated sections

### ISSUE THREAD

**Issue by tuananhtd** [pingcap/docs#17640]
File: [/release-8.1/develop/dev-guide-overview.md](https://docs.pingcap.com/tidb/stable/dev-guide-overview)
<img width="1059" alt="image" src="https://github.com/pingcap/docs/assets/14288059/5b904273-0439-46bc-9801-c0861284598d">

**Comment by qiancai** [comment]
Hi @tuananhtd, 

I checked https://docs.pingcap.com/tidb/stable/dev-guide-overview#tidb-transaction-mechanisms but did not find the issue. Would you please take a look at it again? Thanks.

**Comment by tuananhtd** [comment]
It's fixed. Thanks!
