### ISSUE TITLE
Unsupported JSON functions includes JSON_ARRAY_INSERT

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#1766]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

This page https://pingcap.com/docs/dev/reference/sql/functions-and-operators/json-functions/

2. Describe your suggestion or addition.

A minor issue: the function `JSON_ARRAY_INSERT` has been added.

3. Provide some reference materials (documents, websites, etc) if you could.

It was merged in https://github.com/pingcap/tidb/issues/7546

**Comment by XuHuaiyu** [comment]
@wwar Thanks, I think you're right.

/cc @TomShawn

**Comment by TomShawn** [comment]
@XuHuaiyu Please help update the [JSON Functions](https://pingcap.com/docs/dev/reference/sql/functions-and-operators/json-functions/) document to include the added function, thanks!

**Comment by wwar** [comment]
Actually, the page is more out of date. The only functions not supported now are:
```
JSON_MERGE_PATCH
JSON_PRETTY
JSON_ARRAYAGG
```

I manually verified.

**Comment by TomShawn** [comment]
@XuHuaiyu Please help confirm and update the [unsupported JSON function](https://pingcap.com/docs/dev/functions-and-operators/json-functions/#unsupported-functions).
