### ISSUE TITLE
Generated Columns Docs are out of date

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#1767]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.

The docs on [generated columns](https://pingcap.com/docs/stable/reference/sql/generated-columns/) include a note:

> The optimizer in TiDB only uses the index created on a generated stored column. Currently, the optimizer cannot use an index created on a generated virtual column. This issue will be fixed in later TiDB versions (See Issue #5189).

The related issue has been fixed, and this note is no longer correct.

2. Describe your suggestion or addition.

Remove the note, change the example to a VIRTUAL column, since this is typically better.

3. Provide some reference materials (documents, websites, etc) if you could.

There is one bug I found - https://github.com/pingcap/tidb/issues/14455 - but the example as virtual still works. Ideally https://github.com/pingcap/tidb/issues/14456 should be fixed too, since the example will look cleaner, but it is also not essential.

**Comment by XuHuaiyu** [comment]
@wwar Thanks

@TomShawn Hi, @wjhuang2016 will update this doc.

**Comment by TomShawn** [comment]
@wwar Document updated: https://github.com/pingcap/docs-cn/pull/2200. Does it help you?

**Comment by wwar** [comment]
@TomShawn It is much better, but still not ideal.

From here:
https://pingcap.com/docs/stable/reference/sql/generated-columns/

The example of `STORED` should be removed, and just show an example of `VIRTUAL`. There can be a note at the bottom of the page that `STORED` may be useful for computationally complex scenarios + scanning large amounts of data, but the ideal default case should be `VIRTUAL`.

Also on the dev docs:
https://pingcap.com/docs/dev/reference/sql/generated-columns/

It should show an example with https://github.com/pingcap/tidb/pull/14367 - since 4.0 now supports virtual column expression substitution.

**Comment by TomShawn** [comment]
> @TomShawn It is much better, but still not ideal.
> 
> From here:
> https://pingcap.com/docs/stable/reference/sql/generated-columns/
> 
> The example of `STORED` should be removed, and just show an example of `VIRTUAL`. There can be a note at the bottom of the page that `STORED` may be useful for computationally complex scenarios + scanning large amounts of data, but the ideal default case should be `VIRTUAL`.
> 
> Also on the dev docs:
> https://pingcap.com/docs/dev/reference/sql/generated-columns/
> 
> It should show an example with [pingcap/tidb#14367](https://github.com/pingcap/tidb/pull/14367) - since 4.0 now supports virtual column expression substitution.

@wjhuang2016 Please take a look at the feedback, thanks!

**Comment by wjhuang2016** [comment]
@wwar 
Thanks for your feedback.
1. We have a plan to improve our documents, then I will rewrite the generated column docs completely, which will give the example of `virtual` and the usage scenarios about `store` and `virtual`.  
2. The `virtual column expression substitution` is still WIP, it only support base substitution in where clause, we will give a doc about it when this feature is mature.

**Comment by TomShawn** [comment]
@wwar To better manage our issues, I'll close this one. If you have further questions, feel free to open another issue, thanks!
