### ISSUE TITLE
The coarse-grained Region scatter algorithm warning still appears at v8.1

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs#17679]
File: [/release-8.1/br/br-snapshot-guide.md](https://docs.pingcap.com/tidb/stable/br-snapshot-guide)

The coarse-grained Region scatter algorithm warning still appears at the v8.1 document.
> Warning
The coarse-grained Region scatter algorithm (enabled by setting --granularity="coarse-grained") is experimental. It is recommended that you use this feature to accelerate data recovery in clusters with up to 1,000 tables. Note that this feature does not support checkpoint restore.

This document is linked from TiDB 8.1.0 release note https://docs.pingcap.com/tidb/stable/release-8.1.0
that says "Acceleration of cluster snapshot restore speed (GA in v8.0.0)". I think this warning above should be removed.

**Comment by qiancai** [comment]
hi @yahonda, many thanks for the feedback. I've created https://github.com/pingcap/docs/pull/17685 to remove the experimental info.
