### ISSUE TITLE
sql-mode compatibility docs are out of date

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#1768]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

On https://pingcap.com/docs/stable/reference/mysql-compatibility/#sql-modes it says that ORACLE, POSTGRESQL etc are not supported.

But on https://pingcap.com/docs/stable/reference/sql/sql-mode/ it says that these modes are fully supported.

I did a quick test, and it looks like the are now fully supported:

```
mysql> set sql_mode='oracle';
Query OK, 0 rows affected (0.00 sec)

mysql> select @@sql_mode;
+----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                           |
+----------------------------------------------------------------------------------------------------------------------+
| PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_FIELD_OPTIONS,NO_AUTO_CREATE_USER,ORACLE |
+----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

2. Describe your suggestion or addition.

Update compatibility docs.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by XuHuaiyu** [comment]
@wwar Thanks. For the SQL Modes which are deprecated in MySQL 5.7 and removed in MySQL 8.0, TiDB only supports the syntax of them but not the functionality.

@TomShawn We may update the doc to specify this.
