### ISSUE TITLE
update of tidb-ansible-master is needed before rolling update of the cluster

### ISSUE THREAD

**Issue by tshqin** [pingcap/docs#179]
I couldn't rolling update my test cluster from RC4 to V0.8 by following the step 7 in this [page](https://pingcap.com/doc-ansible-deployment#perform-rolling-update)
 I'm not sure if it's a must during every rolling update or just this version.
a renew of the tidb-ansible-master(STEP 3) is needed before doing 7.1, at least from RC4 to V0.8

**Comment by queenypingcap** [comment]
Hi Gin, Could you please shed some light about V0.8? Where did you get it? Thanks!

**Comment by tshqin** [comment]
I was informed yesterday that preGA was released, and I got it by rolling update, all set I checked the tidb version, I saw the preGA is called 0.8
Release Version: 0.8.0
Git Commit Hash: 62c8d39d931b329254cc390c1ae31af27890540a
Git Commit Branch: master
UTC Build Time:  2017-08-29 11:46:09

**Comment by queenypingcap** [comment]
Got it. Thanks! You can deploy the Pre-GA version directly:
git clone -b Pre-GA https://github.com/pingcap/tidb-ansible.git
