### ISSUE TITLE
terraform version needs to be changed 

### ISSUE THREAD

**Issue by jackxwu** [pingcap/docs#1802]
File: [v3.0/tidb-in-kubernetes/deploy/alibaba-cloud.md](https://pingcap.com/docs/v3.0/tidb-in-kubernetes/deploy/alibaba-cloud/)

i was using tidb-operator 1.0.6 and apparently it needs terraform 12

**Comment by cofyc** [comment]
thanks! you're right, 0.12.x is required now

**Comment by cofyc** [comment]
xref: https://github.com/pingcap/tidb-operator/issues/1659

**Comment by CaitinChen** [comment]
@cofyc Please help update related docs. Thanks.
