### ISSUE TITLE
Spelling mistake of variable tidb_enable_auto_analyze

### ISSUE THREAD

**Issue by bernard-zulzi** [pingcap/docs#18036]
File: [/release-8.1/statistics.md](https://docs.pingcap.com/tidb/stable/statistics)

Change `tidb_enable_auto_anlyze` under https://docs.pingcap.com/tidb/stable/statistics#automatic-update to `tidb_enable_auto_analyze`.

**Comment by dveeden** [comment]
Maybe also add `anlyze` to `styles/config/vocabularies/PingCAP/reject.txt`

**Comment by qiancai** [comment]
> Maybe also add `anlyze` to `styles/config/vocabularies/PingCAP/reject.txt`

I searched "anlyze" in the docs repository and found only two instances of it introduced in https://github.com/pingcap/docs/commit/2c4e6512a1ffa85946308aa6b4ad04d854269d02. Considering its infrequency, we might opt to skip adding it to reject.txt.

**Comment by qiancai** [comment]
Hi @bernard-zulzi, thanks for the catch. The bot has closed this issue as it is fixed in https://github.com/pingcap/docs/pull/18168.
