### ISSUE TITLE
helm version missing

### ISSUE THREAD

**Issue by oraluben** [pingcap/docs#1818]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://github.com/pingcap/docs/blob/master/v3.0/tidb-in-kubernetes/reference/tools/in-kubernetes.md

2. How would you like to improve it?

There're some major changes (e.g. [#7052](https://github.com/helm/helm/issues/7052)) between helm 2 and 3.
From https://pingcap.com/docs/stable/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube/ it seems the doc is based on helm 2.
Though the default way to install helm `curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash` do get helm 2 installed but a lot of them don't, like [the brew way mentioned in doc](https://pingcap.com/docs/stable/tidb-in-kubernetes/reference/tools/in-kubernetes/). It would be great if the helm version is specified.

**Comment by cofyc** [comment]
thanks for reporting this bug! yes, the required version of helm is 2. we didn't support helm 3 yet. 
we should use the specific way to install helm 2, not helm 3. does helm provide a way to install latest helm 2?

**Comment by oraluben** [comment]
I'm not familiar with helm and looks like they are trying to move to 3 in most of the package managers, and `https://raw.githubusercontent.com/helm/helm/master/scripts/get` installs version 2 for backward compatibility.

**Comment by cofyc** [comment]
got it, we can continue to use this backward compatible install command. 
but we should specify our required version of helm in docs as you suggested. can you send a PR for this?

**Comment by oraluben** [comment]
sure. Am I supposed to only update the latest version (dev & 3.x) or all version?

**Comment by cofyc** [comment]
Thanks! all versions (dev, 3.0, 3.1) should be updated.
