### ISSUE TITLE
How to redirect Wiki to https://github.com/pingcap/docs?

### ISSUE THREAD

**Issue by WreathCrystal** [pingcap/docs#184]
That is a useful operation for me , but I did not work out how to config. Could anyone tell me ? Thanks in advance !

**Comment by shenli** [comment]
@WreathCrystal Sorry, I do not get your point.

**Comment by WreathCrystal** [comment]
1) Access to website:  https://github.com/pingcap/docs/wiki
    The page should show something like this: 
    
![image](https://user-images.githubusercontent.com/26850311/30003800-124a5d12-90f6-11e7-8925-8824a9a31380.png)

  but actually  The content is changed to 
![image](https://user-images.githubusercontent.com/26850311/30003813-585a16a8-90f6-11e7-8d2d-fc5365ff6dbd.png)

2) You  visit  the website : https://github.com/pingcap/tikv  to try ,  then you will  get it.

**Comment by WreathCrystal** [comment]
I got it . The answer is  GitHub Pages.
