### ISSUE TITLE
TiCDC example include wrong values 

### ISSUE THREAD

**Issue by choudharypankaj** [pingcap/docs#19006]
File: [/release-8.1/ticdc/ticdc-open-protocol.md](https://docs.pingcap.com/tidb/stable/ticdc-open-protocol)

INSERT INTO test.t1(id, val) VALUES (1, 'aa');
INSERT INTO test.t1(id, val) VALUES (2, 'aa')

From the following Log 5 and Log 6, you can see that Row Changed Events on the same table might be sent to different partitions based on the primary key, but changes to the same row are sent to the same partition so that the downstream can easily process the Event concurrently.

The corresponding output is wrong:
5. [partition=0] [key="{\"ts\":415508878783938562,\"scm\":\"test\",\"tbl\":\"t1\",\"t\":1}"] [value="{\"u\":{\"id\":{\"t\":3,\"h\":true,\"v\":1},\"val\":{\"t\":15,\"v\":\"YWE=\"}}}"]
6. [partition=1] [key="{\"ts\":415508878783938562,\"scm\":\"test\",\"tbl\":\"t1\",\"t\":1}"] [value="{\"u\":{\"id\":{\"t\":3,\"h\":true,\"v\":2},\"val\":{\"t\":15,\"v\":\"YmI=\"}}}"]

and so are the remaining output values

**Comment by qiancai** [comment]
@3AceShowHand Would you please take a look at the following feedback and update the docs if necessary? Thanks.

**Comment by 3AceShowHand** [comment]
@choudharypankaj Can you explain in more detail, what's wrong with this example ?

**Comment by choudharypankaj** [comment]
@3AceShowHand The value is wrong
INSERT INTO test.t1(id, val) VALUES (1, 'aa');


5. [partition=0] [key="{"ts":415508878783938562,"scm":"test","tbl":"t1","t":1}"] 
[value="{"u":{"id":{"t":3,"h":true,"v":1},
**"val":{"t":15,"v":"YWE="}}}"]**


shouldn't it be:

"val":{"t":15,"v":"aa"}}}"]

**Comment by 3AceShowHand** [comment]
This example data was copied from the logs, those value is encoded. we have proposed PR to fix this.
