### ISSUE TITLE
Version picker jumps to the wrong release notes

### ISSUE THREAD

**Issue by likidu** [pingcap/docs#19031]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

Go to
https://docs.pingcap.com/tidb/stable/release-8.1.0

Now if you select the other DMR version, for example, v8.3, it won't jump to the right version of the release notes.

Check this video for the wrong behaviors:

https://github.com/user-attachments/assets/a73e0f82-6ce5-4f76-9fe1-d7e28e936578

3. How would you like to improve it?

Jump to the right version of the release notes.

**Comment by Yuiham** [comment]
I believe it is expected behavior, not a bug. Each version's docs contain release notes for several TiDB versions. You are currently looking at the release notes for TiDB v8.1 in the stable version docs, and it makes sense to remain on this release note after switching to the v8.3 version.

**Comment by lilin90** [comment]
Yes, it is the expected behavior by design.
