### ISSUE TITLE
BR English documentation is not updated in time

### ISSUE THREAD

**Issue by GregoryIan** [pingcap/docs#1930]
Recently, many developers and users have asked about BR, but at present, our English documentation for BR is not up-to-date and needs to be updated. Thank you. 

https://pingcap.com/docs-cn/dev/reference/tools/br/use-cases/#%E5%A4%87%E4%BB%BD%E5%A4%B1%E8%B4%A5

**Comment by lilin90** [comment]
@TomShawn Please address my comments in #1808. Thanks!

**Comment by TomShawn** [comment]
> @TomShawn Please address my comments in #1808. Thanks!

Comments addressed, PTAL again, thanks!

**Comment by lilin90** [comment]
@GregoryIan FYI. #1808 Waiting for @3pointer's review now, or you can have a review.

**Comment by TomShawn** [comment]
@GregoryIan Now the BR English document is updated: [BR Usage Scenarios](https://pingcap.com/docs/dev/reference/tools/br/use-cases/), FIY.

**Comment by ran-huang** [comment]
Hi, @GregoryIan! Is this issue resolved by https://github.com/pingcap/docs/pull/1808? If so, we may close the issue now.
