### ISSUE TITLE
Config to always use tidb_snapshot

### ISSUE THREAD

**Issue by nicodemus26** [pingcap/docs#212]
I'm looking to use TiDB/TiKV as a mirror for data with an upstream source of truth for sequence/time. I'd like to use the `tidb_snapshot` system variable to impose a time on inserts, and to perform snapshot reads.

The documentation here https://github.com/pingcap/docs/blame/master/op-guide/history-read.md#L25 implies that the PD clock may override tidb_snapshot if there is a large difference. I would prefer to be able to turn that off with some configuration if possible, so that the client can impose snapshot times.

Is there some settable config that exists, or could it be added, to accommodate this need?

Thank you!

**Comment by shenli** [comment]
@nicodemus26 I think you misunderstand the document.

> Because the timestamp in TiDB transactions is allocated by Placement Driver (PD), the version of the stored data is also marked based on the timestamp allocated by PD. When a Snapshot is created, the version number is based on the value of the tidb_snapshot variable. If there is a large difference between the local time of the TiDB server and the PD server, use the time of the PD server. 

For each transaction, TiDB will apply for a timestamp from PD. So the version of the data is the local time of PD. Consider this scenario: PD's local time is `2017-09-07 00:00:00` and TiDB's local time is `2017-10-07 00:00:00`. If you want to read the data of three days ago, you should set `tidb_snapshot` to `2017-09-04 00:00:00`. 
In one word, you should use the PD's local time as the base line when you want to read history data and TiDB will **not override** the value in `tidb_snapshot`.

**Comment by nicodemus26** [comment]
I need to **write** data at a certain time, determined upstream. These writes may come out of order, but they carry their timestamp along. will `tidb_snapshot` use **my** time for writes, or will it adopt the PD's?

**Comment by shenli** [comment]
No, You can't use `tidb_snapshot` to do this. The version of data will always be assigned by PD. 
And when you set `tidb_snapshot` in a session, [this session will become readonly](https://github.com/pingcap/tidb/blob/master/executor/adapter.go#L176). It is dangerous to update a historical data, we are worried about the data consistency. For example, there is a unique key constraint for a table. If you could update the historical data, the constraint may be violated.

**Comment by nicodemus26** [comment]
In that case we may need to rework our design a bit. I was hoping to lean on the TiKV vector clocks to push data in parallel. I suppose we can serialize the data per-table and record which PD times correlate with which upstream times. This significantly complicates our design, though.

**Comment by nicodemus26** [comment]
Can I select the PD time used for a commit through TiDB?

**Comment by shenli** [comment]
No, you can't choose the TSO.

**Comment by nicodemus26** [comment]
Sorry, I mean may I read out the TSO chosen by TiDB/PD for a TiDB commit?

**Comment by shenli** [comment]
You can use the tidb's specific system variable [`tidb_current_ts`](https://github.com/pingcap/tidb/blob/master/sessionctx/variable/tidb_vars.go#L53):
> mysql> select @@tidb_current_ts;
> +-------------------+
> | @@tidb_current_ts |
> +-------------------+
> | 0                 |
> +-------------------+
> 1 row in set (0.01 sec)
> 
> mysql> begin;
> Query OK, 0 rows affected (0.01 sec)
> 
> mysql> select @@tidb_current_ts;
> +--------------------+
> | @@tidb_current_ts  |
> +--------------------+
> | 395210627849650177 |
> +--------------------+
> 1 row in set (0.00 sec)
> 
> mysql> commit;
> Query OK, 0 rows affected (0.01 sec)
> 
> mysql> select @@tidb_current_ts;
> +-------------------+
> | @@tidb_current_ts |
> +-------------------+
> | 0                 |
> +-------------------+
> 1 row in set (0.00 sec)
> 
> mysql> 
>

**Comment by nicodemus26** [comment]
Thanks for the help! I'll see about correlating PD's TSOs with my upstream timestamps.
