### ISSUE TITLE
部署方式连接404

### ISSUE THREAD

**Issue by isacc-repo** [pingcap/docs#2126]
File: [-cn/_index.md](https://pingcap.com/docs-cn/)

**Comment by ran-huang** [comment]
Hi, thanks for pointing out!
Please visit <https://pingcap.com/docs-cn/stable/overview/> rather than <https://pingcap.com/docs-cn>.

**Comment by YiniXu9506** [comment]
@isacc-repo Thanks for your feedback! We have fixed this issue, PTAL! @ran-huang FYI

**Comment by ran-huang** [comment]
Closing this issue. If you have any other question, feel free to open a new issue~
