### ISSUE TITLE
部署方式中的几个链接都打不开

### ISSUE THREAD

**Issue by shuperry** [pingcap/docs#2133]
File: [-cn/_index.md](https://pingcap.com/docs-cn/)

**Comment by ran-huang** [comment]
Hi, thanks for pointing out!
You can try it here: https://pingcap.com/docs-cn/stable/overview/

**Comment by shuperry** [comment]
Ok, this one works.

**Comment by ran-huang** [comment]
Glad to hear that.
I'll close this issue now. If you have any other question, feel free to ask us😀
