### ISSUE TITLE
Add the BR repo link to its user guide

### ISSUE THREAD

**Issue by lilin90** [pingcap/docs#2273]
## Change Request

Describe your suggestion or addition.

Add the [BR (Backup & Restore) tool's GitHub repository link](https://github.com/pingcap/br) for [its user guide](https://pingcap.com/docs/stable/reference/tools/br/br/) page, to make it easier to check the repository.

```
[Backup & Restore](http://github.com/pingcap/br)
```

Related issue: https://github.com/pingcap/docs-cn/issues/2733

**Comment by ran-huang** [comment]
Closed in https://github.com/pingcap/docs/pull/2384
