### ISSUE TITLE
Out of date FAQs

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#2325]
## Error Report

These  FAQs are out of date, and not part of the challenge program, so I am filing a bug report here.

1. What is the URL/path of the document related to this issue?

https://pingcap.com/docs/stable/faq/tidb/

2. How would you like to improve it?

> TiDB show processlist displays the estimated memory usage (unit: Byte) of the current session, which is not displayed in MySQL show processlist.

SHOW PROCESSLIST no longer shows memory (not mysql compatible behavior). The memory stats are in information_schema.processlist though.

> What's the maximum number of concurrent connections that TiDB supports?
> The current TiDB version has no limit for the maximum number of concurrent connections. If too large concurrency leads to an increase of response time, you can increase the capacity by adding TiDB nodes.

This is now config dependent - max_connections. Default is still unlimited.

> Does TiDB support CBO (Cost-Based Optimization)? If yes, to what extent?
> Yes. TiDB uses the cost-based optimizer. The cost model and statistics are constantly optimized. TiDB also supports correlation algorithms like hash join and soft merge.

It should be sort merge, not soft merge. I believe "correlation" was meant to be join as well.

**Comment by ran-huang** [comment]
@wwar Thanks for your feedback!
@zz-jason PTAL~
