### ISSUE TITLE
How do you generate your PDF manual?

### ISSUE THREAD

**Issue by Amber1990Zhang** [pingcap/docs#2428]
## Question

I'm trying to get my own PDF manual with a lot of markdowns files. How do you make that? Thanks for your response.

**Comment by TomShawn** [comment]
@YiniXu9506 Please take a look, thanks!

**Comment by Amber1990Zhang** [comment]
> @YiniXu9506 Please take a look, thanks!

Thanks for your reply.

**Comment by Amber1990Zhang** [comment]
Hello? Is anybody out there to help? Many thanks.

**Comment by YiniXu9506** [comment]
Hi @Amber1990Zhang ! Firstly, we merge all markdown files to a single markdown file. Secondly, we use [pandoc](https://pandoc.org/MANUAL.html)  to convert this single markdown file to PDF. Hope this will help you!

**Comment by Amber1990Zhang** [comment]
> Hi @Amber1990Zhang ! Firstly, we merge all markdown files to a single markdown file. Secondly, we use [pandoc](https://pandoc.org/MANUAL.html) to convert this single markdown file to PDF. Hope this will help you!
Thanks for your reply, but how do you take care the TOC?

**Comment by YiniXu9506** [comment]
Do you mean the TOC of PDF file? If the structure of your final single markdown file has h1, h2, h3 and so on, pandoc will generate the PDF TOC for you automatically.

**Comment by Amber1990Zhang** [comment]
How do you merge all markdown files into one?

**Comment by TomShawn** [comment]
To better manage issues in this repository, I'll close this stale issue for now. You are welcome to reopen it if you still have other questions.
