### ISSUE TITLE
Document ANALYZE TABLE incompatibilities with MySQL

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#2478]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

ANALYZE TABLE docs need updating.

2. Describe your suggestion or addition.

See comment here for suggested text: https://github.com/pingcap/tidb/issues/16570#issuecomment-624431150

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by toutdesuite** [comment]
@zz-jason PTAL. Thanks~
