### ISSUE TITLE
Generate h1 from hugo title

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#2633]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.

This is just a minor nit/cleanup for consistency:

Currently the title of the page is only used to generate the `<title>` tag. It could also be used to generate the first H1 of the document, as is common in other templates I've worked with.

2. Describe your suggestion or addition.

It can be retrofitted with some automation and a few steps:

1. Add a YAML property called `generate-h1-from-title: false` to all of the documents (this can be automated in a regular expression).
2. Update the template to generate a h1 only when `generate-h1-from-title: true`.
3. Add a followup PR which removes the YAML property and the H1 when it is safe to do so (this can be automated for some documents, in other cases there are variations, such as when an introduced version is included in the H1. These cases can be handled later with an additional YAML property - which might be helpful on its own).

3. Provide some reference materials (documents, websites, etc) if you could.

The main goal here is to reduce the duplication and inconsistencies. As a followup step, the TOC (and titles in the TOC) could also be automatically generated, as is common with other hugo templates.

**Comment by toutdesuite** [comment]
@lilin90 @YiniXu9506 PTAL, thanks
