### ISSUE TITLE
Document Invisible Indexes

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#2634]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

There is currently no documentation for invisible indexes.

2. Describe your suggestion or addition.

It should be added to:
- Its own reference page
- The statements section
- The compatibility with MySQL page will need updating

3. Provide some reference materials (documents, websites, etc) if you could.

https://github.com/pingcap/tidb/pulls?q=is%3Apr+invisible+indexes+is%3Aclosed

**Comment by toutdesuite** [comment]
@bb7133 PTAL, thanks

**Comment by TomShawn** [comment]
@wwar Thanks very much. We do have invisible indexes-related documents that are not yet translated into English. The translation takes time and please stay tuned.

**Comment by wwar** [comment]
Awesome! The docs-cn document is looking good.

**Comment by nullnotnil** [comment]
Fixed in https://github.com/pingcap/docs/pull/2971
