### ISSUE TITLE
Improve introduction / overview

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#2636]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

The "introduction" section of the docs could be improved with starting points about the 4.0 release, and TiDB as a project.

2. Describe your suggestion or addition.

```
Introduction
  v4.0 in a nutshell (i.e. overview of what's new)
  History (new content)
  Benchmarks (existing content)
  Adopters (move from top-level)
  Hardware and OS Recommendations (existing content)
```

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by toutdesuite** [comment]
@wwar Many thanks for your suggestion!

**Comment by ran-huang** [comment]
@wwar We have a [new structure](https://docs.pingcap.com/tidb/stable/overview) for the introduction part now. Do you have any suggestion for this?

**Comment by wwar** [comment]
LGTM, closing this issue.
