### ISSUE TITLE
Flatten How-to -> Get Started and Deploy

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#2638]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

I think it has been discussed before, but one of the problems with the current TOC is that there is too much structure overhead. I have a proposal to reduce that.

2. Describe your suggestion or addition.

The sections "Get Started" and "Deploy" can be renamed and merged as "Install". When there is an install type that has both a "Development" and a "Production" style of deployment, these should be tabs in the page instead - not overhead in the structure.

This makes it easier to read.

3. Provide some reference materials (documents, websites, etc) if you could.

I came up with a mockup (using the generic book hugo template) showing how this would work:

![image](https://user-images.githubusercontent.com/59209078/83220251-bd51a200-a12f-11ea-962d-b817c19e0129.png)

**Comment by toutdesuite** [comment]
@wwar Many thanks for your suggestion. The TOC (Chinese) has been updated, while the English version is to be updated. Once the translation done, I' ll leave a link in this issue~

**Comment by ran-huang** [comment]
@lilin90 PTAL~ I think using tabs is a good idea!
Like, in the following backup & restore docs, we can just group these similar docs together and use tabs to indicate the remote storage (GCS/S3) or the tools (BR/Dumpling/TiDB Lightning).
https://docs.pingcap.com/tidb-in-kubernetes/stable/backup-to-gcs
![image](https://user-images.githubusercontent.com/59654584/89366106-c602bd80-d708-11ea-8cda-03dcc8e9fc21.png)

**Comment by wwar** [comment]
Here is an example in the [Kubernetes docs](https://kubernetes.io/docs/setup/production-environment/container-runtimes/) where this is done. I think it helps readability a lot.

**Comment by lilin90** [comment]
@wwar It has been changed to a flat structure now, with **Quick Start** and **Deploy**. https://docs.pingcap.com/tidb/stable So I'll close this issue. Thanks!
![image](https://user-images.githubusercontent.com/30922556/94224232-6bc1f400-ff24-11ea-89b2-31c37a9c188f.png)
