### ISSUE TITLE
Document ADMIN commands

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#2639]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

In the statement reference, admin is documented all as one command: https://pingcap.com/docs/stable/sql-statements/sql-statement-admin/

2. Describe your suggestion or addition.

These should be documented individually:
```
ADMIN CANCEL DDL
ADMIN CHECK [TABLE|INDEX]
ADMIN CHECKSUM TABLE
ADMIN PLUGINS
ADMIN RECOVER INDEX
ADMIN RELOAD
ADMIN REPAIR TABLE
ADMIN SHOW DDL
```

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by toutdesuite** [comment]
@crazycs520 PTAL, thanks

**Comment by nullnotnil** [comment]
Here is a more up to date list of all the admin commands:
```
ADMIN CANCEL DDL
ADMIN CAPTURE BINDINGS
ADMIN CHECK [TABLE|INDEX]
ADMIN CHECKSUM TABLE
ADMIN EVOLVE BINDINGS
ADMIN FLUSH BINDINGS
ADMIN PLUGINS
ADMIN RECOVER INDEX
ADMIN RELOAD
ADMIN RELOAD BINDINGS
ADMIN REPAIR TABLE
ADMIN SHOW DDL
ADMIN SHOW SLOW
```

**Comment by nullnotnil** [comment]
My plan is to break this up into smaller PRs:

First PR:
```
ADMIN CANCEL DDL
ADMIN CHECK [TABLE|INDEX]
ADMIN CHECKSUM TABLE
ADMIN SHOW DDL
```
Second:
```
ADMIN CAPTURE BINDINGS
ADMIN EVOLVE BINDINGS
ADMIN FLUSH BINDINGS
ADMIN RELOAD BINDINGS
```
Third:
```
ADMIN PLUGINS
ADMIN SHOW SLOW
```

Fourth:
```
ADMIN RECOVER INDEX
ADMIN RELOAD
ADMIN REPAIR TABLE
```

**Comment by kolbe** [comment]
Reopen this issue. Many of these commands are still not documented.

**Comment by Oreoxmt** [comment]
@TomShawn PTAL
- [x] [ADMIN CANCEL DDL](https://docs.pingcap.com/tidb/dev/sql-statement-admin-cancel-ddl)
- [ ] ADMIN CAPTURE BINDINGS
- [x] [ADMIN CHECK [TABLE|INDEX]](https://docs.pingcap.com/tidb/dev/sql-statement-admin-check-table-index)
- [x] [ADMIN CHECKSUM TABLE](https://docs.pingcap.com/tidb/dev/sql-statement-admin-checksum-table)
- [ ] ADMIN EVOLVE BINDINGS
- [ ] ADMIN FLUSH BINDINGS
- [ ] ADMIN PLUGINS
- [ ] ADMIN REPAIR TABLE
- [ ] ADMIN RECOVER INDEX
- [ ] ADMIN RELOAD
- [ ] ADMIN RELOAD BINDINGS
- [ ] ADMIN REPAIR TABLE
- [x] [ADMIN SHOW DDL](https://docs.pingcap.com/tidb/dev/sql-statement-admin-show-ddl)
- [ ] ADMIN SHOW SLOW https://docs.pingcap.com/tidb/dev/identify-slow-queries#admin-show-slow-command
- [x] [ADMIN SHOW TELEMETRY](https://docs.pingcap.com/tidb/dev/sql-statement-admin-show-telemetry)

**Comment by shichun-0415** [comment]
@kolbe @Oreoxmt `ADMIN CLEANUP` and `ADMIN RECOVER` have been documented. Till now, all `ADMIN` commands claimed missing are documented properly.
[ADMIN CLEANUP INDEX](https://docs.pingcap.com/tidb/dev/sql-statement-admin-cleanup)
[ADMIN RECOVER INDEX](https://docs.pingcap.com/tidb/dev/sql-statement-admin-recover)
