### ISSUE TITLE
Document SQL statements for binding

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#2640]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

Binding is documented here: https://pingcap.com/docs/stable/execution-plan-binding/#view-binding -- but the statements are not in the statement index: https://pingcap.com/docs/stable/sql-statements/sql-statement-add-column/

2. Describe your suggestion or addition.

They should all be here with examples:
```
CREATE [GLOBAL|SESSION] BINDING
DROP [SESSION|GLOBAL] BINDING
SHOW BINDINGS
```

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by toutdesuite** [comment]
@lamxTyler @zz-jason PTAL, thanks

**Comment by nullnotnil** [comment]
This has been fixed. See: https://docs.pingcap.com/tidb/dev/sql-statement-create-binding
