### ISSUE TITLE
Document Roles syntax in Statement index

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#2641]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

The syntax for roles is not in the statement index: https://pingcap.com/docs/stable/sql-statements/sql-statement-drop-user/

2. Describe your suggestion or addition.

```
CREATE ROLE
DROP ROLE
GRANT <role> (split GRANT privileges and GRANT role).
SET DEFAULT ROLE
SET ROLE
etc
```

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by toutdesuite** [comment]
@bb7133 PTAL, thanks
