### ISSUE TITLE
System Databases section of manual is confusing

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#2642]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

See: https://pingcap.com/docs/stable/system-tables/system-table-cluster-info/

The structure has the following as system databases (as formatted code):

```
mysql
information_schema
sql-diagnosis
```

But if I use `mysql`, the system databases are:

```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| INFORMATION_SCHEMA |
| METRICS_SCHEMA     |
| PERFORMANCE_SCHEMA |
| mysql              |
| test               |
+--------------------+
5 rows in set (0.00 sec)
```

2. Describe your suggestion or addition.

These show really correspond to where they are in the product. For example, some of the ones under sql-diagnosis are actually information_schema tables.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by toutdesuite** [comment]
@reafans PTAL, thanks~

**Comment by toutdesuite** [comment]
@crazycs520 PTAL, thanks~

**Comment by nullnotnil** [comment]
I would like to work on this if that works for you?
