### ISSUE TITLE
Make 1 version of Roadmap

### ISSUE THREAD

**Issue by wwar** [pingcap/docs#2643]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

Currently the roadmap appears in every version of the manual:
https://pingcap.com/docs/stable/roadmap/
https://pingcap.com/docs/dev/roadmap/
https://pingcap.com/docs/v3.1/roadmap/
https://pingcap.com/docs/v3.0/roadmap/

What's weirder, is the pages differ.

2. Describe your suggestion or addition.

It doesn't really make sense to have a roadmap for anything except future versions, so this content should really be all the same. There should be some way to harmonize this / force this content to be identical.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by toutdesuite** [comment]
@lilin90 @yikeke PTAL~

**Comment by uglyengineer** [comment]
PMG (Product Management Group) will confirm a new presentation of TiDB Roadmap

**Comment by yikeke** [comment]
I removed the /roadmap.md link from TOC.md in master and all release branches, so now the docs website has no entry for the roadmap content, but users can still access roadmap.md via the URL. FYI @nullnotnil @scsldb @uglyengineer

**Comment by nullnotnil** [comment]
Even though the version-specific roadmaps are removed from the TOC, they are still in search engine results. I think this is easy to fix by just cherry-picking `/roadmap.md` into all of the version-specific branches.

**Comment by yikeke** [comment]
> Even though the version-specific roadmaps are removed from the TOC, they are still in search engine results. I think this is easy to fix by just cherry-picking `/roadmap.md` into all of the version-specific branches.

Do we even need a roadmap in all version-specific branches? If a roadmap is for future versions (we are talking about v5.0 right?), how about we just keep the roadmap in the `dev` version and removing all current roadmaps in other version-specific branches? @scsldb @nullnotnil

**Comment by nullnotnil** [comment]
That works for me - since it only applies to `dev` anyway. I assume it is possible to add aliases in the roadmap.md from dev to handle redirects from all other versions.

**Comment by yikeke** [comment]
Right, aliases are necessary to fix the 404s. 

Does it work for you or the PMG too? @scsldb If you agree, I will send the PR then.

**Comment by yikeke** [comment]
The roadmap will only be kept in the [master branch](https://docs.pingcap.com/zh/tidb/dev/roadmap) from today on.
