### ISSUE TITLE
Changed: br Sub command "version" is now an option --version

### ISSUE THREAD

**Issue by rachitmanit** [pingcap/docs#2754]
File: [/br/backup-and-restore-tool.md](https://pingcap.com/docs/v4.0/br/backup-and-restore-tool/)

**Comment by TomShawn** [comment]
@3pointer @overvenus PTAL, thanks!
![image](https://user-images.githubusercontent.com/41534398/84225687-688c2f00-ab12-11ea-8213-555b5c0f8ed7.png)

**Comment by overvenus** [comment]
Thank you for the feedback, we will update it soon!
