### ISSUE TITLE
Could not compile `tikv`.

### ISSUE THREAD

**Issue by xming4321** [pingcap/docs#29]
use setup script :  

Compiling rocksdb v0.3.0 (https://github.com/ngaut/rust-rocksdb.git#4c8e2192)
src/lib.rs:15:1: 15:18 error: #[feature] may not be used on the stable release channel [E0554]
src/lib.rs:15 #![feature(test)]
              ^~~~~~~~~~~~~~~~~
src/lib.rs:16:1: 16:34 error: #[feature] may not be used on the stable release channel [E0554]
src/lib.rs:16 #![feature(optin_builtin_traits)]
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:17:1: 17:44 error: #[feature] may not be used on the stable release channel [E0554]
src/lib.rs:17 #![feature(btree_range, collections_bound)]
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:18:1: 18:19 error: #[feature] may not be used on the stable release channel [E0554]
src/lib.rs:18 #![feature(fnbox)]
              ^~~~~~~~~~~~~~~~~~
src/lib.rs:19:1: 19:19 error: #[feature] may not be used on the stable release channel [E0554]
src/lib.rs:19 #![feature(alloc)]
              ^~~~~~~~~~~~~~~~~~
src/lib.rs:20:1: 20:20 error: #[feature] may not be used on the stable release channel [E0554]
src/lib.rs:20 #![feature(plugin)]
              ^~~~~~~~~~~~~~~~~~~
src/lib.rs:21:1: 21:28 error: #[feature] may not be used on the stable release channel [E0554]
src/lib.rs:21 #![feature(slice_patterns)]
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:22:1: 22:24 error: #[feature] may not be used on the stable release channel [E0554]
src/lib.rs:22 #![feature(box_syntax)]
              ^~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:23:1: 23:22 error: #[feature] may not be used on the stable release channel [E0554]
src/lib.rs:23 #![feature(const_fn)]
              ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to 9 previous errors
error: Could not compile `tikv`.

**Comment by shenli** [comment]
@xming4321 Do you use nightly rustc?

**Comment by siddontang** [comment]
Hi @xming4321 
You must use the nightly Rust version, not stable.

**Comment by siddontang** [comment]
Hi @overvenus 

I think we can use the check requirement script script at the beginning of the build script.
