### ISSUE TITLE
Should we move the DM Download to the DM documentation instead? 

### ISSUE THREAD

**Issue by Ishiihara** [pingcap/docs#3156]
File: [/download-ecosystem-tools.md](undefined/tidb/v4.0/download-ecosystem-tools)

**Comment by toutdesuite** [comment]
@WangXiangUSTC PTAL, thanks~

**Comment by WangXiangUSTC** [comment]
I think it's ok

**Comment by ran-huang** [comment]
@WangXiangUSTC Is there any update on this issue?

**Comment by WangXiangUSTC** [comment]
> @WangXiangUSTC Is there any update on this issue?

I will do this this week
