### ISSUE TITLE
Translate TiDB deployment overview document into English

### ISSUE THREAD

**Issue by shenli** [pingcap/docs#32]
See https://github.com/pingcap/docs-cn/blob/master/op-guide/overview.md
@queenypingcap

**Comment by queenypingcap** [comment]
Got it!

**Comment by queenypingcap** [comment]
Finished in the following commits:
faa9ef456294ad5c96d89d09e022a95d90a60c2c
392d76b7ef15cfa22da8a5421407aab5fa8e6c88
