### ISSUE TITLE
At-rest Encryption

### ISSUE THREAD

**Issue by kaeverens** [pingcap/docs#331]
I'm sorry if this has already been addressed, but I don't see it mentioned in the documentation.

Does TiDB support at-rest encryption, where the data in the storage system is encrypted so that hackers that gain access to the server cannot simply read the data in the files?

This is an important feature which other databases such as MySQL 5.7 and Mongo 3.2 have introduced. The European GDPR laws coming into force this year don't state that encryption at-rest is required, but it is strongly implied that if a hacker were to gain access to a server hosting data, and the data is not encrypted, then the server-owner must make the breach public.

**Comment by shenli** [comment]
@kaeverens Thanks for your feedback!
This feature is on our plan but not implemented yet. I will let you know when we finish it.

**Comment by morgo** [comment]
This is being tracked in TiKV as https://github.com/tikv/tikv/issues/3680

I am going to close this issue here to reduce duplication. Thank you for your feature request!
