### ISSUE TITLE
Remove extra escape characters

### ISSUE THREAD

**Issue by yikeke** [pingcap/docs#3357]
Files that need update: 

[/faq/tidb-faq.md - 3.1 branch](https://docs.pingcap.com/tidb/v3.1/tidb-faq)
[/faq/tidb-faq.md - 3.0 branch](https://docs.pingcap.com/tidb/v3.0/tidb-faq)
[/faq/tidb-faq.md - 2.1 branch](https://docs.pingcap.com/tidb/v2.1/tidb-faq)

Require change:

``` `sql\_mode` ``` -> ``` `sql_mode` ```

**Comment by andrefpoliveira** [comment]
Is this still a thing? I can't find ````sql\_mode``

**Comment by yikeke** [comment]
> Is this still a thing? I can't find `sql\_mode`

Must've been resolved by PRs I did not notice. Thanks for reporting it. I'll close this issue.
