### ISSUE TITLE
GIS Support

### ISSUE THREAD

**Issue by yangjun** [pingcap/docs#372]
类似 PostGIS 或者 MySQL 5.7，支持空间引擎，支持 osgeo 标准

**Comment by shenli** [comment]
GIS is on the roadmap. Please keep eye on the tidb repo.

**Comment by morgo** [comment]
This is being tracked in the TiDB issue queue as https://github.com/pingcap/tidb/issues/6347

To reduce duplication, I am going to close this issue. Thank you for your feature request!
