### ISSUE TITLE
Improve documentation of tidb_general_log

### ISSUE THREAD

**Issue by kolbe** [pingcap/docs#3720]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

TiDB has a "general query log", the purpose of which is to log every statement executed by an individual TiDB server instance. This log is toggled by the `tidb_general_log` variable.

The only description of the behavior is at https://docs.pingcap.com/tidb/stable/system-variables/#tidb_general_log where it's noted "This variable is used to set whether to record all the SQL statements in the log". It's also noted that this variable has "Scope: SERVER".

2. Describe your suggestion or addition.

   1. We should describe the usage of the tidb_general_log variable. It should be obvious who can set it and when, and it should be clear where the log entries are written.

   2. The meaning of "Scope: SERVER" is not explained anywhere. Apparently this means that the variable is a "session" variable, even though it affects the whole server instance. It's not possible to set it globally (because in TiDB a global variable affects all tidb-server instances)... but if you set it as a session variable it actually affects the whole server instance immediately. This behavior must be explained somewhere.

3. Provide some reference materials (documents, websites, etc) if you could.

```
mysql> set global tidb_general_log=1;
ERROR 1105 (HY000): Variable 'tidb_general_log' is a SESSION variable and can't be used with SET GLOBAL

mysql> set session tidb_general_log=1;
Query OK, 0 rows affected (0.00 sec)
```

**Comment by TomShawn** [comment]
@zz-jason PTAL, thanks!

**Comment by TomShawn** [comment]
The docs-cn PR is https://github.com/pingcap/docs-cn/pull/4843

**Comment by kolbe** [comment]
We should not automatically close issues without addressing them.

**Comment by lilin90** [comment]
Hi @kolbe, since @XuHuaiyu & @TomShawn had updated the description about `tidb_general_log` in both English and Chinese documentation (https://github.com/pingcap/docs-cn/pull/4843 and https://github.com/pingcap/docs/pull/4378), @TomShawn didn't freeze this issue to prevent it from being auto-closed.

Do you have further update suggestions? If yes, you can directly file a PR or tell @XuHuaiyu and request him to update it. Thanks!

**Comment by kolbe** [comment]
Fixed by https://github.com/pingcap/docs/pull/4378
