### ISSUE TITLE
last_plan_from_binding documented but not merged

### ISSUE THREAD

**Issue by nullnotnil** [pingcap/docs#3998]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

See: https://docs.pingcap.com/tidb/stable/system-variables#last_plan_from_binding-new-in-v40

2. How would you like to improve it?

This references a feature which has not merged yet: https://github.com/pingcap/tidb/pull/18017 -- if it doesn't merge, it should be removed from the docs to reduce confusion (it confused me!)

**Comment by TomShawn** [comment]
@nullnotnil Can this issue be closed now?

**Comment by nullnotnil** [comment]
Yes

**Comment by nullnotnil** [comment]
Actually, I double checked the PR. It is in master branch only. I think because of the high rate of conflicts, it won't immediately be cherry picked. We should remove the docs about this for the `stable` docs.
