### ISSUE TITLE
text/blob types' maximum lengths are wrong

### ISSUE THREAD

**Issue by cyliu0** [pingcap/docs#4014]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
https://docs.pingcap.com/tidb/stable/data-type-string#longblob-type

> The MEDIUMBLOB type is similar to the BLOB type. The difference is that the maximum column length of MEDIUMBLOB is 16,777,215.
> The LONGBLOB type is similar to the BLOB type. The difference is that the maximum column length of LONGBLOB is 4,294,967,295.

2. How would you like to improve it?
According to the [TiDB Limitations](https://docs.pingcap.com/tidb/stable/tidb-limitations#limitation-on-a-single-row), The limitation of size on a single column/row is 6MB. But the maximum lengths of medium/long text/blob are over 6MB a lot which are 16MB and 4GB.

**Comment by TomShawn** [comment]
@wjhuang2016 Please help take a look,thanks!

**Comment by morgo** [comment]
This also relates to https://github.com/pingcap/docs/issues/4390 (There is no actual storage size details on this page)

**Comment by TomShawn** [comment]
Looks like this document (https://docs.pingcap.com/tidb/dev/data-type-string) needs technical correction and more information for users.
