### ISSUE TITLE
Document supported SQL syntax

### ISSUE THREAD

**Issue by F21** [pingcap/docs#43]
While the [roadmap](https://github.com/pingcap/tidb/blob/master/docs/ROADMAP.md) contains a list of things the SQL layer supports, it is very brief.

For example, it is unclear to what extent simple subqueries are supported. It would be nice if there was a dedicated document documenting all the supported SQL constructs and syntax.

**Comment by shenli** [comment]
@F21 Thanks for your report! We will add a document for this.

**Comment by tiancaiamao** [comment]
Here is a tool you may also interested @F21 
https://github.com/pingcap/tidb-tools/tree/master/checker

**Comment by queenypingcap** [comment]
@shenli Since you have added the [TiDB SQL Grammar](https://pingcap.github.io/sqlgram), can we close this issue?

**Comment by c4pt0r** [comment]
@F21 As Queeny mentioned above, we also have a diagram of full SQL grammar that TiDB supports. See: [sqlgram](https://pingcap.github.io/sqlgram)

**Comment by F21** [comment]
@c4pt0r and @queenypingcap Thanks! That's perfect 😄

**Comment by shenli** [comment]
@F21 We will add an index for the sqlgram soon.
