### ISSUE TITLE
Confusing in `tidb_ddl_reorg_priority`

### ISSUE THREAD

**Issue by wenfengwang** [pingcap/docs#4394]
When I type `SET GLOBAL tidb_ddl_reorg_priority=PRIORITY_HIGH;` in MySQL console, and got:
![image](https://user-images.githubusercontent.com/9766821/101983943-18f11080-3cb9-11eb-962b-ebe939d1a09f.png)

but in docs: https://docs.pingcap.com/zh/tidb/stable/system-variables#tidb_ddl_reorg_priority, the global is ok:
![image](https://user-images.githubusercontent.com/9766821/101983968-5190ea00-3cb9-11eb-8765-6eed2ef2d818.png)

what's the problem?

cluster version: `v4.0.8`

**Comment by TomShawn** [comment]
@AilinKid Please help take a look, thanks!

**Comment by AilinKid** [comment]
Seems it's a mistake with the doc cause the code is `ScopeSession` indeed and it is unchanged for 2 years.

**Comment by TomShawn** [comment]
> Seems it's a mistake with the doc cause the code is `ScopeSession` indeed and it is unchanged for 2 years.

Shall we update the doc? (remove `GLOBAL`)
