### ISSUE TITLE
Incomplete search results on official website

### ISSUE THREAD

**Issue by binaryjerry** [pingcap/docs#4397]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

Incomplete search results on official website

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by CharLotteiu** [comment]
Thanks for your feedback! Could you please provide more information about which word did you search and what's your expected search result? That can help us locate the problem more quickly. 😄

**Comment by TomShawn** [comment]
@binaryjerry Any update?
