### ISSUE TITLE
Arm support 

### ISSUE THREAD

**Issue by lavvy** [pingcap/docs#44]
Hello are there arm docker images or binaries for pd, tikv and tidb. Atleast for entry or test environment for raspberry pi community

**Comment by c4pt0r** [comment]
Currently we don't support ARM platform officially, because there's no available 64bit OS image for Raspberry Pi right now. You have to do lots of patches on tikv and its dependent libraries, for example:
https://github.com/c4pt0r/rust-rocksdb/commit/b3105ac8d4c7cb286e2d572d5b9e1824983fe9c5

**Comment by shenli** [comment]
@lavvy There is no plan for Arm supporting. So I will close this issue.
