### ISSUE TITLE
sql views manual page does not render

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#4475]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/tidb/dev/views

2. How would you like to improve it?

It currently does not render in `dev`:

![image](https://user-images.githubusercontent.com/57982/102916157-55063d00-4440-11eb-86e8-2962bdc4ecfa.png)

**Comment by ran-huang** [comment]
@YiniXu9506 PTAL, thanks!

**Comment by ran-huang** [comment]
Thank you for the feedback! The page is fixed now.
