### ISSUE TITLE
update the method count in the warning

### ISSUE THREAD

**Issue by Glight29** [pingcap/docs#4496]
File: [/quick-start-with-tidb.md](https://docs.pingcap.com/tidb/stable/quick-start-with-tidb)

The warning on this page mentions that "For production environments, do not deploy TiDB with the following three methods.", but this page only provides two methods, not three.  Suggest removing the word ''three" from the warning.

**Comment by ran-huang** [comment]
Thanks for the feedback! Good catch.
We used to provide three methods on that page but recently removed one, and I forgot to update that warning 😸
