### ISSUE TITLE
Do we need to move build_rocksdb.sh to TiKV project ?

### ISSUE THREAD

**Issue by ngaut** [pingcap/docs#45]
Looks like it's a better place to host build_rocksdb.sh, since the TiKV project needs rocksdb.

**Comment by siddontang** [comment]
Most of the time, we must build TiDB, TiKV, PD and run them together, so it is better that putting all build instructions in one repository. 
I think adding reference in TiKV readme is ok. 
/cc @shenli

**Comment by siddontang** [comment]
now we build rocksdb statically, so no need build script anymore and has already been removed.
