### ISSUE TITLE
Incorrect server.snap-max-write-bytes-per-sec default value

### ISSUE THREAD

**Issue by andylokandy** [pingcap/docs#4510]
### What is the URL/path of the document related to this issue?

In docs/tikv-configuration-file.md:  default value of `server.snap-max-write-bytes-per-sec` should be `100MB`.

This affects 3.0, 3.1, 4.0, 5.0. 

3.0 and 3.1 should be fine since they are fixed in these PRs: 

- https://github.com/pingcap/docs/pull/4387
- https://github.com/pingcap/docs/pull/4386

**Comment by andylokandy** [comment]
@TomShawn @ran-huang This issue should not be closed.

**Comment by TomShawn** [comment]
This issue is fixed in https://github.com/pingcap/docs/pull/4597/files#diff-5e0b63d087f45ab3370aeb3f520d8d1f637a6f031fb6b9f294b4addc227e24c5R101.
