### ISSUE TITLE
Ansible recommendation is really confusing

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#4529]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/tidb/dev/production-deployment-using-tiup

2. How would you like to improve it?

This note is really confusing:
> Since TiDB v4.0, PingCAP no longer provides support for TiDB Ansible. Since TiDB v5.0, PingCAP no longer provides TiDB Ansible documents. If you want to read the document that introduces how to deploy a TiDB cluster using TiDB Ansible, see Deploy TiDB Using TiDB Ansible.

To start with, I clicked on the page for the documentation for TiUP and not ansible. It then says it's removed from documents but provides a link to the document for TiDB 4.0.

May I recommend something clearer such as:

> TiUP is the recommended upgrade path for users of TiDB Ansible. Support for Ansible was deprecated in TiDB v4.0, and removed starting with TiDB v5.0.

If they switch to the v4.0 docs, they will see the pages with deprecation links. There is no reason to link to them from the dev version of the docs.

**Comment by TomShawn** [comment]
This is because we have removed all Ansible docs from dev and 5.0 branches. The deleted Ansible doc link will be redirected to this TiUP doc. Suppose that some users kept the Ansible doc link and now **expect to see the Ansible doc NOT TiUP doc**. The link to v4.0 at least **gives them a choice to see what they want** and also provides recommendation for TiUP.

**Comment by morgo** [comment]
It's confusing because:
- It doesn't explain the context of why there is a warning about Ansible. Some users might not even know what Ansible is, but the wording makes it sound like they may need to understand. It would be more helpful to explain "TiUP is the recommended upgrade path for users of TiDB Ansible".
- It's not obvious when you follow the link you are switching to the v4.0 docs. I think from context of stating it was deprecated in v4.0 users know they can switch to the v4.0 manual to find more. As 5.0 is released, this will effectively suggest downgrading to use a deprecated technology, which is not a good idea.

This is why I suggested the following, which is shorter:
> TiUP is the recommended upgrade path for users of TiDB Ansible. Support for Ansible was deprecated in TiDB v4.0, and removed starting with TiDB v5.0.

**Comment by TomShawn** [comment]
@scsldb @kissmydb What do you think?

**Comment by kolbe** [comment]
I agree that linking to a deprecated version of the documentation is confusing.

If the problem here is related to a confusing/abrupt redirection, remove the redirection or have it point to something that is less confusing. Including totally irrelevant notes/warnings on documentation pages that refer to something different the item being described is a bad practice.

**Comment by TomShawn** [comment]
@King-Dylan PTAL

**Comment by alex-quan-001** [comment]
I suggest a direct pull request, rather than an issue, TiUP's or doc's  owner in charge needs to review and follow up on the subsequent changes.

**Comment by morgo** [comment]
> I suggest a direct pull request, rather than an issue, TiUP's or doc's owner in charge needs to review and follow up on the subsequent changes.

I will chat to you about it on Slack. While I can, not everyone can sign the contributor agreement. I really hope that's not the answer we give out to people who report issues.

**Comment by lilin90** [comment]
I talked with @morgo. Currently, let's guide users to the recommended deployment method. And for those who want to use the v4.0 TiDB Ansible deployment doc, they can find it via the version switcher. @TomShawn Would you please help file a PR to update https://docs.pingcap.com/tidb/dev/production-deployment-using-tiup? Thanks!

**Comment by TomShawn** [comment]
> I talked with @morgo. Currently, let's guide users to the recommended deployment method. And for those who want to use the v4.0 TiDB Ansible deployment doc, they can find it via the version switcher. @TomShawn Would you please help file a PR to update https://docs.pingcap.com/tidb/dev/production-deployment-using-tiup? Thanks!

Sure, I will.

**Comment by TomShawn** [comment]
@morgo @lilin90 PTAL
https://github.com/pingcap/docs/pull/4946
https://github.com/pingcap/docs/pull/4947

**Comment by TomShawn** [comment]
@morgo Docs updated, shall we close this issue?
