### ISSUE TITLE
new system variables are not documented in alphabetical order

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#4532]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/tidb/dev/system-variables#tidb_opt_prefer_range_scan

2. How would you like to improve it?

Chronological order of when options were added is not useful to users (especially when such a long list). The options in this page are alphabetical up until this variable on: https://docs.pingcap.com/tidb/dev/system-variables#tidb_opt_prefer_range_scan

**Comment by TomShawn** [comment]
Addressed in #4589.
