### ISSUE TITLE
lightning should not be recommended over BR for backup

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#4550]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/tidb/dev/backup-and-restore-using-dumpling-lightning

2. How would you like to improve it?

See the menu on the left hand side. I think it is fine to keep lightning under this section, but both BR and Dumpling have (recommended). This is a legacy from the earlier docs where mydumper etc were present.

I think it makes sense to just drop "(recommended)" from dumpling/lightning, since it is an import/export tool and not a backup tool. The restore times will be much longer.

**Comment by TomShawn** [comment]
@kennytm @overvenus PTAL, thanks~

**Comment by kennytm** [comment]
LGTM
