### ISSUE TITLE
lightning supports s3 parameters

### ISSUE THREAD

**Issue by cyliu0** [pingcap/docs#4555]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
We need to link the document which describe the supported s3 parameters in br such as endpoint and force_path_style from the lightning/dumpling document

2. Describe your suggestion or addition.
Add some descriptions

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by TomShawn** [comment]
@kennytm @overvenus PTAL, thanks

**Comment by kennytm** [comment]
@cyliu0 https://docs.pingcap.com/tidb/stable/backup-and-restore-storages#s3-parameters ?

**Comment by cyliu0** [comment]
> @cyliu0 https://docs.pingcap.com/tidb/stable/backup-and-restore-storages#s3-parameters ? This applies to BR & Lightning & Dumpling & everything else.

Yeah, we all know. But the document is for customers. I think we should have a link to this one with some simple information in the usage document for each tool (lightning, dumpling and etc.) at least.

**Comment by kennytm** [comment]
So the real issue is "we didn't link to this file from Lightning" rather than "We don't have the document to describe these".

**Comment by TomShawn** [comment]
@kennytm Would you help update the doc and add the link? Thanks

**Comment by ran-huang** [comment]
Fixed in https://github.com/pingcap/docs-cn/pull/5528
