### ISSUE TITLE
mydumper note is misleading and inaccurate

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#4606]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/tidb/dev/ecosystem-tool-user-guide

2. How would you like to improve it?

mydumper is an independent project. It is the PingCAP fork of mydumper which is no longer maintained. The note should be the same as [this one](https://github.com/pingcap/docs/pull/4538/files#diff-64a768071ffaa211a85a574132a639cc580eb6cdb5d7b03b47eefdf800c79e05R9-R11):

> PingCAP previously maintained a fork of the [mydumper project](https://github.com/maxbube/mydumper) with enhancements specific to TiDB. This fork has since been replaced by [Dumpling](/dumpling-overview.md), which has been rewritten in Go, and supports more optimizations that are specific to TiDB. It is strongly recommended that you use Dumpling instead of mydumper.

**Comment by CharLotteiu** [comment]
@overvenus PTAL. Thanks!
