### ISSUE TITLE
Creating a doc to show how to run a test app on TiDB

### ISSUE THREAD

**Issue by queenypingcap** [pingcap/docs#47]
You can use MySQL drivers/clients and applications, such as MySQL cli , PhpMyAdmin, WordPress, etc. to work with TiDB. This request is create an article to show how to run a test app on TiDB.

**Comment by c4pt0r** [comment]
@shenli  PTAL

**Comment by taoeffect** [comment]
So TiDB, right now, works with Wordpress? If so I would love to try it out!

Maybe a sample Docker app with Alpine linux could be used as the "documentation" / example?

**Comment by shenli** [comment]
There are already some tutorials now. So I will close this issue.
