### ISSUE TITLE
Dead url link about tikb hibernate region

### ISSUE THREAD

**Issue by yuqi1129** [pingcap/docs#4735]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
   https://docs.pingcap.com/zh/tidb/stable/massive-regions-best-practices#%E6%96%B9%E6%B3%95%E5%9B%9B%E5%BC%80%E5%90%AF-hibernate-region-%E5%8A%9F%E8%83%BD

  then click "TiKV Hibernate Region" and the result is:
  
![image](https://user-images.githubusercontent.com/15794564/105990936-26821e80-60de-11eb-89f5-4770136143f6.png)
  

2. How would you like to improve it?

Link to the correct page

**Comment by ran-huang** [comment]
Oh, thank you for your feedback! The page you're looking for is [here](https://docs.pingcap.com/zh/tidb/stable/tikv-configuration-file#raftstorehibernate-regions-%E5%AE%9E%E9%AA%8C%E7%89%B9%E6%80%A7).
Sorry for the inconvenience! We'll update the link soon.


@Joyinqin Could you please update both Chinese and English docs? Thanks.

**Comment by ran-huang** [comment]
I just saw your pull request. Thank you for the fix 😸😸😸
