### ISSUE TITLE
How to recover root user's privilege after some improper operation by mistake？

### ISSUE THREAD

**Issue by siuu** [pingcap/docs#475]
The misuse removed the user root@'%', and the user root@'127.0.0.1' was created without giving any permission.
After tidb is restarted with skip-grant-table=true, the root user still does not have any permissions.

./tidb-server -V
Release Version:  v2.0.0
Git Commit Hash:  637e130e6a9ba2e54e158131c0466233db39a60e
Git Commit Branch:  release-2.0
UTC Build Time:  2018-04-27 11:43:00
GoVersion:  go version go1.10 linux/amd64
TiKV Min Version:  2.0.0-rc.4.1

**Comment by tiancaiamao** [comment]
You can use grant https://pingcap.com/docs/sql/privilege/

The SQL grammar is the same with MySQL:

```
grant all privileges on *.* to 'root'@'%';
```

**Comment by tiancaiamao** [comment]
You need to operation on a special TiDB:

```
./tidb-server -config config.toml.example
```

--skip-grant-table is removed from command line (the document maybe outdated, I'm not sure), 
so you have to use a config file, modify here:

```
[security]
skip-grant-table = true

# Path of file that contains list of trusted SSL CAs for connection with mysql client.
ssl-ca = ""
# Path of file that contains X509 certificate in PEM format for connection with mysql client.
ssl-cert = ""
# Path of file that contains X509 key in PEM format for connection with mysql client.
ssl-key = ""
# Path of file that contains list of trusted SSL CAs for connection with cluster components.
cluster-ssl-ca = ""
# Path of file that contains X509 certificate in PEM format for connection with cluster components.
cluster-ssl-cert = ""
# Path of file that contains X509 key in PEM format for connection with cluster components.
cluster-ssl-key = ""
```


https://github.com/pingcap/tidb/blob/master/config/config.toml.example

And if you're using TiKV, don't forget to specify path to something like "127.0.0.0:2379", otherwise you just modify a TiDB on the local store.

**Comment by siuu** [comment]
Thank you very much, the problem has been solved
