### ISSUE TITLE
IP typo for minimal deployment topology : Monitoring & Grafana

### ISSUE THREAD

**Issue by ghz-max** [pingcap/docs#4760]
File: [/minimal-deployment-topology.md](https://docs.pingcap.com/tidb/dev/minimal-deployment-topology)

The node : Monitoring & Grafana has the IP 10.0.1.11 in the webpage whereas in the .yaml (both complex and simple), the IP is 10.0.1.10.

**Comment by TomShawn** [comment]
@superlzs0476 Please help confirm which one is correct, thanks!
