### ISSUE TITLE
start with fatal error

### ISSUE THREAD

**Issue by huangxueliang1980** [pingcap/docs#477]
TASK [set_fact] *******************************************************************************************************************************************************
fatal: [192.168.0.111]: FAILED! => {"msg": "The conditional check '((existing_api_keys['json'] | selectattr(\"name\", \"equalto\", \"grafana_apikey\")) | list) | length == 1' failed. The error was: no test named 'equalto'\n\nThe error appears to have been in '/opt/tidb-ansible/create_grafana_api_keys.yml': line 21, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}
        to retry, use: --limit @/opt/tidb-ansible/start.retry

**Comment by LinuxGit** [comment]
You need to install Ansible and its dependencies by pip, see https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md#step-4-install-ansible-and-its-dependencies-on-the-control-machine.
