### ISSUE TITLE
Use sentence case in graphics

### ISSUE THREAD

**Issue by ran-huang** [pingcap/docs#4770]
File: [/tidb-architecture.md](https://docs.pingcap.com/tidb/dev/tidb-architecture)

The graphic labels should be in sentence case:

`Data Location` -> `Data location`
`TiDB Cluster` -> `TiDB cluster`
![image](https://user-images.githubusercontent.com/59654584/106438300-4c7a3b00-64b1-11eb-8dde-d95e70551028.png)

**Comment by ran-huang** [comment]
@TomShawn PTAL

**Comment by TomShawn** [comment]
Thanks for feedback. I'll fix it soon.
