### ISSUE TITLE
br backup example is invalid

### ISSUE THREAD

**Issue by cosven** [pingcap/docs#4798]
## Error Report

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/zh/tidb/dev/use-br-command-line-tool#br-%E5%91%BD%E4%BB%A4%E8%A1%8C%E6%8F%8F%E8%BF%B0

2. How would you like to improve it?

The docs has an example
```sh
br backup full \
    --pd "${PDIP}:2379" \
    --storage "s3://${Bucket}/${Folder}" \
    --s3.region "${region}" \
    --send-credentials-to-tikv true
```

I try to run the example and it  fails with following error
```
~/q/t/cron backup-cron* > br backup db --s3.endpoint http://xxx --db test_cosven --pd 127.0.0.1:2379 --storage s3://user-cosven/backups/test --send-credentials-to-tikv true

Error: unknown command "true" for "br backup db"
[2021/02/04 10:51:24.834 +00:00] [ERROR] [main.go:59] ["br failed"] [error="unknown command \"true\" for \"br backup db\""] [stack="main.main\n\tgithub.com/pingcap/br@/main.go:59\nruntime.main\n\truntime/proc.go:203"]
```

**Comment by TomShawn** [comment]
@overvenus @3pointer PTAL, thanks!
