### ISSUE TITLE
correct miswriting

### ISSUE THREAD

**Issue by BanYeung** [pingcap/docs#4812]
File: [/optimistic-transaction.md](https://docs.pingcap.com/tidb/stable/optimistic-transaction)

Principles of optimistic transactions
5
 iv. TiDB **receives** all requests in the prewrite phase and the prewrite is successful.
       
SHOULD BE:
TiDB **sends** all requests in the prewrite phase and the prewrite is successful.

**Comment by TomShawn** [comment]
@BanYeung Thanks for feedback!
@cfzjywxk PTAL, thanks!

**Comment by cfzjywxk** [comment]
@BanYeung Thanks for feedback.
Here should be:
`TiDB receives all ok responses in the prewrite phase and the prewrite is successful`
