### ISSUE TITLE
Missing parameter "readpool.unifiy-read-pool" definition

### ISSUE THREAD

**Issue by XiaoGe2030** [pingcap/docs#4950]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
  https://docs.pingcap.com/tidb/stable/benchmark-sysbench-v4-vs-v3

2. How would you like to improve it?
  In TiDB Sysbench Performance Test Report -- v4.0 vs. v3.0 ,use " readpool.unifiy-read pool" parameter .  But  " readpool.unifiy-read pool "parameter definition not found in https://docs.pingcap.com/tidb/stable/tikv-configuration-file.

**Comment by TomShawn** [comment]
@sticnarf Would you please help add `readpool.unifiy-read pool` in the [TiKV Configuration File | PingCAP Docs](https://docs.pingcap.com/tidb/dev/tikv-configuration-file)? Thanks!

**Comment by sticnarf** [comment]
> @sticnarf Would you please help add `readpool.unifiy-read pool` in the [TiKV Configuration File | PingCAP Docs](https://docs.pingcap.com/tidb/dev/tikv-configuration-file)? Thanks!

This parameter does not exist indeed. If the test was really done with this configuration, the `readpool.unifiy-read-pool` setting should be removed.
