### ISSUE TITLE
Diagramming tool suggestion

### ISSUE THREAD

**Issue by tjyang** [pingcap/docs#507]
Hi There
I noticed that the TiDB's architecture diagram are using google's diagramming tool.
Is it possible that TiDB diagrammig tool can be switched over to open-source [Dia tool](http://dia-installer.de/)? 
Doing so will allow others to download the .dia source and modify/enhance/reuse diagrams easily.

**Comment by tjyang** [comment]
@Hoverbear , I can re-create a few TiDB arch diagram using Dia, if there is an interest.

**Comment by Hoverbear** [comment]
Hi @tjyang (I thought I responded to this, sorry!)

Using diagramming format that can be more easily edited is a great idea. Do you know if Dia files can be previewed on Github? Or embedded? If not we might need to have some sort of push hook to generate the images on change.

I think SVG may also be an option, but it's not very convenient to edit. I have previously used http://asciiflow.com/ and appreciate the simplicity of the output.

**Comment by Hoverbear** [comment]
Hmm that's a bit annoying. I think it is an upgrade over what we currently. @queenypingcap could you PTAL, what do you think?

**Comment by tjyang** [comment]
@Hoverbear 
Can you elaborate why you feel "a bit annonying" ? 
All drawing tools using  special formats that not can be displayed  directly from github/gitlab.  Usually export to png/jpeg/pdf are the required step and save the viewable format to git repo.

**Comment by Hoverbear** [comment]
@tjyang Yeah I was thinking about it compared to GraphViz which has a really plain representation. Unfortunately GraphViz isn't easy to use. :(

**Comment by tjyang** [comment]
@Hoverbear 
I am proposing using Dia over Google draw as this project's diagramming tool , not GraphViz. 
Please [install Dia](http://dia-installer.de/download/index.html.en) on your machine to try it out. and open [GNU autotool example .dia file](https://github.com/tjyang/psp/blob/master/books/psp/dia/autotool.dia) to try out.

**Comment by Hoverbear** [comment]
@tjyang Yes, I know that. :) I was more thinking that GraphViz might be more appropriate, but I think Dia is easier for folks to use.

**Comment by queenypingcap** [comment]
Thank you for the suggestion, @tjyang. For now, we are more inclined to keep the format as it is. We can try it later to see if this works for us!
