### ISSUE TITLE
Document Replication under MySQL Compatibility

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#5137]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

See: https://docs.pingcap.com/tidb/stable/mysql-compatibility

There is no mention of MySQL replication.

2. Describe your suggestion or addition.

There should be some pointers to DM and Binlog to explain that TiDB does not implement replication in a strictly MySQL compatible way. i.e.
- There is no `CHANGE REPLICATION SOURCE`/`CHANGE MASTER TO` statement (use DM)
- MySQL replicas can not connect directly to TiDB as a replication source.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by TomShawn** [comment]
@zz-jason @lance6716 @july2993 PTAL, thanks!

**Comment by TomShawn** [comment]
This issue has been addressed.
