### ISSUE TITLE
fio randread iops of  deploy_dir disk is too low

### ISSUE THREAD

**Issue by Lyle-liang** [pingcap/docs#520]
> ./fio -ioengine=libaio -bs=32k -direct=1 -thread -rw=randrw -percentage_random=100,0 -size=10G -filename=fio_randr_write_test.txt -name='PingCAP' -iodepth=4 -runtime=60

I meet a problem, as follows: 
![image](https://user-images.githubusercontent.com/14850448/42321953-23a03302-808d-11e8-8511-57ee9364db1b.png)
Ps: SSD  10TB

Question:

1. Why are the parameters of the command set like this?

2. How to solve it, and I don't want to skip the test by configuring？

Urgent！！！

Thanks.

**Comment by LinuxGit** [comment]
It's recommended to use NVMe SSD disks for the data directory of TiKV and PD nodes. 
Most of TiKV's disk requests are randread and sequential write.  AND the baseline of fio iops result is Intel SATA3 SSD.
