### ISSUE TITLE
Binary tarball documents

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#5226]
## Error Report

1. What is the URL/path of the document related to this issue?

- https://docs.pingcap.com/tidb/v5.0/test-deployment-from-binary-tarball
- https://docs.pingcap.com/tidb/v5.0/deploy-tidb-from-binary
- https://docs.pingcap.com/tidb/v5.0/get-started-with-tidb-binlog

2. How would you like to improve it?

There are two documents about deploying TiDB from a binary tarball. However I believe that using TiUP is now the recommended way instead of using binaries. Also the two documents only seem to be linked from the TiDB Binlog getting started docs and nowhere else.These documents also show up when searching.

I would suggest to either:

- Remove the two documents and update the reference in the TiDB Binlog document
OR
- Add links in the "Deploy" section etc.

**Comment by morgo** [comment]
I agree with removing if it is not supported.

/cc @qiancai @yikeke

**Comment by qiancai** [comment]
Agree with @morgo. 

To avoid similar issues in the future, perhaps we could consider adding one more check item in the CI check: if a file is removed from the TOC, all the references to this file in the repo should be reported and prompted to be removed or updated as well.

**Comment by morgo** [comment]
> To avoid similar issues in the future, perhaps we could consider adding one more check item in the CI check: if a file is removed from the TOC, all the references to this file in the repo should be reported and prompted to be removed or updated as well.

This might be hard to differentiate from the other case: which is as documents are added they may initially not be in the TOC. This is a useful feature for splitting up large additions into smaller PRs for reviewing.

**Comment by TomShawn** [comment]
> Agree with @morgo.
> 
> To avoid similar issues in the future, perhaps we could consider adding one more check item in the CI check: if a file is removed from the TOC, all the references to this file in the repo should be reported and prompted to be removed or updated as well.

Some docs are intentionally not added to TOC but retained in the repo. Users can access these docs only via exact addresses and cannot find the entry in the left navigation menu. This can be helpful when these docs are no longer recommended but might still be needed by some users. If we need to make a doc offline, removing it from TOC can be a good first step.

**Comment by yikeke** [comment]
Agree to remove the two binary deployment docs from the repo. 

We removed the two docs from TOC since v4.0, now with v5.0 GA, it's good to move to the next step - remove the source files from the repository and redirect them to the TiUP deployment doc. @TomShawn 

Also, https://docs.pingcap.com/tidb/v5.0/get-started-with-tidb-binlog needs updates accordingly.
