### ISSUE TITLE
TiKV_GC_can_not_work refers to wrong rule

### ISSUE THREAD

**Issue by kolbe** [pingcap/docs#5269]
File: [/alert-rules.md](https://docs.pingcap.com/tidb/stable/alert-rules)

TiKV_GC_can_not_work references this rule:
```
sum(increase(tidb_tikvclient_gc_action_result{type="success"}[6h])) < 1
```

This seems to be the correct rule:
```
sum(increase(tikv_gcworker_gc_tasks_vec{task="gc"}[1d])) < 1
```

https://github.com/pingcap/monitoring/blob/master/monitor-snapshot/master/operator/rules/tikv.rules.yml#L18

**Comment by kolbe** [comment]
Oops, no, it's actually at https://github.com/tikv/tikv/blob/master/metrics/alertmanager/tikv.rules.yml#L17 ...

```
    expr: sum(increase(tikv_gcworker_gc_tasks_vec{task="gc"}[1d])) < 1 and sum(increase(tikv_gc_compaction_filter_perform[1d])) < 1
```

**Comment by kolbe** [comment]
https://github.com/tikv/tikv/pull/9914 and/or https://github.com/tikv/tikv/issues/9910 should've requested a documentation update.

**Comment by TomShawn** [comment]
/assign @hicqu @MyonKeminta 
@hicqu @MyonKeminta PTAL, thanks

**Comment by TomShawn** [comment]
@kolbe The docs PR is https://github.com/pingcap/docs/pull/5320. PTAL and see if your issue is addressed.

**Comment by yikeke** [comment]
#5320 has been approved and merged.
