### ISSUE TITLE
Correct miswriting:release5.0.0/tidb_enable_clustered_index

### ISSUE THREAD

**Issue by tzkoba** [pingcap/docs#5307]
File: [/releases/release-5.0.0.md](https://docs.pingcap.com/tidb/stable/release-5.0.0)

- Change the default value of tidb_enable_clustered_index from OFF to INT_ONLY with the following new meanings:

> - OFF: clustered index is **enabled**. Adding or deleting non-clustered indexes is supported.
> - ON: clustered index is **disabled**. Adding or deleting non-clustered indexes is supported.
> - INT_ONLY: the default value. The behavior is consistent with that before v5.0. You can control whether to enable clustered index for the INT type together with alter-primary-key = false.

SHOULD BE:
- Change the default value of tidb_enable_clustered_index from OFF to INT_ONLY with the following new meanings:

> - OFF: clustered index is **disabled**. Adding or deleting non-clustered indexes is supported.
> - ON: clustered index is **enabled**. Adding or deleting non-clustered indexes is supported.
> - INT_ONLY: the default value. The behavior is consistent with that before v5.0. You can control whether to enable clustered index for the INT type together with alter-primary-key = false.

It's the opposite.

**Comment by ran-huang** [comment]
Thank you for the feedback! Sharp eyes.
Do you mind opening a PR to fix this? 😸

**Comment by tzkoba** [comment]
OK. I'll try.

**Comment by tzkoba** [comment]
Already proposed in #5306
