### ISSUE TITLE
remove log printing

### ISSUE THREAD

**Issue by carr123** [pingcap/docs#540]
when i create a tikv client with  tikv.NewRawKVClient( ). 
it automatically prints on console the following logs:

time="2018-07-12T14:06:38+08:00" level=info msg="[pd] create pd client with endpoints [175.16.1.50:2379 175.16.1.53:2379 175.16.1.54:2379]" 
time="2018-07-12T14:06:38+08:00" level=info msg="[pd] leader switches to: http://175.16.1.50:2379, previous: " 
time="2018-07-12T14:06:38+08:00" level=info msg="[pd] init cluster id 8576091382420269395"

how can i switch off those logs printing ? 

thanks.

**Comment by disksing** [comment]
Hi @carr123 , we use logrus(https://github.com/sirupsen/logrus) for logging. You may want set a higher log level or set a different output using logrus's API.

**Comment by carr123** [comment]
where can i invoke  logrus's API ?  should i need to change tikv project's source code ?

**Comment by disksing** [comment]
No. Source code of tikv only controls the log of tikv-server.
