### ISSUE TITLE
no server.request-batch-enable-cross-command in V5.0.0

### ISSUE THREAD

**Issue by dbsid** [pingcap/docs#5413]
File: [/benchmark/benchmark-sysbench-v5-vs-v4.md](https://docs.pingcap.com/tidb/stable/benchmark-sysbench-v5-vs-v4)

please remove below line from TiKV v5.0 configuration
```
server.request-batch-enable-cross-command: false

```
The parameter prevent the TiKV startup.
unknown configuration options: server.request-batch-enable-cross-command

**Comment by TomShawn** [comment]
updated in https://github.com/pingcap/docs/pull/5414

**Comment by TomShawn** [comment]
Related PRs: 

+ https://github.com/pingcap/docs-cn/pull/6108
+ https://github.com/pingcap/docs-cn/pull/6107
+ https://github.com/pingcap/docs/pull/5419
+ https://github.com/pingcap/docs/pull/5414
