### ISSUE TITLE
"split, redefine partitions by using ALTER TABLE statements" is incorrect

### ISSUE THREAD

**Issue by kolbe** [pingcap/docs#5424]
https://docs.pingcap.com/tidb/stable/partitioned-table#range-partition-management makes this statement:

> You can add, drop, merge, split, redefine partitions by using ALTER TABLE statements.

We do not currently support "split" or "redefine" partition operations, as far as I know and can tell by my testing.

File: [/partitioned-table.md](https://docs.pingcap.com/tidb/stable/partitioned-table)

**Comment by zz-jason** [comment]
@qw4990 we need to verify and correct the document related to [partition table](https://docs.pingcap.com/tidb/stable/partitioned-table)
