### ISSUE TITLE
References to Version 3 should be changed

### ISSUE THREAD

**Issue by ttadeo** [pingcap/docs#5457]
File: [/best-practices/pd-scheduling-best-practices.md](https://docs.pingcap.com/tidb/stable/pd-scheduling-best-practices)

Hot regions scheduling
For hot regions scheduling, use hot-region-scheduler. Currently in TiDB 3.0, the process is performed as follows:

Count hot regions by determining read/write traffic that exceeds a certain threshold for a certain period based on the information reported by stores.

Redistribute these regions in a similar way to load balancing.

For hot write regions, hot-region-scheduler attempts to redistribute both region peers and leaders; for hot read regions, hot-region-scheduler only redistributes region leaders.

**Comment by TomShawn** [comment]
@disksing Any plan to update this document? Looks like it's a bit outdated.
