### ISSUE TITLE
doc out of sync

### ISSUE THREAD

**Issue by tisonkun** [pingcap/docs#5631]
## Error Report

1. What is the URL/path of the document related to this issue?

https://github.com/pingcap/docs/blob/ac042040fcc9b03114e6ccfbdf04fddb885c3942/tidb-lightning/tidb-lightning-backends.md#L212

This line is updated by https://github.com/pingcap/docs-cn/pull/6284/files in `docs-cn` repo, while en version out of sync. I don't see a related issue yet.

2. How would you like to improve it?

Keep sync.

**Comment by TomShawn** [comment]
@tisonkun "sync" means translation. We do translate doc changes made in docs-cn to docs as timely as we can (we only have a few hands). [This](https://github.com/pingcap/docs-cn/pulls?q=is%3Apr+is%3Amerged+label%3Atranslation%2Fdoing+) is the list of PRs we are gonna translate. No docs-cn PR is gonna missing sync.

https://github.com/pingcap/docs-cn/pull/6284 was merged less than 23 hours ago. If this PR is really urgent for translation or merge, please let me know in Lark. Thanks!

**Comment by tisonkun** [comment]
Thanks for your explanation and I'm sorry for the burden.
