### ISSUE TITLE
WithCopy ending up in docs without proper rendering

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#5633]
## Error Report

![image](https://user-images.githubusercontent.com/1272980/118522612-8c9dba80-b73c-11eb-9ef7-df9bbb1f38fe.png)

1. What is the URL/path of the document related to this issue?

- https://docs.pingcap.com/tidb/stable/certificate-authentication#get-user-certificate-information
- https://docs.pingcap.com/tidb/stable/enable-tls-between-components

2. How would you like to improve it?

- Fix these specific issues
- Check https://www.google.com/search?q=site%3Adocs.pingcap.com+WithCopy for other issues
- Setup CI to check for similar issues to avoid these from being added again later

**Comment by TomShawn** [comment]
@dveeden In the GitHub docs or docs-cn repo, there are no such "WithCopy" characters. It's a webpage parsing error caused by the incorrect indentation in the markdown files. Now, this issue has been addressed. PTAL.

**Comment by dveeden** [comment]
Looks like that did the trick. Thanks.
