### ISSUE TITLE
go version check problem

### ISSUE THREAD

**Issue by chux0519** [pingcap/docs#566]
[scripts/check_requirement.sh](https://github.com/pingcap/docs/blob/master/scripts/check_requirement.sh#L96) seems not correctly check the go version( GO_VER_2 ).

on OSX
go version: 1.10.3

> go version | awk 'match($0, /([0-9])+(\.[0-9])+/) { ver = substr($0, RSTART, RLENGTH); split(ver, n, "."); print n[2];}'

output: 1

**Comment by queenypingcap** [comment]
Thanks for your issue report, @chux0519! Please try the new script.
