### ISSUE TITLE
VITESS_HASH function documentation

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#5718]
## Error Report

https://docs.pingcap.com/tidb/stable/release-5.0.1 has this:

- Support the built-in function VITESS_HASH() [#23915](https://github.com/pingcap/tidb/pull/23915)

However I can't find this function in the function documentation. I would suggest to add a section for "Compatibility Functions" and add it there. It should be documented that this function is not compatible with MySQL as MySQL doesn't have this.

**Comment by TomShawn** [comment]
@winoros Could you help add doc for `VITESS_HASH()`? Thanks!

**Comment by XuHuaiyu** [comment]
Hi, @morgo 
Can you help to add this doc?
