### ISSUE TITLE
max-replicas documentation needs to be extended

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#5866]
The `replication.max-replicas` documentation on https://docs.pingcap.com/tidb/stable/pd-configuration-file#max-replicas should be extended with:

- A more complete description about what this option does
- If and how this can be changed online
- Why one might want to change this setting

A link to a document that explains this would also be sufficient.

**Comment by disksing** [comment]
Thanks for your suggestion. I'll improve it.

**Comment by TomShawn** [comment]
@dveeden [This PR](https://github.com/pingcap/docs-cn/pull/6669) add these content, PTAL: "The total count of replicas, that is, the sum of leader count and follower count. The default value is `3`, which is 1 leader and 2 followers. When this configuration is modified online, PD will perform background scheduling to make the number of replicas match this configuration."
