### ISSUE TITLE
Differences in defaults between TiDB and MySQL 5.7

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#590]
Is it possible to create a manual page (or alternatively append to [this manual page](https://github.com/pingcap/docs/blob/master/sql/mysql-compatibility.md)) differences in defaults between TiDB and MySQL?  My short list:

* TiDB defaults to `utf8` (MySQL 5.7 is latin1 - this changes in 8.0 to utf8).
* TiDB defaults and only supports `lower_case_table_names=2`.
* TiDB's default collation is binary.

**Comment by lilin90** [comment]
Related content is added to docs in this PR: https://github.com/pingcap/docs/pull/591
