### ISSUE TITLE
TiCDC config templates should includes data-dir, gc-ttl and other important configs 

### ISSUE THREAD

**Issue by overvenus** [pingcap/docs#5962]
https://github.com/pingcap/docs/blob/95770385fb34e4172695d9ecd2b6621051a1ff32/config-templates/complex-cdc.yaml#L43-L46

We should add data-dir, gc-ttl and other important configs in the above file.

**Comment by shichun-0415** [comment]
@overvenus It seems we have such configs in https://github.com/pingcap/docs/blob/master/config-templates/complex-cdc.yaml#L95-L116
![image](https://user-images.githubusercontent.com/89768198/222090391-296fa09e-3a64-4b91-9c2f-2da9b93e5739.png)
