### ISSUE TITLE
op-guide: Add tabs style to Kubernetes

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#597]
On [the kubernetes deploy page](https://pingcap.com/docs/op-guide/kubernetes/), is it possible to have the platforms appear as tabs? (similar to macOS and Linux [on this page](https://www.pingcap.com/blog/how_to_spin_up_an_htap_database_in_5_minutes_with_tidb_tispark/)).

The goal is that in future other k8s platforms will be introduced (eks etc.)  It should also be possible to directly link to the tab being selected.

(In future maybe the ansible online/offline guide could be modified to one page with tabs too.)

**Comment by queenypingcap** [comment]
@YiniXu9506 Could you please take a look? Thanks!

**Comment by YiniXu9506** [comment]
@queenypingcap Yes, I have talked to Morgan, and am planning to develop it.

**Comment by morgo** [comment]
FIxed in https://github.com/pingcap/docs/pull/717 , thx @YiniXu9506 !
