### ISSUE TITLE
Backup & Restore FAQ conflicts with BR Tool Overview for what schemas are backed up by default

### ISSUE THREAD

**Issue by BarDev** [pingcap/docs#6056]
It seems the FAQ needs to be updated.

File: [/br/backup-and-restore-faq.md v5.1.0](https://docs.pingcap.com/tidb/stable/backup-and-restore-faq#does-br-back-up-system-tables-during-data-restoration-do-they-raise-conflict) 

The following is mentioned in the FAQ
> The system schemas (information_schema, performance_schema, mysql) are ***filtered out*** during full backup. 

in (BR Tool Overview - Backup and restore system schemas - v5.1.0)https://docs.pingcap.com/tidb/stable/backup-and-restore-tool#backup-and-restore-system-schemas]

>Before v5.1.0, BR filtered out data from the system schemas during the backup.
>
>Since v5.1.0, ***BR backups all data by default***, including the system schema (mysql.*)

**Comment by shichun-0415** [comment]
@BarDev Thank you for your feedback. The BR doc has been updated. About the backup and restore of system tables, the new doc pages are as follows:
https://docs.pingcap.com/tidb/stable/br-snapshot-guide#restore-tables-in-the-mysql-schema
https://docs.pingcap.com/tidb/dev/backup-and-restore-faq#why-are-tables-in-the-mysql-schema-not-restored
It seems there is no contradictory description any more.
