### ISSUE TITLE
Broken links on Credits page

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#6193]
## Error Report

https://docs.pingcap.com/tidb/stable/credits

From `/usr/local/bin/markdown-link-check`:
```
ERROR: 4 dead links found!
[✖] https://github.com/tikv/community/tree/master/sig/transaction → Status: 404
[✖] https://github.com/pingcap/community/tree/master/special-interest-groups/sig-scheduling → Status: 404
[✖] https://github.com/pingcap/community/tree/master/special-interest-groups/sig-dashboard → Status: 404
[✖] https://github.com/pingcap/community/tree/master/special-interest-groups/sig-ddl → Status: 404
```

**Comment by tisonkun** [comment]
Thanks for reporting this issue @dveeden ! I think as we merge SIGs, there will be several links broken.

@lilin90 @qiancai I'd like to know whether these links populated manually or automatically, so that we know how to fix the problem.

**Comment by TomShawn** [comment]
@tisonkun These links are manually populated. We plan to synchronize [this page] with the [Chinese version](https://docs.pingcap.com/zh/tidb/stable/credits) which does not contain the reported broken links. The PR is in https://github.com/pingcap/docs/pull/6111.

We do have an external broken link checker built into the CircleCI but it does not work very well.

**Comment by tisonkun** [comment]
@TomShawn thanks for your update, you can refer the issue from PR (I did it for you).

For the testing part, I'd suggest you make use of GitHub Actions to perform the tests as we may no longer maintain CircleCI pipelines.
