### ISSUE TITLE
separate query statement and result in two text boxes

### ISSUE THREAD

**Issue by Defined2014** [pingcap/docs#6204]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
https://docs.pingcap.com/tidb/dev/basic-sql-operations#query-data
![image](https://user-images.githubusercontent.com/17435596/130314640-1d32e7d7-6543-4606-a8f8-6023d8efada7.png)

It will copy sql statement and result when click the button.

2. How would you like to improve it?
Separate sql statement and result in two text boxes.

**Comment by TomShawn** [comment]
Thanks very much!
