### ISSUE TITLE
dbForge 7.2.58 can not connect to TiDB

### ISSUE THREAD

**Issue by pmzxlpyt** [pingcap/docs#625]
![image](https://user-images.githubusercontent.com/43162966/46055449-98e53b80-c17e-11e8-884e-e74469f5315d.png)

**Comment by CaitinChen** [comment]
Original title: dbForge 7.2.58 客户端工具无法连接到 Tidb吗

**Comment by winkyao** [comment]
Seems like TiDB doesn't have the `performance_schema.session_variables `, it may be a compatibility problem. We will look into this later. thanks for your feedback.

**Comment by winkyao** [comment]
Could you use the other client, such as Navicat? We will fix this issue later.

**Comment by winkyao** [comment]
Could you use the other client, such as Navicat? We will fix this issue later.

**Comment by pmzxlpyt** [comment]
Navicat is not very convenient to create a procedure @winkyao

**Comment by XuHuaiyu** [comment]
hi, @pmzxlpyt 
Could you please try to build a tidb-server binary file 
with [this commit](https://github.com/pingcap/tidb/pull/7788) and try it again to see whether we can 
connect to the client?

**Comment by shenli** [comment]
@XuHuaiyu Could you provide a binary for @pmzxlpyt?

**Comment by jackysp** [comment]
@XuHuaiyu , I think it may not fix this issue, because MySQL will still provide the data of session_variables when performance_schema is OFF.

**Comment by XuHuaiyu** [comment]
[tidb-server.zip](https://github.com/pingcap/docs/files/2423454/tidb-server.zip)

**Comment by yikeke** [comment]
Hi @pmzxlpyt , did your issue get resolved? 

Because this issue is too old, I'll close it within 7 days if there is no new comment.

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
