### ISSUE TITLE
Does TiDB support stored procedure and event task scheduling?

### ISSUE THREAD

**Issue by pmzxlpyt** [pingcap/docs#626]
Tidb 支持存储过程，支持事件任务调度吗

**Comment by CaitinChen** [comment]
Original title: Tidb 支持存储过程，支持事件任务调度吗

**Comment by lysu** [comment]
Hi @pmzxlpyt, TiDB doesn't support procedure and event task schedule now

https://pingcap.com/docs/sql/mysql-compatibility/
