### ISSUE TITLE
Download location for Spark

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#6417]
## Error Report

https://docs.pingcap.com/tidb/stable/tispark-overview links to https://spark.apache.org/downloads.html to download Spark.

However the version indicated in that document (2.3.x) is no longer available on that page.

https://archive.apache.org/dist/spark/ is probably the right location until we support Spark 3.x

**Comment by dveeden** [comment]
cc @Joyinqin

**Comment by shichun-0415** [comment]
@dveeden Looks like we can close this issue because the latest doc no longer mentions any downloding link for Spark.
