### ISSUE TITLE
TiSpark documentation improvements

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#6454]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.

The TiSpark documentation is unclear at some points

2. Describe your suggestion or addition.

- `spark-sql` is briefly mentioned but it's use isn't explained and no information is provided about how to start it.
- `beeline` & Thrift Server are mentioned in the docs. But no information is included about this being part of the spark download and how to start the thrift server.
- On CentOS 7 (and likely all other platforms) firwalld needs to be disabled for the guide to work
- Using `./sbin/start-slave.sh spark://127.0.0.1:7077` won't work as the Spark master doesn't listen on loopback. As users might deploy the master and worker/slave  together for testing this can cause issues. Solution: use `./sbin/start-slave.sh spark://$(hostname):7077` instead.
- One place mentions the CDH version of hadoop, which is a bit confusing (maybe move this to a note?)
- For the `spark-defaults.conf` config: the PD config *must* include a port number.  (replace `$your_pd_servers` with `$pd_server:$pd_port` to make this easier to spot?)
- "For the Standalone mode without Hadoop support, use Spark 2.3.x and any version of Pre-build with Apache Hadoop 2.x with Hadoop dependencies" -- This is confusing. Maybe list an example filename of the download to make it more explicit that if you don't want Hadoop support you do need to download the version with hadoop dependencies.
- The docs talk about `spark-defaults.conf`, but that file doesn't exist by default as one needs to copy it from `conf/spark-defaults.conf.template` to `conf/spark-defaults.conf`
- As TiSpark doesn't use the access control that TiDB has users should be made aware of the security implications of running TiSpark.

3. Provide some reference materials (documents, websites, etc) if you could.

Related #6417

**Comment by TomShawn** [comment]
@marsishandsome Could you please take a look to see what we can do now according to @dveeden's suggestion? Thanks!

**Comment by dveeden** [comment]
https://docs.pingcap.com/tidb/stable/tispark-deployment-topology doesn't seem to be references from the other two documents that talk about TiSpark.

Might be good to explain when to use TiSpark and when to use TiFlash.

**Comment by dveeden** [comment]
The `tispark-sample-data.tar.gz` looks like tpch data. Shouldn't this use `tiup bench tpch...` instead?

**Comment by shichun-0415** [comment]
@dveeden Seems we can close this issue now, right?

**Comment by dveeden** [comment]
@shichun-0415 yes
