### ISSUE TITLE
FAQ "The order of results is different from MySQL when ORDER BY is omitted" is out of date

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#6533]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

See: https://docs.pingcap.com/tidb/stable/sql-faq#the-order-of-results-is-different-from-mysql-when-order-by-is-omitted

2. How would you like to improve it?

It should mention `tidb_enable_ordered_result_mode` which is also currently not documented in sysvars.md

/cc @qw4990

**Comment by TomShawn** [comment]
@morgo addressed in https://github.com/pingcap/docs/pull/11265. PTAL
