### ISSUE TITLE
FAQ "How to scatter the hotspots?" is out of date

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#6534]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.

See: https://docs.pingcap.com/tidb/stable/sql-faq#how-to-scatter-the-hotspots

2. Describe your suggestion or addition.

There are multiple strategies besides `SHARD_ROW_ID_BITS`. For example: `AUTO_RANDOM` and Non-clustered indexes.

It would honestly be helpful if there was an FAQ section just on hotspots.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by TomShawn** [comment]
@morgo Recently, [this FAQ](https://docs.pingcap.com/tidb/stable/sql-faq#how-to-avoid-hotspot-issues-and-achieve-load-balancing-is-hot-partition-or-range-an-issue-in-tidb) has been added. PTAL whether it addresses your issue.

**Comment by morgo** [comment]
Yes, but I would remove the FAQ in favor of the new one. The old faq suggests one of the four strategies - the new FAQ lists the four. Actually there is a fifth: cached tables should be suggested for some cases.

**Comment by TomShawn** [comment]
> Yes, but I would remove the FAQ in favor of the new one. The old faq suggests one of the four strategies - the new FAQ lists the four. Actually there is a fifth: cached tables should be suggested for some cases.

@morgo addressed in https://github.com/pingcap/docs/pull/11265. PTAL
