### ISSUE TITLE
FAQ "How to safely stop TiDB?" should mention graceful-wait-before-shutdown

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#6535]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.

https://docs.pingcap.com/tidb/stable/deploy-and-maintain-faq#how-to-safely-stop-tidb

2. Describe your suggestion or addition.

Assuming the user is using a load balancer (recommended), then a "safe" shutdown involves removing from the load balancer before killing so that active sessions are not killed. There is a configuration setting called `graceful-wait-before-shutdown` for exactly this purpose.

3. Provide some reference materials (documents, websites, etc) if you could.

Because load balancing is an important topic, it should link to https://github.com/pingcap/docs/pull/5555/files once merged.

**Comment by shichun-0415** [comment]
The document has been refactored and the new doc link is [Cluster Management FAQs | PingCAP Docs](https://docs.pingcap.com/tidb/stable/manage-cluster-faq#how-to-safely-stop-tidb)
https://docs.pingcap.com/tidb/stable/manage-cluster-faq#how-to-safely-stop-tidb.

**Comment by easonn7** [comment]
Does this mean that we recommend customers to use Load Balancer, but for users who are not using Load Balancer, the behavior of stopping the cluster remains the same？

**Comment by morgo** [comment]
Yes to both.
