### ISSUE TITLE
FAQ "Can kill be executed in TiDB?" is out of date

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#6536]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

See: https://docs.pingcap.com/tidb/stable/deploy-and-maintain-faq#can-kill-be-executed-in-tidb

2. Describe your suggestion or addition.

The answer is not really helpful. `KILL` can be used, but is disabled by default because of the case that you could be using a load balancer and killing the wrong connection.

This can be changed by either enabling `compatible-kill-query = true`, or enabling global kill (experimental).

3. Provide some reference materials (documents, websites, etc) if you could.

It would also be helpful to link to the kill statement reference which mentions this: https://docs.pingcap.com/tidb/stable/sql-statement-kill

**Comment by shichun-0415** [comment]
The document has been refactored and the new doc link is [Cluster Management FAQs | PingCAP Docs](https://docs.pingcap.com/tidb/stable/manage-cluster-faq#can-kill-be-executed-in-tidb)
https://docs.pingcap.com/tidb/stable/manage-cluster-faq#can-kill-be-executed-in-tidb
