### ISSUE TITLE
FAQ "Does TiDB support session timeout?" is out of date/wrong

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#6537]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

https://docs.pingcap.com/tidb/stable/deploy-and-maintain-faq#can-kill-be-executed-in-tidb

2. Describe your suggestion or addition.

This is not correct, TiDB supports both `wait_timeout` and `interactive_timeout`.

3. Provide some reference materials (documents, websites, etc) if you could.

https://docs.pingcap.com/tidb/stable/system-variables#wait_timeout

**Comment by shichun-0415** [comment]
The document has been refactored and the new doc link is [Cluster Management FAQs | PingCAP Docs](https://docs.pingcap.com/tidb/stable/manage-cluster-faq#does-tidb-support-session-timeout)
https://docs.pingcap.com/tidb/stable/manage-cluster-faq#does-tidb-support-session-timeout.
