### ISSUE TITLE
FAQ "Is there a graphical deployment tool for TiDB?" could be improved

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#6538]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

See: https://docs.pingcap.com/tidb/stable/deploy-and-maintain-faq#can-kill-be-executed-in-tidb

2. Describe your suggestion or addition.

While the answer is true (there is no GUI _deployer_), I think at the time this question was written there was no GUI management tool either. It would be helpful to clarify that the recommended installers are TiUP, operator and for simplicity TiDB Cloud.

For managing, there is the TiDB Dashboard GUI.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by shichun-0415** [comment]
@morgo Thanks for your feedback and sorry for the late reply. We are now developing a graphical database operation and maintenance management platform TiDB Enterprise Manager (TiEM) for TiDB. It is expected to open source next month and we will provide the user doc link of TiEM to this question.
