### ISSUE TITLE
FAQ "How to modify the user password and privilege?" uses non-recommended technique

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#6539]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

https://docs.pingcap.com/tidb/stable/high-reliability-faq#how-to-modify-the-user-password-and-privilege

2. Describe your suggestion or addition.

It is recommended to use `ALTER USER` now and not `SET password`, since you can set the authentication plugin at the same time. This will make it easier for users to use stronger mechanisms in future (the default password is sha1 based)

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by TomShawn** [comment]
@morgo Can we close this issue now?
