### ISSUE TITLE
Add partitioning documentation

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#662]
Ideas:

- Add to mysql compatibility page (only range partitioning supported)
- Add to user-guide
- Add to optimizer somewhere (partition pruning)

**Comment by lilin90** [comment]
The partitioning doc had been added in https://github.com/pingcap/docs/pull/1300, so I'll close this issue. You can also [view this doc on the PingCAP website](https://pingcap.com/docs/stable/reference/sql/partitioning/).
