### ISSUE TITLE
Missing information for table locking

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#6831]
## Error Report

- The `enable-table-lock` config option for TiDB is not documented.
- `LOCK TABLE` and `UNLOCK TABLES` is missing from SQL statement documentation

https://github.com/pingcap/tidb/blob/56ba37a1ca0d959367c8031a0182815fd81034e4/config/config.toml.example#L80-L81

```
mysql> \W
Show warnings enabled.
mysql> CREATE TABLE t1 (id int primary key);
Query OK, 0 rows affected (0.01 sec)

mysql> LOCK TABLE t1 WRITE;
Query OK, 0 rows affected, 1 warning (0.00 sec)

Warning (Code 1235): LOCK TABLES is not supported. To enable this experimental feature, set 'enable-table-lock' in the configuration file.
mysql> UNLOCK TABLE;
Query OK, 0 rows affected, 1 warning (0.00 sec)

Warning (Code 1235): UNLOCK TABLES is not supported. To enable this experimental feature, set 'enable-table-lock' in the configuration file.
```

This option seems to be in TiDB at least since v4.0

**Comment by TomShawn** [comment]
@dveeden Hello, as confirmed with @tangenta and @crazycs520, the table locking feature was particularly developed for TiSpark, but with some bugs. Therefore, the developer still does not want to expose this feature to users. That's why there's no documentation for it.

**Comment by dveeden** [comment]
> @dveeden Hello, as confirmed with @tangenta and @crazycs520, the table locking feature was particularly developed for TiSpark, but with some bugs. Therefore, the developer still does not want to expose it to users. That's why there's no documentation for it.

I think it then should be documented as an experimental option, something like "`enable-table-lock`: experimental feature for table locking, not recommended for production".

**Comment by dveeden** [comment]
Maybe we should also mark this as experimental in the sample config in that case:
```patch
diff --git a/config/config.toml.example b/config/config.toml.example
index e23f390e2..b10a59bfc 100644
--- a/config/config.toml.example
+++ b/config/config.toml.example
@@ -62,6 +62,7 @@ max-index-length = 3072
 index-limit = 64
 
 # enable-table-lock is used to control table lock feature. Default is false, indicate the table lock feature is disabled.
+# This is an experimental feature, not recommended for production.
 enable-table-lock = false
 
 # delay-clean-table-lock is used to control the time (Milliseconds) of delay before unlock the table in the abnormal situation.
```

There is an `experimental` section in the config, but this isn't part of it:
```
$ egrep -A3 '^\[experimental\]' config/config.toml.example 
[experimental]
# enable creating expression index.
allow-expression-index = false

```
@tangenta, @crazycs520 should we modify the sample config?
