### ISSUE TITLE
`tidb_enable_alter_placement` was not added in system_variables page

### ISSUE THREAD

**Issue by aytrack** [pingcap/docs#6844]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
since `tidb_enable_alter_placement ` was introduced by support plancement rule in sql , but it's not 
 add in system_variables page 

2. Describe your suggestion or addition.
add `tidb_enable_alter_placement` variables in page.
3. Provide some reference materials (documents, websites, etc) if you could.
https://github.com/pingcap/docs/blob/master/placement-rules-in-sql.md?plain=1#L10

**Comment by morgo** [comment]
This is a system variable that is pre-existing, and follows our previous procedure of not documenting experimental features.

But our [new procedure](https://github.com/pingcap/tidb/blob/master/docs/design/2021-07-29-hidden-sysvars.md) is to document them. So I will create a PR for this.
