### ISSUE TITLE
Wrong tikv-ctl command in garbage-collection-configuration.md

### ISSUE THREAD

**Issue by ekexium** [pingcap/docs#6867]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://github.com/pingcap/docs/blob/b818cb598a079c1d1377f4e853ab96aa33bdcf94/garbage-collection-configuration.md?plain=1#L28

2. How would you like to improve it?
```
./tikv-ctl --host=127.0.0.1:20160 modify-tikv-config -m server -n gc.max_write_bytes_per_sec -v 10MB
```
```
error: Found argument '-m' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-ctl modify-tikv-config -n <config_name> -v <config_value>

For more information try --help
```

It seems to me the `-m server` part shouldn't be there.

**Comment by BusyJay** [comment]
@youjiali1995 any thoughts? It's seems to be written by you.

**Comment by youjiali1995** [comment]
It works in v3.x https://github.com/tikv/tikv/pull/5769. I guess online config change since v4.0 changes it.

**Comment by en-jin19** [comment]
@BusyJay @youjiali1995  Thanks for your comments!

@youjiali1995 could you please update the command in the TiDB user document "garbage-collection-configuration.md" and add the cherry pick labels on PRs?

**Comment by NingLin-P** [comment]
https://github.com/pingcap/docs-cn/pull/7772 will fix this issue.

**Comment by en-jin19** [comment]
Hi, @ekexium, since the [PR #7772](https://github.com/pingcap/docs-cn/pull/7772) fixed this issue, we will close this issue today. Thank you for your feedback on PingCAP documents!
