### ISSUE TITLE
sql: Document EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#690]
EXPLAIN ANALYZE is great! 

We should amend the example here to show an example with analyze:
[./sql/understanding-the-query-execution-plan.md#example-usage](https://github.com/pingcap/docs/blob/master/sql/understanding-the-query-execution-plan.md#example-usage)

**Comment by morgo** [comment]
@lysu what do you think - should it star with an example on the EXPLAIN page, or have a separate page?

Also, do you mind providing an explanation of `execution_info`:
- time
- loops
- rows

**Comment by lysu** [comment]
Hi @morgo, IMO maybe more suitable in EXPLAIN page, it's just a optional for analyze :laughing: 

- time: means total execution time of those executor, from "enter executor" to "exit executor", it contains the time of its sub-executor and it will sum up all executor call if those executor be call multple times from parent.
- loops: display the count of executor-call from parent executor.
- rows: give total rows returned by this executor.
