### ISSUE TITLE
Add bug severity in release note

### ISSUE THREAD

**Issue by zgcbj** [pingcap/docs#7033]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
TiDB release many versions every year.  Our online clusters cannot follow every version，but we don’t want to miss important bug fixes either.

2. Describe your suggestion or addition.
Add bug serverity in release note
3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by morgo** [comment]
Thank you for the suggestion! Would it be okay to instead suggest that critical bugs be clearly labeled?

(The severity of bugs can change in score. But the most important piece seems to be identifying critical issues.)

**Comment by zgcbj** [comment]
> Thank you for the suggestion! Would it be okay to instead suggest that critical bugs be clearly labeled?
> 
> (The severity of bugs can change in score. But the most important piece seems to be identifying critical issues.)

Thanks for your reply, this is a great solution！

**Comment by shichun-0415** [comment]
@zgcbj Thanks for your feedback, all bug fixes in our release notes link to their GitHub issues, through which you can check the bug severity and get more information.
![image](https://user-images.githubusercontent.com/89768198/216278841-e6d40467-fb9f-4f80-a59c-af7f627bbb53.png)
![image](https://user-images.githubusercontent.com/89768198/216278919-32adbff6-1b2d-4c81-a7a6-b015222655c4.png)
