### ISSUE TITLE
undocumented uuid functions

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#7079]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/tidb/stable/miscellaneous-functions

2. How would you like to improve it?

The functions introduced in https://github.com/pingcap/tidb/pull/20140 are not documented.

**Comment by dveeden** [comment]
Looks like a duplicate of https://github.com/pingcap/docs/issues/5920

**Comment by morgo** [comment]
Agree. Closing this one!
