### ISSUE TITLE
`INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS` does not work in v5.2

### ISSUE THREAD

**Issue by zhangyangyu** [pingcap/docs#7084]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/zh/tidb/v5.2/information-schema-referential-constraints

2. How would you like to improve it?

According to discussion in https://github.com/pingcap/tidb/issues/30291, `INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS` table functionality was added to v5.3, not v5.2 in https://github.com/pingcap/tidb/pull/26450.

**Comment by qiancai** [comment]
Hi @zhangyangyu, thanks for the feedback. I've updated the doc in https://github.com/pingcap/docs/pull/7513. PTAL. Thanks.

**Comment by qiancai** [comment]
Both English and Chinese PRs are merged.
