### ISSUE TITLE
lack `tidb_enable_change_multi_schema` doc

### ISSUE THREAD

**Issue by zhangyangyu** [pingcap/docs#7093]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

Variable `tidb_enable_change_multi_schema` is added in https://github.com/pingcap/tidb/pull/21533 but no doc could be found.

1. What is the URL/path of the document related to this issue?

2. How would you like to improve it?

**Comment by shichun-0415** [comment]
@Arenatlx, PTAL. Thanks.

**Comment by AilinKid** [comment]
this variable is not visible to users.

under the control of this var the error should be like: Unsupported multi schema change (cause this feature hasn't been GA yet)

**Comment by shichun-0415** [comment]
@zhangyangyu Shall we close this issue? Or do you have any further suggestions on this issue?
