### ISSUE TITLE
"ulimit -n" related error

### ISSUE THREAD

**Issue by pmzxlpyt** [pingcap/docs#712]
TASK [check_system_dynamic : Preflight check - ulimit -n] *************************************************************************************************************************************************************
fatal: [192.168.117.231]: FAILED! => {"changed": false, "msg": "The default maximum number of open file descriptors is too low 4096, should be 1000000"}

NO MORE HOSTS LEFT ****************************************************************************************************************************************************************************************************
	to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/deploy.retry

PLAY RECAP ************************************************************************************************************************************************************************************************************
192.168.117.231            : ok=5    changed=0    unreachable=0    failed=1   

how can I fix it? thx

**Comment by Connor1996** [comment]
The reason is `The default maximum number of open file descriptors is too low 4096, should be 1000000`. You can use `ulimit -n 1000000` to set

**Comment by Connor1996** [comment]
just run `sudo ulimit -n 1000000` in your command-line

**Comment by pmzxlpyt** [comment]
when i close the check  session "check_system_dynamic" in deploy.ini file ,it is ok now. but i think it is not a good idea

**Comment by Connor1996** [comment]
yeah, it is not a good idea

**Comment by pmzxlpyt** [comment]
@Connor1996  thx

**Comment by lilin90** [comment]
@Connor1996 Thanks for your quick response :)
