### ISSUE TITLE
add PD node 

### ISSUE THREAD

**Issue by pmzxlpyt** [pingcap/docs#716]
following 【https://pingcap.com/docs-cn/op-guide/ansible-deployment-scale/】 to add PD node ,it isn't available 

![image](https://user-images.githubusercontent.com/43162966/48180205-8b19fd00-e35d-11e8-8107-919e64b322dc.png)

error:
/home/tidb/tidb-ansible/resources/bin/pd-ctl -u "http://117.168.117.244:2379" -d member
Failed to get pd members: Get http://117.168.117.244:2379/pd/api/v1/members: dial tcp 117.168.117.244:2379: i/o timeout

**Comment by shenli** [comment]
What do you mean by "it isn't available"?
Have you checked if the PD cluster is running?

**Comment by pmzxlpyt** [comment]
@shenli  how can i check the PD clulster?
![image](https://user-images.githubusercontent.com/43162966/48182209-58740280-e365-11e8-9c2a-2c90a09db5c6.png)

**Comment by disksing** [comment]
Hi @pmzxlpyt , could you check the log of the new PD?

**Comment by disksing** [comment]
Also, please replace the IP in command to an old PD and run the `member` command to see the cluster status.

**Comment by pmzxlpyt** [comment]
yes , i replaced the IP as follow

#!/bin/bash
set -e
ulimit -n 1000000

# WARNING: This file was auto-generated. Do not edit!
#          All your edit might be overwritten!
DEPLOY_DIR=/home/tidb/deploy

cd "${DEPLOY_DIR}" || exit 1


exec bin/pd-server \
    --name="pd4" \
    --join="http://192.168.117.244:2379" \
    --advertise-client-urls="http://192.168.117.44:2379" \
    --peer-urls="http://192.168.117.44:2380" \
    --advertise-peer-urls="http://192.168.117.44:2380" \
    --data-dir="/home/tidb/deploy/data.pd" \
    --initial-cluster="pd1=http://192.168.117.243:2380,pd2=http://192.168.117.244:2380,pd3=http://192.168.117.245:2380,pd4=http://192.168.117.44:2380" \
    --config=conf/pd.toml \
    --log-file="/home/tidb/deploy/log/pd.log" 2>> "/home/tidb/deploy/log/pd_stderr.log"

**Comment by pmzxlpyt** [comment]
![image](https://user-images.githubusercontent.com/43162966/48182659-fddba600-e366-11e8-92be-f5626ab2db72.png)

**Comment by pmzxlpyt** [comment]
![image](https://user-images.githubusercontent.com/43162966/48182704-29f72700-e367-11e8-8cce-05565a1ee206.png)

**Comment by pmzxlpyt** [comment]
error msg:

github.com/pingcap/pd/server/config.go:276: \n/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/config.go:245: \n"
time="2018-11-08T14:56:27+08:00" level=fatal msg="parse cmd flags error: /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/config.go:250: -initial-cluster and -join can not be provided at the same time\n/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/config.go:276: \n/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/config.go:245: \n"
time="2018-11-08T14:56:42+08:00" level=fatal msg="parse cmd flags error: /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/config.go:250: -initial-cluster and -join can not be provided at the same time\n/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/config.go:276: \n/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/config.go:245: \n"

**Comment by disksing** [comment]
As the log says "-initial-cluster and -join can not be provided at the same ". I think you want to remove the `initial-clueter` line from the script. (It is also mentioned in the document)

**Comment by pmzxlpyt** [comment]
yes, It is also mentioned in the document.   so remove the initial-cluster line . why it doesn't work?

**Comment by pmzxlpyt** [comment]
Yes , I did it step by step as the document . why it doesn't work ?  @disksing

**Comment by pmzxlpyt** [comment]
it is working now 
![image](https://user-images.githubusercontent.com/43162966/48184202-4053b180-e36c-11e8-955a-164fb6e03401.png)

but the log-file=/home/tidb/deploy/log/pd.log  says "
2018/11/08 15:39:05.963 log.go:80: [error] rafthttp: [request sent was ignored (cluster ID mismatch: peer[138bca46ae09fa79]=da4e0e7733bc2114, local=8db684bda59786d5)]
2018/11/08 15:39:06.001 log.go:80: [error] rafthttp: [request sent was ignored (cluster ID mismatch: peer[c39d998ea0150513]=da4e0e7733bc2114, local=8db684bda59786d5)]
2018/11/08 15:39:06.001 log.go:80: [error] rafthttp: [request sent was ignored (cluster ID mismatch: peer[c39d998ea0150513]=da4e0e7733bc2114, local=8db684bda59786d5)]
"
![image](https://user-images.githubusercontent.com/43162966/48184301-8ad52e00-e36c-11e8-92dc-a4b0a5d00e8d.png)

**Comment by disksing** [comment]
This is because a new cluster was incorrectly initialized when the previous configuration was wrong. You can try to kill the PD process, delete the "/home/tidb/deploy/data.pd" directory, and restart the PD again.

**Comment by pmzxlpyt** [comment]
you are great !!! thx @disksing

**Comment by pmzxlpyt** [comment]
it is working now(  the pd =192.168.117.44) ,but in my monitor background  i can't get it as before.
![image](https://user-images.githubusercontent.com/43162966/48185726-e73a4c80-e370-11e8-828d-0d563c2f881b.png)

**Comment by pmzxlpyt** [comment]
And  

 [tidb@Center-ctl tidb-ansible]$ /home/tidb/tidb-ansible/resources/bin/pd-ctl -u http://117.168.117.244:2379
? member
Failed to get pd members: Get http://117.168.117.244:2379/pd/api/v1/members: dial tcp 117.168.117.244:2379: i/o timeout

**Comment by disksing** [comment]
em, it seems that this PD does not join successfully. Could you check log of the new PD again?

**Comment by pmzxlpyt** [comment]
2018/11/08 16:03:10.061 util.go:62: [info] Welcome to Placement Driver (PD).
2018/11/08 16:03:10.061 util.go:63: [info] Release Version: v2.0.5
2018/11/08 16:03:10.061 util.go:64: [info] Git Commit Hash: b64716707b7279a4ae822be767085ff17b5f3fea
2018/11/08 16:03:10.061 util.go:65: [info] Git Branch: release-2.0
2018/11/08 16:03:10.061 util.go:66: [info] UTC Build Time:  2018-10-16 09:33:41
2018/11/08 16:03:10.061 metricutil.go:87: [info] start Prometheus push client
2018/11/08 16:03:12.268 main.go:73: [fatal] join error etcdserver: unhealthy cluster
/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/pkg/etcdutil/etcdutil.go:82: 
/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/join.go:119: 
2018/11/08 16:03:27.378 util.go:62: [info] Welcome to Placement Driver (PD).
2018/11/08 16:03:27.379 util.go:63: [info] Release Version: v2.0.5
2018/11/08 16:03:27.379 util.go:64: [info] Git Commit Hash: b64716707b7279a4ae822be767085ff17b5f3fea
2018/11/08 16:03:27.379 util.go:65: [info] Git Branch: release-2.0
2018/11/08 16:03:27.379 util.go:66: [info] UTC Build Time:  2018-10-16 09:33:41
2018/11/08 16:03:27.379 metricutil.go:87: [info] start Prometheus push client
2018/11/08 16:03:27.421 server.go:96: [info] PD config - Config({FlagSet:0xc00019af60 Version:false ClientUrls:http://192.168.117.44:2379 PeerUrls:http://192.168.117.44:2380 AdvertiseClientUrls:http://192.168.117.44:2379 AdvertisePeerUrls:http://192.168.117.44:2380 Name
:pd4 DataDir:/home/tidb/deploy/data.pd InitialCluster:pd1=http://192.168.117.243:2380,pd4=http://192.168.117.44:2380,pd2=http://192.168.117.244:2380,pd3=http://192.168.117.245:2380 InitialClusterState:existing Join:http://192.168.117.244:2379 LeaderLease:3 Log:{Level:in
fo Format:text DisableTimestamp:false File:{Filename:/home/tidb/deploy/log/pd.log LogRotate:true MaxSize:300 MaxDays:0 MaxBackups:0}} LogFileDeprecated: LogLevelDeprecated: TsoSaveInterval:3s Metric:{PushJob:pd4 PushAddress:192.168.117.85:9091 PushInterval:15s} Schedule
:{MaxSnapshotCount:3 MaxPendingPeerCount:16 MaxMergeRegionSize:0 SplitMergeInterval:1h0m0s PatrolRegionInterval:100ms MaxStoreDownTime:30m0s LeaderScheduleLimit:4 RegionScheduleLimit:4 ReplicaScheduleLimit:8 MergeScheduleLimit:8 TolerantSizeRatio:5 LowSpaceRatio:0.8 Hig
hSpaceRatio:0.6 EnableRaftLearner:false Schedulers:[{Type:balance-region Args:[] Disable:false} {Type:balance-leader Args:[] Disable:false} {Type:hot-region Args:[] Disable:false} {Type:label Args:[] Disable:false}]} Replication:{MaxReplicas:3 LocationLabels:[host]} Nam
espace:map[] QuotaBackendBytes:0 AutoCompactionRetention:1 TickInterval:500ms ElectionInterval:3s Security:{CAPath: CertPath: KeyPath:} LabelProperty:map[] configFile:conf/pd.toml WarningMsgs:[] NamespaceClassifier:default nextRetryDelay:1000000000 disableStrictReconfig
Check:false heartbeatStreamBindInterval:{Duration:60000000000} leaderPriorityCheckInterval:{Duration:60000000000}})
2018/11/08 16:03:27.422 server.go:122: [info] start embed etcd
2018/11/08 16:03:27.422 log.go:86: [info] embed: [listening for peers on  http://192.168.117.44:2380]
2018/11/08 16:03:27.422 log.go:86: [info] embed: [pprof is enabled under /debug/pprof]
2018/11/08 16:03:27.422 log.go:86: [info] embed: [listening for client requests on  192.168.117.44:2379]
2018/11/08 16:03:27.423 systime_mon.go:24: [info] start system time monitor
2018/11/08 16:03:27.426 log.go:86: [info] etcdserver: [name = pd4]
2018/11/08 16:03:27.426 log.go:86: [info] etcdserver: [data dir = /home/tidb/deploy/data.pd]
2018/11/08 16:03:27.426 log.go:86: [info] etcdserver: [member dir = /home/tidb/deploy/data.pd/member]
2018/11/08 16:03:27.426 log.go:86: [info] etcdserver: [heartbeat = 500ms]
2018/11/08 16:03:27.426 log.go:86: [info] etcdserver: [election = 3000ms]
2018/11/08 16:03:27.426 log.go:86: [info] etcdserver: [snapshot count = 100000]
2018/11/08 16:03:27.426 log.go:86: [info] etcdserver: [advertise client URLs = http://192.168.117.44:2379]
2018/11/08 16:03:27.427 log.go:86: [info] etcdserver: [starting member 1cf6d089e2c11230 in cluster da4e0e7733bc2114]
2018/11/08 16:03:27.427 log.go:86: [info] raft: [1cf6d089e2c11230 became follower at term 0]
2018/11/08 16:03:27.427 log.go:86: [info] raft: [newRaft 1cf6d089e2c11230 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]]
2018/11/08 16:03:27.427 log.go:86: [info] raft: [1cf6d089e2c11230 became follower at term 1]
2018/11/08 16:03:27.430 log.go:82: [warning] auth: [simple token is not cryptographically signed]
2018/11/08 16:03:27.433 log.go:86: [info] rafthttp: [started HTTP pipelining with peer 138bca46ae09fa79]
2018/11/08 16:03:27.433 log.go:86: [info] rafthttp: [started HTTP pipelining with peer 4a58dc46a268c615]
2018/11/08 16:03:27.433 log.go:86: [info] rafthttp: [started HTTP pipelining with peer c39d998ea0150513]
2018/11/08 16:03:27.433 log.go:86: [info] rafthttp: [starting peer 138bca46ae09fa79...]
2018/11/08 16:03:27.433 log.go:86: [info] rafthttp: [started HTTP pipelining with peer 138bca46ae09fa79]
2018/11/08 16:03:27.435 log.go:86: [info] rafthttp: [started streaming with peer 138bca46ae09fa79 (writer)]
2018/11/08 16:03:27.435 log.go:86: [info] rafthttp: [started streaming with peer 138bca46ae09fa79 (writer)]
2018/11/08 16:03:27.435 log.go:86: [info] rafthttp: [started peer 138bca46ae09fa79]
2018/11/08 16:03:27.435 log.go:86: [info] rafthttp: [added peer 138bca46ae09fa79]
2018/11/08 16:03:27.435 log.go:86: [info] rafthttp: [starting peer 4a58dc46a268c615...]
2018/11/08 16:03:27.435 log.go:86: [info] rafthttp: [started HTTP pipelining with peer 4a58dc46a268c615]
2018/11/08 16:03:27.436 log.go:86: [info] rafthttp: [started peer 4a58dc46a268c615]
2018/11/08 16:03:27.436 log.go:86: [info] rafthttp: [added peer 4a58dc46a268c615]
2018/11/08 16:03:27.436 log.go:86: [info] rafthttp: [starting peer c39d998ea0150513...]
2018/11/08 16:03:27.436 log.go:86: [info] rafthttp: [started HTTP pipelining with peer c39d998ea0150513]
2018/11/08 16:03:27.437 log.go:86: [info] rafthttp: [started peer c39d998ea0150513]
2018/11/08 16:03:27.437 log.go:86: [info] rafthttp: [added peer c39d998ea0150513]
2018/11/08 16:03:27.437 log.go:86: [info] etcdserver: [starting server... [version: 3.2.18, cluster version: to_be_decided]]
2018/11/08 16:03:27.439 log.go:86: [info] rafthttp: [started streaming with peer 138bca46ae09fa79 (stream MsgApp v2 reader)]
2018/11/08 16:03:27.439 log.go:86: [info] rafthttp: [started streaming with peer 138bca46ae09fa79 (stream Message reader)]
2018/11/08 16:03:27.439 log.go:86: [info] rafthttp: [started streaming with peer 4a58dc46a268c615 (writer)]
2018/11/08 16:03:27.439 log.go:86: [info] rafthttp: [started streaming with peer 4a58dc46a268c615 (writer)]
2018/11/08 16:03:27.439 log.go:86: [info] rafthttp: [started streaming with peer 4a58dc46a268c615 (stream MsgApp v2 reader)]
2018/11/08 16:03:27.439 log.go:86: [info] rafthttp: [started streaming with peer 4a58dc46a268c615 (stream Message reader)]
2018/11/08 16:03:27.439 log.go:86: [info] rafthttp: [started streaming with peer c39d998ea0150513 (writer)]
2018/11/08 16:03:27.439 log.go:86: [info] rafthttp: [started streaming with peer c39d998ea0150513 (writer)]
2018/11/08 16:03:27.439 log.go:86: [info] rafthttp: [started streaming with peer c39d998ea0150513 (stream MsgApp v2 reader)]
2018/11/08 16:03:27.439 log.go:86: [info] rafthttp: [started streaming with peer c39d998ea0150513 (stream Message reader)]
2018/11/08 16:03:27.441 log.go:86: [info] rafthttp: [peer c39d998ea0150513 became active]
2018/11/08 16:03:27.441 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer c39d998ea0150513 (stream MsgApp v2 reader)]
2018/11/08 16:03:27.441 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer c39d998ea0150513 (stream Message reader)]
2018/11/08 16:03:27.442 log.go:86: [info] rafthttp: [peer 4a58dc46a268c615 became active]
2018/11/08 16:03:27.442 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer 4a58dc46a268c615 (stream MsgApp v2 reader)]
2018/11/08 16:03:27.442 log.go:86: [info] rafthttp: [peer 138bca46ae09fa79 became active]
2018/11/08 16:03:27.442 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer 138bca46ae09fa79 (stream Message reader)]
2018/11/08 16:03:27.443 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer 138bca46ae09fa79 (stream MsgApp v2 reader)]
2018/11/08 16:03:27.485 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer 138bca46ae09fa79 (stream MsgApp v2 writer)]
2018/11/08 16:03:27.485 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer 138bca46ae09fa79 (stream Message writer)]
2018/11/08 16:03:27.489 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer c39d998ea0150513 (stream Message writer)]
2018/11/08 16:03:27.489 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer c39d998ea0150513 (stream MsgApp v2 writer)]
2018/11/08 16:03:27.490 log.go:86: [info] etcdserver: [1cf6d089e2c11230 initialzed peer connection; fast-forwarding 4 ticks (election ticks 6) with 3 active peer(s)]
2018/11/08 16:03:27.493 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer 4a58dc46a268c615 (stream Message reader)]
2018/11/08 16:03:27.521 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer 4a58dc46a268c615 (stream Message writer)]
2018/11/08 16:03:27.521 log.go:86: [info] rafthttp: [established a TCP streaming connection with peer 4a58dc46a268c615 (stream MsgApp v2 writer)]
2018/11/08 16:03:27.752 log.go:86: [info] raft: [1cf6d089e2c11230 [term: 1] received a MsgHeartbeat message with higher term from 138bca46ae09fa79 [term: 54]]
2018/11/08 16:03:27.752 log.go:86: [info] raft: [1cf6d089e2c11230 became follower at term 54]
2018/11/08 16:03:27.752 log.go:86: [info] raft: [raft.node: 1cf6d089e2c11230 elected leader 138bca46ae09fa79 at term 54]
2018/11/08 16:03:27.771 log.go:86: [info] etcdserver/membership: [added member 138bca46ae09fa79 [http://192.168.117.243:2380] to cluster da4e0e7733bc2114]
2018/11/08 16:03:27.771 log.go:86: [info] etcdserver/membership: [added member 4a58dc46a268c615 [http://192.168.117.244:2380] to cluster da4e0e7733bc2114]
2018/11/08 16:03:27.771 log.go:86: [info] etcdserver/membership: [added member c39d998ea0150513 [http://192.168.117.245:2380] to cluster da4e0e7733bc2114]
2018/11/08 16:03:27.772 log.go:84: [info] etcdserver/membership: [set the initial cluster version to 3.2]
2018/11/08 16:03:27.772 log.go:86: [info] etcdserver/api: [enabled capabilities for version 3.2]
2018/11/08 16:03:27.796 log.go:86: [info] mvcc: [store.index: compact 1]
2018/11/08 16:03:27.809 log.go:86: [info] mvcc: [store.index: compact 1321]
2018/11/08 16:03:27.819 log.go:86: [info] mvcc: [finished scheduled compaction at 1 (took 11.021155ms)]
2018/11/08 16:03:27.821 log.go:86: [info] mvcc: [store.index: compact 2532]
2018/11/08 16:03:27.839 log.go:86: [info] mvcc: [store.index: compact 3725]
2018/11/08 16:03:27.840 log.go:86: [info] mvcc: [finished scheduled compaction at 1321 (took 20.74969ms)]
2018/11/08 16:03:27.841 log.go:86: [info] mvcc: [finished scheduled compaction at 2532 (took 1.699649ms)]
2018/11/08 16:03:27.842 log.go:86: [info] mvcc: [finished scheduled compaction at 3725 (took 1.06923ms)]
2018/11/08 16:03:27.871 log.go:86: [info] mvcc: [store.index: compact 4926]
2018/11/08 16:03:27.881 log.go:86: [info] mvcc: [store.index: compact 6127]
2018/11/08 16:03:27.897 log.go:86: [info] mvcc: [store.index: compact 7293]
2018/11/08 16:03:27.898 log.go:86: [info] mvcc: [finished scheduled compaction at 4926 (took 17.637773ms)]
2018/11/08 16:03:27.924 log.go:86: [info] mvcc: [finished scheduled compaction at 6127 (took 26.212157ms)]
2018/11/08 16:03:27.926 log.go:86: [info] mvcc: [finished scheduled compaction at 7293 (took 1.965079ms)]
2018/11/08 16:03:27.932 log.go:86: [info] etcdserver/membership: [added member 1cf6d089e2c11230 [http://192.168.117.44:2380] to cluster da4e0e7733bc2114]
2018/11/08 16:03:27.933 log.go:86: [info] etcdserver: [published {Name:pd4 ClientURLs:[http://192.168.117.44:2379]} to cluster da4e0e7733bc2114]
2018/11/08 16:03:27.933 log.go:86: [info] embed: [ready to serve client requests]
2018/11/08 16:03:27.933 log.go:84: [info] embed: [serving insecure client requests on 192.168.117.44:2379, this is strongly discouraged!]
2018/11/08 16:03:27.933 server.go:156: [info] create etcd v3 client with endpoints [http://192.168.117.44:2379]
2018/11/08 16:03:27.936 server.go:195: [info] init cluster id 6621033703978490577
2018/11/08 16:03:27.937 leader.go:95: [info] leader is name:"pd1" member_id:1408441713399822969 peer_urls:"http://192.168.117.243:2380" client_urls:"http://192.168.117.243:2379" , watch it

**Comment by pmzxlpyt** [comment]
there is not any error message

**Comment by pmzxlpyt** [comment]
2018/11/08 16:03:12.268 main.go:73: [fatal] join error etcdserver: unhealthy cluster

**Comment by disksing** [comment]
It doesn't matter. From the last log messages, we can learn it should have joined successfully.

Please try run "curl http://117.168.117.244:2379/pd/api/v1/members" on the host where pd4 belongs to (117.168.117.244) to verify if there is something wrong with the network.

Also please run "curl http://192.168.117.243:2379/pd/api/v1/members" to check if the new PD is included in member list.

**Comment by pmzxlpyt** [comment]
run "curl http://192.168.117.243:2379/pd/api/v1/members"  list:

{
  "header": {
    "cluster_id": 6621033703978490577
  },
  "members": [
    {
      "name": "pd1",
      "member_id": 1408441713399822969,
      "peer_urls": [
        "http://192.168.117.243:2380"
      ],
      "client_urls": [
        "http://192.168.117.243:2379"
      ]
    },
    {
      "name": "pd4",
      "member_id": 2087084767966204464,
      "peer_urls": [
        "http://192.168.117.44:2380"
      ],
      "client_urls": [
        "http://192.168.117.44:2379"
      ]
    },
    {
      "name": "pd2",
      "member_id": 5357273952687801877,
      "peer_urls": [
        "http://192.168.117.244:2380"
      ],
      "client_urls": [
        "http://192.168.117.244:2379"
      ]
    },
    {
      "name": "pd3",
      "member_id": 14095591246589658387,
      "peer_urls": [
        "http://192.168.117.245:2380"
      ],
      "client_urls": [
        "http://192.168.117.245:2379"
      ]
    }
  ],
  "leader": {
    "name": "pd1",
    "member_id": 1408441713399822969,
    "peer_urls": [
      "http://192.168.117.243:2380"
    ],
    "client_urls": [
      "http://192.168.117.243:2379"
    ]
  },
  "etcd_leader": {
    "name": "pd1",
    "member_id": 1408441713399822969,
    "peer_urls": [
      "http://192.168.117.243:2380"
    ],
    "client_urls": [
      "http://192.168.117.243:2379"
    ]
  }
}

but run "curl http://117.168.117.244:2379/pd/api/v1/members"   got  error msg:
curl: (7) Failed connect to 117.168.117.244:2379; 连接超时

**Comment by pmzxlpyt** [comment]
@disksing  any idea?

**Comment by pmzxlpyt** [comment]
my God!!!!!!!!!!!!

**Comment by tiancaiamao** [comment]
Is this issue solved?  @pmzxlpyt  @disksing 

By the way, you can file issues to TiDB and PD repository (rather than here) to get more rapid response.

**Comment by disksing** [comment]
It should be fixed. Please reopen if not :-) /cc @pmzxlpyt
