### ISSUE TITLE
Undocumented config options for TiKV

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#7161]
## Error Report

Page: https://docs.pingcap.com/tidb/stable/tikv-configuration-file

I noticed that `max-total-wal-size` was missing from the docs. A simple check shows that more options are likely missing:

```
[dvaneeden@dve-carbon tikv]$ for option in $(awk '/^# [^\[]/ { print $2 }' ./etc/config-template.toml); do grep "### \`$option\`" ../../pingcap/docs/tikv-configuration-file.md > /dev/null || echo "- $option"; done
```
- enable-io-snoop
- memory-usage-limit
- addr
- advertise-addr
- status-addr
- status-thread-pool-size
- enable-request-batch
- labels
- background-thread-count
- data-dir
- enable-async-apply-prewrite
- endpoints
- retry-interval
- retry-log-every
- retry-max-count
- raft-log-compact-sync-interval
- raft_log_reserve_max_ticks
- raft-engine-purge-interval
- consistency-check-method
- coprocessor-plugin-directory
- max-total-wal-size
- rate-limiter-refill-period
- info-log-level
- allow-concurrent-memtable-write
- info-log-level
- dir
- batch-compression-threshold
- target-file-size
- purge-threshold
- recovery-mode
- recovery-read-block-size
- recovery-threads
- enable-file-dictionary-log
- type
- type
- stream-channel-window
- batch-size
- sst-max-size
- enable-auto-tune
- home
- linux-user
- wake-up-delay-duration
- batch-keys
- max-write-bytes-per-sec
- ratio-threshold

**Comment by en-jin19** [comment]
@dveeden Thanks!

@tabokie Could you please take a look?
