### ISSUE TITLE
Search Engine Optimization error or redirect action error for docs

### ISSUE THREAD

**Issue by laingke** [pingcap/docs#7184]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

When I search anything in google, baidu or other search engine, it always lead me to the version 4.0 docs, NOT the stable version. Moreover, when I browse in the official website, it has the same action.

For example:

in [TiUP](https://tiup.io/) page, When I click `Read the document(English/Chinese)`, 

original link [English](https://pingcap.com/docs/stable/how-to/deploy/orchestrated/tiup/) redirect to [Deploy a TiDB Cluster Using TiUP](https://docs.pingcap.com/tidb/v4.0/production-deployment-using-tiup)

original link [Chinese](https://pingcap.com/docs-cn/stable/how-to/deploy/orchestrated/tiup/) redirect to [使用 TiUP 部署 TiDB 集群](https://docs.pingcap.com/zh/tidb/v4.0/production-deployment-using-tiup)

2. Describe your suggestion or addition.

The SEO or redirect action are wrong, correct it.

3. Provide some reference materials (documents, websites, etc) if you could.

[original link](https://pingcap.com/docs-cn/) -> [redirected link](https://docs.pingcap.com/zh/tidb/v4.0)

**Comment by shichun-0415** [comment]
Now, the links in "Read the document([English](https://docs.pingcap.com/tidb/stable/production-deployment-using-tiup)/[Chinese](https://docs.pingcap.com/zh/tidb/stable/production-deployment-using-tiup))" redirect to TiDB stable versions (currently 6.5). Therefore, this issue is resolved.
