### ISSUE TITLE
About Introduction of compression-per-level

### ISSUE THREAD

**Issue by qiaoxinke** [pingcap/docs#7224]
There is a mismatch between manual of English and Chinese version about Introduction of compression-per-level parameter.
The meaning of ”Optional values:” in English manual is difficult to understand. Is it a document bug in English version.
- English version:
File: [/release-5.3/tikv-configuration-file.md](https://docs.pingcap.com/tidb/stable/tikv-configuration-file)

- Chinese version:
https://docs.pingcap.com/zh/tidb/stable/tikv-configuration-file

**Comment by shichun-0415** [comment]
@tabokie PTAL. Thanks.

**Comment by shichun-0415** [comment]
@qiaoxinke Hi. As discussed in Ask Docs, this issue will be resolved by the English version of PR (https://github.com/pingcap/docs-cn/pull/7843).

**Comment by qiaoxinke** [comment]
Got it, thank you.
