### ISSUE TITLE
Document 'HANDLER' as not supported

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#7226]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

This page does not document `HANDLER` as not supported: https://docs.pingcap.com/tidb/stable/mysql-compatibility

2. Describe your suggestion or addition.

One line addition to say HANDLER commands are not supported.

3. Provide some reference materials (documents, websites, etc) if you could.

This is a MySQL feature.

**Comment by rebelice** [comment]
I will update the document for this issue later.
