### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by pmzxlpyt** [pingcap/docs#734]
From Navicat for MySQL connect to Tidb for query  ,it was often Lost connection over 30 seconds
[SQL]select t1.* from ori_Orders t1 inner join  (
SELECT AutoId from ori_Orders  t2  GROUP BY AutoId HAVING count(1)>1)  t3 
on t1.AutoId=t3.AutoId ;

[Err] 2013 - Lost connection to MySQL server during query

**Comment by pmzxlpyt** [comment]
How can i change  tidb the config?

**Comment by yikeke** [comment]
Hi @pmzxlpyt , did your issue get resolved? 

Because this issue is too old, I'll close it within 7 days if there is no new comment.

**Comment by yikeke** [comment]
Feel free to reopen it if you have any further questions~
