### ISSUE TITLE
sync-diff-inspector needs update about charset suppot

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#7351]
## Error Report

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/tidb/stable/sync-diff-inspector-overview

2. How would you like to improve it?

> TiDB uses the utf8_bin collation. If you need to compare the data in MySQL with that in TiDB, pay attention to the collation configuration of MySQL tables. If the primary key or unique key is the varchar type and the collation configuration in MySQL differs from that in TiDB, then the final check result might be incorrect because of the collation issue. You need to add collation to the sync-diff-inspector configuration file.

https://docs.pingcap.com/tidb/stable/character-set-and-collation gives details about support for `utf8mb4` and collations other than `utf8_bin`.

**Comment by ran-huang** [comment]
@Leavrth PTAL. Thanks!
