### ISSUE TITLE
Improve tiup mirror documentation

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#7362]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.

https://docs.pingcap.com/tidb/stable/tiup-mirror

This should be updated/extended with:

- Sync info from https://github.com/pingcap/tiup/blob/master/doc/user/mirrors.md
- Add information about how to update a local mirror from the official pingcap mirror 
- How to add custom packages
- Add a note about `tiup mirror set ...` causing `tiup mirror clone` to stop working. (`tiup mirror set --reset` to fix or use `$TIUP_MIRRORS`).

**Comment by qiancai** [comment]
@dveeden Thanks for raising this issue. 

Do you plan to resolve this issue by yourself? If so, can you provide an estimated date for creating the document PR? Thanks.

**Comment by dveeden** [comment]
Somewhat related: https://github.com/pingcap/tiup/pull/1705
