### ISSUE TITLE
date and time functions are not totally MySQL compatible

### ISSUE THREAD

**Issue by zhangyangyu** [pingcap/docs#7455]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/tidb/stable/date-and-time-functions#date-and-time-functions

2. How would you like to improve it?

Currently the date and time functions page directly links to MySQL docs. But there are still some specifiers not supported yet, see https://github.com/pingcap/tidb/issues/30082. Gives a wrong feeling to readers that all are supported.

**Comment by TomShawn** [comment]
@morgo @XuHuaiyu Could you please take a look? Can we describe the unsupported specifiers? Thanks~

**Comment by morgo** [comment]
Yes, I can take a look. Independent of the unsupported specifiers, I think it's also important to add some language to describe that date+time compatibility with MySQL is very difficult with invalid dates.
