### ISSUE TITLE
Can "Step 3. Replicate incremental data"  be done with TiCDC?

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs#7651]
File: [/release-5.4/incremental-replication-between-clusters.md](https://docs.pingcap.com/tidb/stable/incremental-replication-between-clusters)

I would like to know if [Step 3. Replicate incremental data](https://docs.pingcap.com/tidb/stable/incremental-replication-between-clusters#step-3-replicate-incremental-data) can be done with TiCDC, not TiDB Binlog.

**Comment by ran-huang** [comment]
@sunzhaoyang Can you take a look? Thanks.

**Comment by leoppro** [comment]
yes, you are right. the docs about replicating incremental data will be updated soon.

**Comment by leoppro** [comment]
for now, you can see ticdc manage docs: https://docs.pingcap.com/tidb/stable/manage-ticdc

**Comment by shichun-0415** [comment]
@yahonda Now we have a document describing how to replicate incremental data using TiCDC: https://docs.pingcap.com/tidb/stable/migrate-from-tidb-to-tidb#step-3-migrate-incremental-data. Shall we close this issue? Thanks.

**Comment by yahonda** [comment]
Thanks for the update and this document looks good.
