### ISSUE TITLE
The explain result of Semi join (correlated subquery) in English edition may wrong (Document error Feedback)

### ISSUE THREAD

**Issue by wuzhenglin510** [pingcap/docs#7710]
File: [/release-5.4/explain-subqueries.md](https://docs.pingcap.com/tidb/stable/explain-subqueries)

The explain result of Semi join (correlated subquery)  section in English edition  is different from Chinese

**Comment by en-jin19** [comment]
@wuzhenglin510 Thanks for your question!

@winoros Could you please take a look?

**Comment by en-jin19** [comment]
Hi @wuzhenglin510, the English document has been fixed, so we are going to close this issue on the evening of March 11. If you have any other questions, please feel free to leave comments, thanks you!
