### ISSUE TITLE
Document --topology-file in tiup/tiup-component-cluster-edit-config.md

### ISSUE THREAD

**Issue by joseespinoza** [pingcap/docs#7918]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
There is no documentation for `--topology-file` at https://docs.pingcap.com/tidb/dev/tiup-component-cluster-edit-config. The expectation is that you cannot use a “partial” or non-canonicalized topology file.<br/>
You’ll note that when you use `tiup cluster edit-config` to open the configuration in an editor, there are many more fields that are not part of the original topology file. But those fields are now part of the cluster definition, and especially immutable ones must be included in the new topology file.

2. Describe your suggestion or addition.
See above.

3. Provide some reference materials (documents, websites, etc.) if you could.
https://docs.pingcap.com/tidb/dev/tiup-component-cluster-edit-config

**Comment by TomShawn** [comment]
@qqqdan @lilyjazz Could you please help take a look? Thanks!

**Comment by AstroProfundis** [comment]
The `--topology-file` of `edit-config` command is used to edit a provided topology file **instead** of the one in default location (the one in tiup's home directory under the cluster's path), it's not meant to "merge" or "import" from an external config. This is useful for some external tools using `tiup-cluster` as a pure executor and they want to manage all metadata by themselves.

Could you describe some details of what were you trying to archive by trying the `--topology-file` argument?

**Comment by shichun-0415** [comment]
@AstroProfundis Thanks for your information. @joseespinoza Do you think the information above resolves your issue? If not, please let us know.
