### ISSUE TITLE
session tracker: Add GTIDs context to the OK packet is not documented as unsupported

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#7979]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

On https://docs.pingcap.com/tidb/stable/mysql-compatibility

It claims 5.7 compatibility, but does not note that this feature is not supported:
https://dev.mysql.com/worklog/task/?id=6128

2. Describe your suggestion or addition.

Add a note about incompatibility.

3. Provide some reference materials (documents, websites, etc) if you could.

See above.

**Comment by TomShawn** [comment]
@morgo addressed in https://github.com/pingcap/docs/pull/11265. PTAL
