### ISSUE TITLE
found a keyword not in docment

### ISSUE THREAD

**Issue by qiuwenhuifx** [pingcap/docs#7982]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

https://docs.pingcap.com/zh/tidb/v5.1/keywords
2. How would you like to improve it?

alter table to_test_keyword add placement varchar(200);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 49 near "varchar(200)"
alter table to_test_keyword add \`placement\` varchar(200);
Query OK, 0 rows affected (0.51 sec)

**Comment by ran-huang** [comment]
@bb7133 Is this an undocumented keyword? We might need to add this to the docs
