### ISSUE TITLE
Cached tables documentation shows 404

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs#8110]
## Error Report

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?
https://docs.pingcap.com/tidb/v6.0/cached-tables/#cached-tables

2. How would you like to improve it?
I expect this page shows one of the TiDB 6.0.0 new feature Cached tables but it raises 404 status code.

**Comment by TomShawn** [comment]
@yahonda Thanks for your feedback. Now this page is available. Please try again.

**Comment by yahonda** [comment]
Confirmed it is available. Thanks for the quick fix.
