### ISSUE TITLE
Add section on mysql compatibility page: ANALYZE TABLE command

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#833]
Analyze table in TiDB takes *significantly* longer in TiDB than MySQL (not a bad thing in itself - it builds different/better statistics), whereas MySQL(InnoDB) just samples random pages.

It should be documented, since some naive scripts may need to be changed (i.e. expecting ANALYZE to take less than a second, when it takes 30 minutes..)

**Comment by kolbe** [comment]
Since ANALYZE TABLE is *such* a lightweight command in MySQL that I wonder if it would possibly be better to add a new keyword to run this "full" TiDB ANALYZE that takes a long time? `ANALYZE [TIDB] TABLE` or something? Just a thought to prevent poor administrators from getting into lots of trouble.

**Comment by morgo** [comment]
@kolbe I think you would still need to do something for `ANALYZE`, it is not safe to just make it a noop.  We plan to add incremental `ANALYZE` soon, in which case this may become less of an issue.  I think we should document for now though.

**Comment by kolbe** [comment]
I think that kind of depends on the timeline for implementing the "incremental `ANALYZE`". Right now, `KILL` (without the `TIDB` keyword) is a noop, so there's some precedent for adding the `TIDB` keyword to dangerously divergent behavior. As more of these features are added to TiDB, and these operations are made less surprising, we'll presumably also be seeing an upward curve in adoption, so plenty of people making assumptions about `ANALYZE` and other MySQL-typical operations will be bringing their scripts and tools to TiDB and will be able to make use of the improved behaviors.
