### ISSUE TITLE
link is not proper rendered in "Monitoring and debugging" section 

### ISSUE THREAD

**Issue by wxiaomou** [pingcap/docs#8400]
File: [/release-5.4/encryption-at-rest.md](https://docs.pingcap.com/tidb/stable/encryption-at-rest) seems there link . The link in this statement in `Please refer to [TiKV Control](/tikv-control.md#dump-encryption-metadata] document`. is not proper rendered

**Comment by shichun-0415** [comment]
@wxiaomou Thank you for your feedback. I have fixed the problem in a PR. You can visit the doc and check the link.
