### ISSUE TITLE
Support k8s address resolution

### ISSUE THREAD

**Issue by mmexus** [pingcap/docs#8468]
File: [/master/tidb-lightning/monitor-tidb-lightning.md](https://docs.pingcap.com/tidb/dev/monitor-tidb-lightning)

For the scrape_configs mentioned in the doc,
scrape_configs:
  - job_name: 'tidb-lightning'
    static_configs:
      - targets: ['192.168.20.10:8289']
currently I don’t have a static ip for the pod since it’s running in the k8s, can I use k8s service name as the target? 
Ans:  It is fine to use k8s address. Just make sure DNS will translate the k8s address to the correct ip address.

**Comment by TomShawn** [comment]
@sunzhaoyang Could you please take a look? Thanks~

**Comment by Ehco1996** [comment]
@lrvgz yes you can  use a k8s svc as an endpoint but make sure your svc config is correct

**Comment by ran-huang** [comment]
Closing this issue as it is resolved. If you have any other questions regarding the usage of TiDB and its related tools, feel free to start a discussion on the community forum ([English](https://ask.pingcap.com) or [Chinese](https://asktug.com/)).
