### ISSUE TITLE
LOCK TABLES and UNLOCK TABLES statements needs documented

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs#8632]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.
`LOCK TABLES` and `UNLOCK TABLES` are implemented via https://github.com/pingcap/tidb/pull/10343

2. Describe your suggestion or addition.
It needs to be documented in https://docs.pingcap.com/tidb/dev/mysql-compatibility or somewhere.

3. Provide some reference materials (documents, websites, etc) if you could.

**Comment by qiancai** [comment]
@crazycs520 Would you please help check and confirm the compatibility info of 
LOCK TABLES and UNLOCK TABLES statements should be added to user docs? Thanks.
