### ISSUE TITLE
update DM document

### ISSUE THREAD

**Issue by GregoryIan** [pingcap/docs#874]
- [x] [deploy](https://pingcap.com/docs/tools/data-migration-deployment/),  remove server_id and use source_id in sample config file
- [x] [sharding overview and design detail](https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/shard-table/shard-merge.md)
  - Updated and added in #887 
- [x] [troubleshot shard ddl lock](https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/shard-table/handle-DDL-lock.md)
  - Added in #876 
- [x] put `Precheck the upstream MySQL instance configuration` of [task management](https://pingcap.com/docs/tools/data-migration-manage-task/) into a separate document
    - Add the precheck to the deployment doc (after confirming with @GregoryIan)
- [x] add [relay log introduction](https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/features/relay-log.md)
- [x] update [troubleshot](https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/troubleshoot/skip-replace-sqls.md)
- [x] add [caution for restarting dm](https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/maintenance/caution-for-restart-dm.md)
    - Already added [here](https://github.com/pingcap/docs/blob/master/tools/dm/cluster-operations.md#restart-cluster-components).
- [x] add [sample task scenario](https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/use-cases/one-tidb-slave.md)

**Comment by GregoryIan** [comment]
@lilin90 I simply sorted out the documents that need to be modified, and you can adjust them. I will help you to modify them next week, and I hope that you can take the time to deploy and use DM to confirm this document is useful. :smiley:   Let's cheer together.

**Comment by lilin90** [comment]
Thanks! Currently, we already have the [relay log](https://github.com/pingcap/docs/blob/master/tools/dm-relay-log.md) and [simple task scenario](https://github.com/pingcap/docs/blob/master/tools/dm-simple-synchronization-scenario.md) documents, and I added them to TOC in #869. And I saw your PR #873. We can discuss the TOC later.

**Comment by GregoryIan** [comment]
@lilin90 you can add the items that you found while you try DM into this issue, easy to trace them

**Comment by lilin90** [comment]
@Gregorylan Got it. I'll add them later.
