### ISSUE TITLE
Does the duplicate TableReader Operator appeared at second and third row means the same Operator that just distinguished from different engine and each condition?

### ISSUE THREAD

**Issue by coolZhangSir** [pingcap/docs#8748]
File: [/release-5.4/choose-index.md](https://docs.pingcap.com/tidb/stable/choose-index)

**Comment by coolZhangSir** [comment]
![image](https://user-images.githubusercontent.com/27146728/170622439-6907ff86-03fe-452b-a397-a73b0690e47b.png)
does the same operator means which would be picked in the two different condition?

**Comment by Oreoxmt** [comment]
@winoros Could you please take a look? Thanks~

**Comment by winoros** [comment]
Yes, the first one is the TableReader on TiKV, and the second one is the TableReader on TiFlash

**Comment by coolZhangSir** [comment]
> Yes, the first one is the TableReader on TiKV, and the second one is the TableReader on TiFlash

Thanks for your answer,  I'm a beginner with TiDB, when I read the table, Although I guess the positive answer, but I'm not sure, so could we adjust the table style(merge and center) which maybe eliminate the doubt and let up understood more clear, like this:
![image](https://user-images.githubusercontent.com/27146728/170638668-c49f09d2-3869-48c4-9866-a45fe5672f7a.png)

**Comment by coolZhangSir** [comment]
> Yes, the first one is the TableReader on TiKV, and the second one is the TableReader on TiFlash

Thanks
