### ISSUE TITLE
`tidb_enable_change_multi_schema` needs documented since this message is visible to users

### ISSUE THREAD

**Issue by yahonda** [pingcap/docs#8787]
## Change Request

1. Describe what you find is inappropriate or missing in the existing docs.

`tidb_enable_change_multi_schema` needs documented since this message is visible to users. There was a similar request https://github.com/pingcap/docs/issues/7093 that was closed because this variable is not visible to users at that time.

Now https://github.com/pingcap/tidb/pull/29526 has been merged,  Users will get 
`ERROR 8200 (HY000): can't drop column c3 with tidb_enable_change_multi_schema is disable` message.

### Steps to reproduce

- Run `tiup playground`
```
tiup playground
```

- Drop indexed column
```
mysql --comments --host 127.0.0.1 --port 4000 -u root test
create table t(id int primary key, c1 int, c2 int, c3 int, index idx1(c1, c2), index idx2(c3));
alter table t drop column c3;
set global tidb_enable_change_multi_schema = on;
alter table t drop column c3;
```

### Actual results

```
% mysql --comments --host 127.0.0.1 --port 4000 -u root test
... snip ...
mysql> create table t(id int primary key, c1 int, c2 int, c3 int, index idx1(c1, c2), index idx2(c3));
Query OK, 0 rows affected (0.10 sec)

mysql> alter table t drop column c3;
ERROR 8200 (HY000): can't drop column c3 with tidb_enable_change_multi_schema is disable
mysql> set global tidb_enable_change_multi_schema = on;
Query OK, 0 rows affected (0.03 sec)

mysql> alter table t drop column c3;
Query OK, 0 rows affected (0.30 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.0.0
Edition: Community
Git Commit Hash: 36a9810441ca0e496cbd22064af274b3be771081
Git Branch: heads/refs/tags/v6.0.0
UTC Build Time: 2022-03-31 10:27:25
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.01 sec)

mysql>
```

3. Describe your suggestion or addition.
`tidb_enable_change_multi_schema` needs documented since this message is visible to users and it is difficult for users to understand why this variables needs configured, MySQL can drop indexed column by default.

4. Provide some reference materials (documents, websites, etc) if you could.

https://github.com/pingcap/docs/issues/7093
https://github.com/pingcap/tidb/pull/29526

**Comment by shichun-0415** [comment]
@yahonda Thanks for your feedback. @AilinKid Could you please take a look?

**Comment by AilinKid** [comment]
actually `tidb_enable_change_multi_schema` is not for users, it's an internal switch because change_multi_schema hasn't been  GA yet.

**Comment by yahonda** [comment]
Sorry I do not agree with that. If this is not for users, This `ERROR 8200 (HY000): can't drop column c3 with tidb_enable_change_multi_schema is disable` message also needs reviewed / revised.

**Comment by tangenta** [comment]
/assign

OK. Let me add the document of this variable.
