### ISSUE TITLE
the link [Developer install guide (single machine)] seems to be wrong.

### ISSUE THREAD

**Issue by xiaobogaga** [pingcap/docs#880]
Hi, I found there is a **wrong link** on page [TiDB quickStart](https://pingcap.com/docs/QUICKSTART/) and with text **"Developer install guide (single machine)"**, actually this link refers to http://www.tocker.ca/this-blog-now-powered-by-wordpress-tidb.html, So, I think this is definitely wrong. 

A fix might be required.

**Comment by queenypingcap** [comment]
Thanks @xiaobogaga ! 
The link is contributed by the community and points to the contributor's personal blog where he installed and deployed a single-machine TiDB for his blog. So the link is not wrong and we welcome more links from the community!
Please be noted that the deployment is for developer experiment only, not for production usage.

**Comment by gregwebs** [comment]
@queenypingcap I also find this link to be confusing. @morgo maybe you can create a post designed for the audience that would click this link. I think the way the content is laid out (starting with a personal announcement) is very confusing when you click the link, and if it were just slightly re-titled and re-arranged it would make sense.
