### ISSUE TITLE
Links to the archived tidb-ansible repository should be replaced

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#8816]
## Error Report

1. What is the URL/path of the document related to this issue?
```
$ git grep '/github.com/pingcap/tidb-ansible' | egrep -v '^releases/' | cut -d: -f1
best-practices/high-concurrency-best-practices.md
deploy-monitoring-services.md
tidb-troubleshooting-map.md
```

2. How would you like to improve it?

The links should be checked and updated/removed where applicable.

Possible replacements:

For `deploy-monitoring-services.md`:
- https://github.com/pingcap/tidb/tree/master/metrics/grafana
- https://github.com/tikv/tikv/tree/master/metrics/grafana
- https://github.com/tikv/pd/tree/master/metrics/grafana

For `tidb-troubleshooting-map.md`:
- Remove info for older (< v5.0) versions.

For `best-practices/high-concurrency-best-practices.md`:
- The functionality of `table-regions.py` might need to be moved to `tiup` and/or `pd-ctl` or the script might need to be moved.

Maybe there should be a way for CI/CD to flag links to archived repositories outside of the release notes

**Comment by TomShawn** [comment]
@dveeden https://github.com/pingcap/docs/pull/8834 PTAL
