### ISSUE TITLE
Lost connection to MySQL server during query using count distinct

### ISSUE THREAD

**Issue by Soft-me** [pingcap/docs#952]
Report this odd situation.
Running code following, 
```
SELECT
	COUNT( DISTINCT ( a.id ) ) 
FROM
	sup_after AS a
	LEFT OUTER JOIN order AS o ON a.sup_id = o.id
	LEFT OUTER JOIN direct AS d ON a.sup_id = d.id
WHERE
	 d.`code` = '138590704832094668' 
OR 
	 o.`code` = '138590704832094668' 
```
I get error:
`2013 - Lost connection to MySQL server during query`
When I remove `distinct` and rerun, it works.

**Comment by morgo** [comment]
@Soft-me This looks like it could be a bug.  Do you mind recreating the issue in https://github.com/pingcap/tidb?

We will need to know the version of TiDB you are using and the output of `SHOW CREATE TABLE order; SHOW CREATE TABLE direct`.  Thanks!
