### ISSUE TITLE
tiup: inappropriate translation of command options

### ISSUE THREAD

**Issue by tninomiya** [pingcap/docs#9529]
## Error Report

Issue about Japanese translation

1. Some command options are translated into Japanese, which should not be, on TiUP command reference.
2. Large part of options with double hyphen `--` are transformed to  single hyphen `-`

Please answer the following questions before submitting your issue. Thanks!

1. What is the URL/path of the document related to this issue?

- https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-clean
- https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-deploy
- https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-destroy
- https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-display
- https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-import
- https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-patch
- https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-reload
- https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-scale-in
- https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-scale-out
- https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-template
- https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-upgrade

2. How would you like to improve it?

> 1.

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-clean
- `- 全て` -> `-all`
- `- データ` -> `--data`
- `- ログ` -> `--log`
- `--無視-役割` -> `--ignore-role`

```console
$ tiup cluster clean -h
...
Flags:
      --all                       Cleanup both log and data (not include audit log)
      --audit-log                 Cleanup TiDB-server audit log
      --data                      Cleanup data
  -h, --help                      help for clean
      --ignore-node stringArray   Specify the nodes or hosts whose data will be retained
      --ignore-role stringArray   Specify the roles whose data will be retained
      --log                       Cleanup log
```

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-deploy
- `--ラベルなし` -> `--no-labels`

```console
$ tiup cluster deploy -h
...
Flags:
  -h, --help                   help for deploy
  -i, --identity_file string   The path of the SSH identity file. If specified, public key authentication will be used. (default "<masked>")
      --ignore-config-check    Ignore the config check result of components
      --no-labels              Don't check TiKV labels
  -p, --password               Use password of target hosts. If specified, password authentication will be used.
      --skip-create-user       (EXPERIMENTAL) Skip creating the user specified in topology.
  -u, --user string            The user name to login via SSH. The user must has root (or sudo) privilege. (default "<masked>")
```

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-destroy
- `- 力` -> `--force`

```console
$ tiup cluster destroy -h
...
Flags:
      --force                          Force will ignore remote error while destroy the cluster
  -h, --help                           help for destroy
      --retain-node-data stringArray   Specify the nodes or hosts whose data will be retained
      --retain-role-data stringArray   Specify the roles whose data will be retained
```

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-display
- `-ダッシュボード` -> `--dashboard`

```console
$ tiup cluster display -h
...
Flags:
      --dashboard             Only display TiDB Dashboard information
  -h, --help                  help for display
      --labels                Only display labels of specified TiKV role or nodes
  -N, --node strings          Only display specified nodes
  -R, --role strings          Only display specified roles
      --status-timeout uint   Timeout in seconds when getting node status (default 10)
      --uptime                Display with uptime
      --version               Only display TiDB cluster version
```

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-import
- `- 在庫` -> `--inventory`
- `--バックアップなし` -> `--no-backup`
- `--名前を変更` -> `--rename`

```console
$ tiup cluster import -h
Flags:
      --ansible-config string   The path to ansible.cfg (default "ansible.cfg")
  -d, --dir string              The path to TiDB-Ansible directory
  -h, --help                    help for import
      --inventory string        The name of inventory file (default "inventory.ini")
      --no-backup               Don't backup ansible dir, useful when there're multiple inventory files
  -r, --rename NAME             Rename the imported cluster to NAME
```

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-patch
- `-上書き` -> `--overwrite`
- `--転送タイムアウト` -> `--transfer-timeout`
- `- オフライン` -> `--offline`

```console
$ tiup cluster patch -h
...
Flags:
  -h, --help                    help for patch
  -N, --node strings            Specify the nodes
      --offline                 Patch a stopped cluster
      --overwrite               Use this package in the future scale-out operations
  -R, --role strings            Specify the roles
      --transfer-timeout uint   Timeout in seconds when transferring PD and TiKV store leaders (default 300)
```

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-reload
- `- 力` -> `--force`
- `--転送タイムアウト` -> `--transfer-timeout`
- `--スキップ-再起動` -> `--skip-restart`

```console
$ tiup cluster reload -h
...
Flags:
      --force                   Force reload without transferring PD leader and ignore remote error
  -h, --help                    help for reload
      --ignore-config-check     Ignore the config check result
  -N, --node strings            Only reload specified nodes
  -R, --role strings            Only reload specified roles
      --skip-restart            Only refresh configuration to remote and do not restart services
      --transfer-timeout uint   Timeout in seconds when transferring PD and TiKV store leaders (default 300)
```

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-scale-in
- `- 力` -> `--force`
- `--転送タイムアウト` -> `transfer-timeout`

```console
$ tiup cluster scale-in -h
...
Flags:
      --force                   Force just try stop and destroy instance before removing the instance from topo
  -h, --help                    help for scale-in
  -N, --node strings            Specify the nodes (required)
      --transfer-timeout uint   Timeout in seconds when transferring PD and TiKV store leaders (default 300)
```

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-scale-out
- `--ラベルなし` -> `--no-labels`

```console
$ tiup cluster scale-out -h
...
Flags:
  -h, --help                   help for scale-out
  -i, --identity_file string   The path of the SSH identity file. If specified, public key authentication will be used. (default "<masked>")
      --no-labels              Don't check TiKV labels
  -p, --password               Use password of target hosts. If specified, password authentication will be used.
      --skip-create-user       (EXPERIMENTAL) Skip creating the user specified in topology.
      --stage1                 Don't start the new instance after scale-out, need to manually execute cluster scale-out --stage2
      --stage2                 Start the new instance and init config after scale-out --stage1
  -u, --user string            The user name to login via SSH. The user must has root (or sudo) privilege. (default "<masked>")
```

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-template
- `- 満杯` -> `--full`
- `--マルチDC` -> `--multi-dc`

```console
$ tiup cluster template -h
...
Flags:
      --alertmanager-servers strings   List of alermanager servers
      --arch string                    Supported values: "amd64", "arm64". (default "amd64")
      --data-dir string                TiDB Cluster data storage directory. (default "/tidb-data")
      --deploy-dir string              Storage directory for cluster deployment files, startup scripts, and configuration files. (default "/tidb-deploy")
      --full                           Print the full topology template for TiDB cluster.
      --grafana-servers strings        List of grafana servers (default [127.0.0.1])
      --group string                   group is used to specify the group name the user belong to if it's not the same as user.
  -h, --help                           help for template
      --local                          Print and render template for deploying a simple cluster locally.
      --monitoring-servers strings     List of monitor servers (default [127.0.0.1])
      --multi-dc                       Print template for deploying to multiple data center.
      --pd-servers strings             List of PD servers (default [127.0.0.1])
      --ssh-port int                   SSH port of servers in the managed cluster. (default 22)
      --tidb-servers strings           List of TiDB servers (default [127.0.0.1])
      --tiflash-servers strings        List of TiFlash servers
      --tikv-servers strings           List of TiKV servers (default [127.0.0.1])
      --user string                    The user who runs the tidb cluster. (default "tidb")
```

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-upgrade
- `- 力` -> `--force`
- `--転送タイムアウト` -> `--transfer-timeout`
- `- オフライン` -> `--offline`

```console
$ tiup cluster upgrade -h
...
Flags:
      --force                   Force upgrade without transferring PD leader
  -h, --help                    help for upgrade
      --ignore-config-check     Ignore the config check result
      --offline                 Upgrade a stopped cluster
      --transfer-timeout uint   Timeout in seconds when transferring PD and TiKV store leaders (default 600)
```

## References

```console
$ tiup --version
1.10.2 tiup
Go Version: go1.18.3
Git Ref: v1.10.2
GitHash: 2de5b500c9fae6d418fa200ca150b8d5264d6b19
```

**Comment by yahonda** [comment]
Thanks for the detailed report.
We have updated these Japanese translations. Please also validate these translations are correct now.

Thanks.

**Comment by tninomiya** [comment]
@yahonda 
Thank you for your update.
I confirmed that every `1. Some command options are translated into Japanese, which should not be, on TiUP command reference.` have been fixed correctly.

However, I noticed that there are some points to be fixed for `2. Large part of options with double hyphen -- are transformed to single hyphen -` . Following is the summary of places to be patched.

Please feel free to let me know if I should open another issue for remaining points.

Thanks,

---

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-clean

- `-h、-help` -> `-h, --help`

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-deploy

- `-u、-user` -> `-u、--user`
- `-i、-identity_file` -> `-i、--identity_file`
- `-p、-password` -> `-p、--password`
- `-h、-help` -> `-h、--help`

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-destroy

- `-h、-help` -> `-h、--help`

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-display

- `-N、-node` -> `-N、--node`
- `-R、-role` -> `-R、--role`
- `-h、-help` -> `-h、--help`

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-import

- `-d、-dir` -> `-d、--dir`
- `-h、-help` -> `-h、--help`

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-patch

- `-N、-node` -> `-N、--node`
- `-R、-role` -> `-R、--role`
- `-h、-help` -> `-h、--help`

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-reload

- `-N、-node` -> `-N、--node`
- `-R、-role` -> `-R、--role`
- `-h、-help` -> `-h、--help`

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-scale-in

- `-N、-node` -> `-N、--node`
- `-h、-help` -> `-h、--help`

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-scale-out

- `-u、-user` -> `-u、--user`
- `-i、-identity_file` -> `-i、--identity_file`
- `-p、-password` -> `-p、--password`
- `-h、-help` -> `-h、--help`

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-template

- `-h、-help` -> `-h、--help`

> https://docs.pingcap.com/ja/tidb/stable/tiup-component-cluster-upgrade

- `-h、-help` -> `-h、--help`

**Comment by yahonda** [comment]
Thanks for the review. 

> Please feel free to let me know if I should open another issue for remaining points.
Would you open another issue so that we can track each issue separately?

**Comment by tninomiya** [comment]
@yahonda 
Sure, please let me close this issue and create another one.
Thank you for your guidance.
