### ISSUE TITLE
develop: a typo in dev-guide-transaction-troubleshoot

### ISSUE THREAD

**Issue by Oreoxmt** [pingcap/docs#9825]
File: [/release-6.1/develop/dev-guide-transaction-troubleshoot.md](https://docs.pingcap.com/tidb/stable/dev-guide-transaction-troubleshoot)

- this command should be `connection.exec('ROLLBACK');`.
- the admonition `Note` rendered not as expected.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/60599231/182824631-0e858bc1-c792-4ce4-a6c2-de78c4e67c03.png">

**Comment by Icemap** [comment]
That's too weird. Our old documents seem never been tested.

**Comment by Icemap** [comment]
Fixed.
