### ISSUE TITLE
Any Docs about how to sync two TiDB with syncer or something else

### ISSUE THREAD

**Issue by ihipop** [pingcap/docs#985]
## Question

We have  doc with how to make full backup of  `TIDB` with `mydumper`
And sync `MySQL` server to TIDB with `syncer`
but we have no Doc about  sync between two TiDB.
a full backup of  `TIDB` with `mydumper` takes too much time,We want a way to sync increment data  between two TiDB.

**Comment by kennytm** [comment]
Hi. You could use [TiDB-Binlog](https://pingcap.com/docs/tools/tidb-binlog-cluster/) ([Chinese docs](https://pingcap.com/docs-cn/tools/tidb-binlog-cluster/)) to synchronize changes from one TiDB cluster to another TiDB database.

**Comment by ihipop** [comment]
@kennytm Thanks,I will read about it carefully
