### ISSUE TITLE
Move from master to published branch, make README.md more instructive

### ISSUE THREAD

**Issue by morgo** [pingcap/docs#999]
## Change Request

**This repository is ONLY used to solve issues related to DOCS.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

Currently `README.md` is a duplicate of `overview.md`. We also publish to master.

2. Describe your suggestion or addition.

- For SEO, it is bad to have the master branch contain content (since it will be indexed by Google, and conflict with pingcap.com/docs).
- We should move the docs to a `published` branch and make the master branch bare.
- The `readme.md` should tell people to look at the master branch for contributions.

3. Provide some reference materials (documents, websites, etc) if you could.

https://webapps.stackexchange.com/questions/67344/how-to-prevent-a-public-github-repository-from-showing-up-on-search-results/67345#67345

**Comment by nullnotnil** [comment]
GitHub has changed how they index branches, and `master` is no longer indexed either. This can be closed.
